### ISSUE TITLE
Not Appearing on new leaderboards

### ISSUE THREAD

**Issue by pizza334** [Avicus/Issues#1001]
I don't appear to come up on the new leaderboards , went to kills overall and said 'Player not found in the context of your search'. after i typed my name. 
Tried this on all the sub-categories and same message.

No idea if it's something to do with my senior perms or what.

Thanks.

**Comment by thekeenant** [comment]
Neither am I anynore? @austinlmayes

**Comment by flohlen** [comment]
I can confirm this from happening, yet some of the configurations do work (weekly kills, weekly time online), but some don't (overall time online). So I assume it's not a permission issue..

**Comment by thekeenant** [comment]
Fixed!
