### ISSUE TITLE
keepInventory Bow Glitching

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1003]
When you die on the map Halcyon, you still have your inventory in the death screen. You still could use the bow to shoot people, and they won't know where the arrows came from. This could be abused so much, but it only works on maps where you don't drop your inventory when you die. (Which is in most maps not the case)

Hitting the enemies with your sword doesn't work, because you'll simply respawn. :P

Here a video (I tested the glitch, didn't abuse it): https://www.youtube.com/watch?v=XpqH8pOYO-Y

Greetings,
-Atdit

**Comment by andrgorr** [comment]
@AtditC Do you know why even the inventory is kept in death screen in this map? Like, does it have any rationale to it?

**Comment by andrgorr** [comment]
oopsies

**Comment by Atdit** [comment]
Well my guess is that keepInventory (a vanilla minecraft gamerule (/gamerule keepInventory) was somehow on/true, but it might just be something in the XML. I'm not a Map Dev so I can't tell sorry.

**Comment by AustinLMayes** [comment]
keepInventory would not have an effect whatsoever since you never actually die.

**Comment by OldManTigerMask** [comment]
@javipepe I think what's happening is, when you 'die' your inventory doesn't get cleared and you can effect other users (by dealing damage, etc.)
Something to do with plugin I presume because I don't think there's anything in XML that does it. (I'm not sure)

Or it could just be your receiving the inventory too early

meh idk?

**Comment by joelmce** [comment]
Do you know the map names where this issue occurs?

**Comment by joelmce** [comment]
@javipepe Could it be to do something with reward loadouts? I've noticed maps without rewards don't have this glitch...

**Comment by Atdit** [comment]
I only know that it works on Halcyon @joelmcelroy maybe there are other maps too, don't know.

**Comment by Atdit** [comment]
Update: It happens on the map Amazon Kingdom too

**Comment by Wqrld** [comment]
#1027 didnt see this one before i made that but weird

**Comment by AustinLMayes** [comment]
Can't reproduce

**Comment by Atdit** [comment]
Reopen this please, it's still a bug
