### ISSUE TITLE
You can view other users deleted forum posts

### ISSUE THREAD

**Issue by johannestheigen** [Avicus/Issues#1004]
Hello Avicus developers I found this interesting bug on the web while looking at _DISTRACTION_'s profile. The bug is that you can view other users deleted forum posts and even if you're not even logged in. You can view them. Here are two screenshots of it:
![image](https://cloud.githubusercontent.com/assets/13437351/19214903/a86571da-8d8f-11e6-8b6c-58a73d799763.png)
![image](https://cloud.githubusercontent.com/assets/13437351/19214904/b6d992f0-8d8f-11e6-8d1a-9a08dc8bf598.png)

Thanks for reading regards Fanta.

**Comment by andrgorr** [comment]
@alm WHAT

**Comment by andrgorr** [comment]
@AustinLMayes
