### ISSUE TITLE
Allow MapDevs to edit posts

### ISSUE THREAD

**Issue by legoche** [Avicus/Issues#1008]
Would be very handy for updating map acceptances and removing download links from threads. Obviously if abused, we would be given an applicable punishment.

**Comment by ProfessorUtonium** [comment]
or add tags for accepted/denied/reviewing which mapdevs can add as well

**Comment by andrgorr** [comment]
@legoche @ProfessorUtonium You guys now have access to editing post & replies in `Map Releases` subforum. Also, added handy dandy `Accepted / Reviewing / Denied` mapdev-only tags to that subforum as well.

Enjoy :sparkles:
