### ISSUE TITLE
Spawn Eggs

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#1009]
Spawn eggs don't work. Intentional or no?
If it's not, would it be an XML error or just the server?

**Comment by thekeenant** [comment]
Xml

**Comment by Prodigy4532** [comment]
You can set this un the XML and the spawner egg will work

`<world>
  <mobs>
    <any>
      <all>
        <entity>MOB</entity>
        <spawn>spawner egg</spawn>
      </all>
    </any>
  </mobs>
</world>`
