### ISSUE TITLE
@devs

### ISSUE THREAD

**Issue by ItsJunr** [Avicus/Issues#1010]
Please add a comma in between maintaining and or, it bothers me so much.
Picture:
https://gyazo.com/851c9f356193459ad0cba80db732243f

**Comment by joelmce** [comment]
Grammatically that's correct?

**Comment by ItsJunr** [comment]
It's not, there needs to be a comma in front of or to be grammatically correct.

**Comment by flohlen** [comment]
I'm pretty sure it's correct and doesn't need changing.

**Comment by thekeenant** [comment]
The serial comma is optional, it is correct.
