### ISSUE TITLE
Website: Profile Page - the sidebar overlapping the appeals

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#1011]
<img src="http://i.imgur.com/88cl4fH.png" alt="image" style="max-width:100%;">

This occurs when you make your browser smaller than usual
<img src="https://cloud.githubusercontent.com/assets/9856226/19467493/3a306f28-955d-11e6-9eee-ff691ee48e17.png" alt="image" style="max-width:100%;">

**Comment by AustinLMayes** [comment]
Appears to be fixed
