### ISSUE TITLE
/match unexecutable

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#1012]
<iframe width="560" height="315" src="https://www.youtube.com/embed/3eUfuuEMoM8" frameborder="0" allowfullscreen></iframe>

https://youtu.be/3eUfuuEMoM8

No message, no nothing is displayed

**Comment by thekeenant** [comment]
We have yet to add the command!

Objectives command and map command both work though.

**Comment by OldManTigerMask** [comment]
Ah ok! Thanks for clearing it up
