### ISSUE TITLE
Warns do appear in chat

### ISSUE THREAD

**Issue by flohlen** [Avicus/Issues#1013]
I guess it's pretty straight forward and easy to recreate.

Basically warns appear in chat, which shouldnt really be since warns are a matter between the staff member and the player that was warned, it should stay private.

We have voted on it and came to the conclusion that warns shouldn't show up so I guess it's a bug.

**Comment by AustinLMayes** [comment]
This is intended.

**Comment by flohlen** [comment]
Change the label to enhancement then
