### ISSUE TITLE
I can't see my profile page

### ISSUE THREAD

**Issue by Prodigy4532** [Avicus/Issues#1014]
i changed my mc name like 2 days ago and now i can't see my profile.

Images: 

http://prntscr.com/cxew5f
http://prntscr.com/cxew8r
http://prntscr.com/cxewb1

Regards - Prodigy4532

**Comment by OldManTigerMask** [comment]
It's accessible, I found it :)

You just need to wait a few days for it to work, I think any how it's working
@Prodigy4532 Want to close it? It's working for me

**Comment by AustinLMayes** [comment]
@OldManTigerMask please do not comment on issues that you are not related to, Thanks.

Also, @Prodigy4532 was an issue with some old backups that has since been resolved. 

To clear up any confusion, usernames update _instantly_ whenever you log in with a new name.
