### ISSUE TITLE
Forum Profile

### ISSUE THREAD

**Issue by DomSpicer** [Avicus/Issues#1015]
I stole Cuddle's name, 'LetsCuddle' and now when I go to my forum profile, it goes to 3_16am instead of WantThePing.

Pls send help :c

**Comment by AustinLMayes** [comment]
Only one user has ever had the username and it's not you.

**Comment by DomSpicer** [comment]
Want proof that it's me? I still currently own LetsCuddle. You can even ask
Avicus staff?
