### ISSUE TITLE
Can't edit stickied threads

### ISSUE THREAD

**Issue by flohlen** [Avicus/Issues#1020]
Heeya,
for some strange reasons neither mods nor senior mods have permissions to edit stickied threads, yet junior mods do have perms.

Tested by 
- Pizza334 (Senior Moderator - Media - Diamond - Emerald - Tournament Runner Up)
- resepignev (Moderator - Referee - Diamond - Translator)
- Atdit (Junior Moderator - Diamond)

**Comment by Atdit** [comment]
AtditC (Junior Moderator - Diamond)*

c:

**Comment by AustinLMayes** [comment]
Mods+ can perform all actions on discussions.
