### ISSUE TITLE
Friend request

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#1021]
https://gyazo.com/affbfa3691b97a96c5ba278c91f98096
I've already accepted the friend request multiple times, but it always end up being unaccepted and continues to be under Pending Friend Requests

**Comment by andrgorr** [comment]
Who is the user in question?

**Comment by DaFrozenBlaze** [comment]
OldManTigerMask, his face is still there under Pending Friend Requests in the photo

**Comment by AustinLMayes** [comment]
Cleared all friendships between the two users, should be fixed now.
