### ISSUE TITLE
semi - dead mode in amazon kingdom by whitestever

### ISSUE THREAD

**Issue by Wqrld** [Avicus/Issues#1027]
i Wereld2003 just found a bug in avicus where its possible to become a semi dead person in the map amazon kingdom,  u can hit people and break and shoot but people cant see and so can kill you, this could be a random ticklag thing but it could also be  related to me going in a boat and sinking to t
he ground and diening, after thati died 

11-11-2016
17:15 amsterdam time 
jelicious (staff) was on 

if you need more info please reply with what you guys need

(a reward would be loved :))

**Comment by AustinLMayes** [comment]
Cannot reproduce
