### ISSUE TITLE
Really weird unexplainable glitch 

### ISSUE THREAD

**Issue by Cryomancies** [Avicus/Issues#1030]
Alright so pretty much in the first video I somehow got killed while I was dead.
First I died, then The "punch to respawn" screen came up, and my health also showed, and then I got hit and I died. This escalated into some trippy LSD experience

https://www.youtube.com/watch?v=TSVeo1tg3Jc&feature=youtu.be

In the second part the next game started, and I was in the void, as if I was stuck between the two maps.
I alerted the mods and we tried to figure out what was going on but no-one knew.
I couldn't move, but I could eat and shoot arrows. people also were able to see me. 
I did /leave and /join but nothing changed. I fixed it by just relogging MC.

https://www.youtube.com/watch?v=FZJzowctmcc&feature=youtu.be

**Comment by OldManTigerMask** [comment]
This is a local issue (I am pretty sure) and is unable to be fixed by the devs (I still think)
