### ISSUE TITLE
Reports are visible to non mod players.

### ISSUE THREAD

**Issue by johannestheigen** [Avicus/Issues#1031]
So I looked at this <a href="https://avicus.net/TylerdotMichael">profile</a>. And when I went to his forum posts I was actually able to see his locked reports. You can do this while being logged of or even logged in. Here are two examples:
![img_0905](https://cloud.githubusercontent.com/assets/13437351/20302947/735f95c6-ab29-11e6-93fb-091283388a61.PNG)
![img_0906](https://cloud.githubusercontent.com/assets/13437351/20302966/81ff8712-ab29-11e6-8234-7f21a6ccdb8a.PNG)

Please fix this bug.

**Comment by flohlen** [comment]
dube #1024
