### ISSUE TITLE
Wool room

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#1035]
I just played a game on Arizona and a player could enter the wool room although he is from the other team
And it seems like only that player could

**Comment by AustinLMayes** [comment]
@Avicus/map-developers

**Comment by joelmce** [comment]
I can reproduce, however I do not believe this is something map-related but rather developmental. @AustinLMayes  the XML seems OK, however when the region is trying to deny the user from entering, it originally stops them but as soon as they try again they are 'teleported' into the region. 

GIF: https://gyazo.com/6311fa0ed83ceef74487374a258375ec
