### ISSUE TITLE
glitch back to block where you last were, whenyou place a block mistakenly in a non-placeable void gap?

### ISSUE THREAD

**Issue by armoredpotato1** [Avicus/Issues#1041]
not sure if it makes sense, but when you fall off the edge, and catch yourself, but it turns out you may not place any blocks there, you freeze up for a second then go back to the place you were hit off/fell off. No proof but you can see it for yourself on any map. thank you

-armoredpotato

**Comment by AustinLMayes** [comment]
This is an anticheat issue
