### ISSUE TITLE
"Recent Posts" still shows you posts which you're not supposed to see as a non-staff

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1050]
I don't know why it was closed: https://github.com/Avicus/Issues/issues/1024

It's still not fixed. I can see others applications as an example, without even logging in
![screenshot_14](https://cloud.githubusercontent.com/assets/7355350/20642593/42a40a96-b413-11e6-9ec3-4d3cd153da94.png)
At the very bottom of the screenshot you can see the first line of my staff application. I took this screenshot when I was using another browser where I wasn't logged in. This also works for everyone who is logged in!

**Comment by ProfessorUtonium** [comment]
high priority
