### ISSUE TITLE
Hi, I don´t see my stats profile, its a error page or refresh page? 

### ISSUE THREAD

**Issue by CHIPOTLEYT02** [Avicus/Issues#1051]
fix coming soon please

**Comment by thekeenant** [comment]
Username?

**Comment by Aki35** [comment]
@thekeenant

I believe his username is CHIPOTLE_YT

I just tried clicking his profile through the stats page and gor a 404 error.

**Comment by AustinLMayes** [comment]
This will be fixed when you log in again.
