### ISSUE TITLE
Showing wrong number of pages in appeals

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1058]
<a href="https://gyazo.com/552493e80d34dceabc378b9ac205b42e"><img src="https://i.gyazo.com/552493e80d34dceabc378b9ac205b42e.png" alt="https://gyazo.com/552493e80d34dceabc378b9ac205b42e" width="1185"/></a>

**Comment by thekeenant** [comment]
You can't view the others.

**Comment by ghost** [comment]
But still beign a bug
