### ISSUE TITLE
Players can kill frozen players to "free" them

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1062]
When you kill a frozen player (you can hit him or use the bow), he just can respawn and get unfrozen automatically.

**Comment by tylerCain** [comment]
Unless it has changed they just respawn in the same place?

Either way, it should just cancel the damage event

**Comment by Atdit** [comment]
They respawned just normally at the spawn of their team, but now they seem to only get damage from players but they can't be killed.

**Comment by Atdit** [comment]
Update: Sometimes they get unfrozen and sometimes they just get damage but don't die. I don't know why, it seems double buggy

**Comment by kashike** [comment]
Should be fixed with https://github.com/Avicus/Hook/commit/137d3b69439dfa64d10a8480f2944408869f269d and https://github.com/Avicus/Hook/commit/c620beaea668835537e7dbabe5614b74ad17e36a.
