### ISSUE TITLE
New players don't get a profile page and it affects /nh

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1065]
New players can't be found at their profile page https://avicus.net/<Player>

This also affects /nh. If a player who already joined the server, before this bug appeared, changes his name, it doesn't show the new name when you use /nh. However, you still can see the other names the player had before. Example:

AtditC changes his name to AtditD. /nh AtditD will output:

"------- Username History for Diamond | AtditD -------
AtditC (3 years ago)"

instead of

"------- Username History for Diamond | AtditD -------
AtditD (x days ago)
AtditC (3 years ago)"

When you /nh new players who joined a few days ago, it will output:

"------- Username History for NewPlayer123 -------"

and nothing else.

**Comment by AustinLMayes** [comment]
This is fixed now.

Usernames will update when you log in.
