### ISSUE TITLE
You get this message everytime the server needs to restart

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#1077]
Hello, I was playing Avicus and I got this message when the server needed to restart (this also happens when you use a Morph in the Lobby)

> _translation: 'generic.countdown.command.type.restarting.time-plural'_
> _translation 'ui.morph-active'_

![4f19013b2110a41f8540da3b4a6a2ba8](https://cloud.githubusercontent.com/assets/19915020/21469502/1e33b7ea-ca18-11e6-90b8-1bff2b36d445.png)

![3fa53d5a4d26e845c71a77e35f45ba59](https://cloud.githubusercontent.com/assets/19915020/21469503/2214441a-ca18-11e6-94f6-50a0589bb607.png)

**Comment by Atdit** [comment]
![ad4d9949bd33454f8c594459501089d1](https://cloud.githubusercontent.com/assets/7355350/21470398/c0c62506-ca86-11e6-94f2-3f81a8d2c26d.png)


![2f8f42348fd844a987a3adda7fe1212c](https://cloud.githubusercontent.com/assets/7355350/21470388/97e0c358-ca86-11e6-8245-6b16c5d4f89b.png)

When you enable/disable a morph

**Comment by kashike** [comment]
The restarting one has been fixed, awaiting deploy.
