### ISSUE TITLE
Breaking monuments after death

### ISSUE THREAD

**Issue by vladthegreat100** [Avicus/Issues#1079]
When you break the monument, if your close enough to breaking the monument and you die, during the respawn timer you can still continue to break the monument if you don't take your finger off the break button and it will break the monument if you have enough time within that respawn time.

How I know? I did it myself wondering what would happen if I kept my finger on the break button.

Maybe have it so when you die that the player cannot break blocks during that respawn timer gap?

**Comment by Atdit** [comment]
Comment: Same for when you're frozen, you still can break the monument, _if it hasn't been fixed yet_, it just takes longer because you're "flying".

**Comment by Spartemex** [comment]
I think this is similar to my issue about using bows after death
