### ISSUE TITLE
Punishment tab is messed up if the reason of the punishment it's too long (Profiles)

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#1084]
Title explains everything. Some examples: 

![a4ce1ecce793bb069ded0bf5efd5f80a](https://cloud.githubusercontent.com/assets/19915020/21570573/d4d8b694-ce8c-11e6-8ce1-1e41ee59db6c.png)
![06560f0ff2a9aff182b43fa0ff6904dd](https://cloud.githubusercontent.com/assets/19915020/21570566/be562eb0-ce8c-11e6-86f7-f7465498fc88.png)

**Comment by smitdalt** [comment]
Fixed.
