### ISSUE TITLE
/r after chat partner disconnects has a buggy text output

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1085]
Example:

Player1: /msg AtditC hi
**Player disconnects**
AtditC: /r hi
AtditC is not online.

![screenshot_1](https://cloud.githubusercontent.com/assets/7355350/21575749/b7e114ba-cf17-11e6-946e-8e5569778e95.png)

**Comment by benrobson** [comment]
This has been happening way more often as of recent.
