### ISSUE TITLE
Scrims offline

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1089]
I reserved a scrim and I couldn't join it because when I did /server scrim01 it stated that it's offline.

**Comment by ghost** [comment]
Just realise there are no scrim servers even listed - https://avicus.net/play

I don't know if this was intended or not. Would be nice if this got fixed.

**Comment by AustinLMayes** [comment]
The servers start when they are reserved.

Some backend changed weren't deployed correctly for this to work, fixed now.
