### ISSUE TITLE
You can still shoot people after you die

### ISSUE THREAD

**Issue by Spartemex** [Avicus/Issues#1090]
When you die you stay in the same spot until you are able to respawn. Sometimes (it has happened to me and my friend) if you have your bow in the right position when you die your bow will not be taken away, and you can still shoot people when you're in that "dead" state where no one can shoot/see you.

**Comment by ghost** [comment]
Yep, I was gonna report it after I discovered it.

**Comment by flohlen** [comment]
Evidence by Rivzz: https://www.youtube.com/watch?v=VJh5OXtZ4qE
(https://avicus.net/forums/discussions/cf18f0d8b)
