### ISSUE TITLE
Badge Colours

### ISSUE THREAD

**Issue by Rockyyyyyy** [Avicus/Issues#1091]
Up until the Atlas update I had a blue flower badge, when the update came along all badge went grey, I wasn't happy but I got over it. Now when I find out you can get colour but you have to buy the whole badge over again annoyed me because I bought the badge and the colour separately and now I only have a grey badge while other people who just buy the same badge as me get a coloured badge, yet I'm still there trying to save up 30 thousand credits trying to get a coloured badge. 

Sorry for the rant I know its not any of your faults but I'm just asking to see if I could get a blue badge 

Thanks for your time,   Rockyyyyy

**Comment by AustinLMayes** [comment]
This is not the proper place for this. 

If you have sufficient proof of having the badge you can email sales@avicus.net

**Comment by Rockyyyyyy** [comment]
I got given a link to Git Hub by a Dev and he told me to put the issue
there
