### ISSUE TITLE
Add welcome message to the lobby

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#1093]
Something like

![](https://i.gyazo.com/597bbdd31972e3dad553fe978f73f877.png)

In bukkit:

`&7&l---------- &aWelcome to the &6Avicus &b&lNetwork &7&l----------
&3You are in the &bLobby&3. To select a gamemode, please
right-click the &6server menu &3located in your hotbar.
&7&l-------------------------------------`

Allowed to post by a dev

**Comment by AustinLMayes** [comment]
Added in https://github.com/AustinLMayes/Atrio/commit/daa51b4a0e9d7f91d8ee21930254c41dd42caef3
