### ISSUE TITLE
Crates don't give you items

### ISSUE THREAD

**Issue by BreakingBadger** [Avicus/Issues#1097]
Crates are no longer working, yet you can still purchase keys through the perk shop. I wasted ~9000 credits on keys and got nothing out of the crates, except for the first one. I opened the first one, got some new trails, and they ended up in my back up. I bought some more, and they weren't in my backpack, so I thought maybe my backpack ran out of space. So I deleted the duplicate trails, and I _still_ didn't get any new items.

**Comment by Palmidence** [comment]
Email support@avicus.net?

**Comment by AustinLMayes** [comment]
Cannot reproduce
