### ISSUE TITLE
Spectators in scrim servers that have Gamemode 1 can use certain items.

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1098]
If a leader in a scrim server can /gamemode 1 they can drop potions or use eggs and these will harm in-game players.

**Comment by kashike** [comment]
The question is: Why are they going into gamemode 1?

**Comment by ghost** [comment]
Why not?

**Comment by kashike** [comment]
Scrimmage servers are for scrimmaging, not for playing around on.

**Comment by AustinLMayes** [comment]
Edge-case issue.
