### ISSUE TITLE
Ranks disappear while you are playing.

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#1107]
Well, I was playing and typing in chat when suddenly my Map Developer and Moderator rank were gone for a few minutes until I relog, I don't know how to reproduce :/
It happens to Donators too.

![fd397b0a5eba00ebe0537e5ba429e3e7](https://cloud.githubusercontent.com/assets/19915020/21877143/ab79abf2-d84e-11e6-872a-0cea59811389.png)

![3875cdf9648cf343b74bdc7a5e91d023](https://cloud.githubusercontent.com/assets/19915020/21877145/ae530b8e-d84e-11e6-9911-8ae71d1edcc0.png)

**Comment by AustinLMayes** [comment]
Unable to reproduce. Comment if still happening.
