### ISSUE TITLE
You can rate a map which playing by clicking the previous message for rating

### ISSUE THREAD

**Issue by sergivb01** [Avicus/Issues#1108]
When a map ends it appears a message so you can rate the map. http://prntscr.com/duv073

Then the map cycles and it starts (you should not be able to rate the playing map util it ends). If you click the previous message (from the previous map obiously) you are able to rate the playing map.

**Comment by kashike** [comment]
> you should not be able to rate the playing map util it ends

Yes you should. You are intentionally permitted to rate the currently playing map, so long as you are on a team.
