### ISSUE TITLE
Using /s gives an internal error.

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1112]
For example, inputting "/s hello" will give:

An internal error occurred while processing that command.

The same happens with /md.

**Comment by AbusiveUser** [comment]
That command is only for Staff Members (Moderators). What's your IGN?

**Comment by master00ofdsiware** [comment]
If I did not have access to the command, it would have said "You do not have permission." (which is what /d and /a return, as I cannot use those commands).
