### ISSUE TITLE
Scrim servers not working

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1114]
This is me 3rd-4th time making a report about scrim servers in the last month :/

Well this time the scrim server did open but none of us could join it because it said "You are not allowed to participate in this event"

We tried for around 15 minutes and then asked a Mod to join, of course the mod could join and then he spoke to the developer 'Kashike'

Kashike went on and turned off scrim01, We assumed he was restarting scrim01/fixing it but if that was the case it did not work as we ended up with no scrim.

**Comment by AustinLMayes** [comment]
They work.
