### ISSUE TITLE
Help with ts

### ISSUE THREAD

**Issue by Kojapan** [Avicus/Issues#1116]
I recently donated to the diamond rank. I wanted to reregister in TS to get the rank's perks, but found that I could not reregister. After, I had to reinstall OS so I lost all my information. I reinstalled TS, only to find that I can't register at all now... I contacted some moderators who did their best but could not come up with a solution. Please help! 

Koja

**Comment by kashike** [comment]
@AustinLMayes

**Comment by AustinLMayes** [comment]
Try again
