### ISSUE TITLE
General destroy icon shows reduced playercount

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1120]
If you right click the server selector enchanted book, the Destroy item shows only the playercount of Destroy1, and does not add the Destroy2 player count.

So, even though Destroy1 has 14 players while Destroy2 has 37 players right now, the general Destroy icon shows only 14, instead of 51 as it should.

**Comment by master00ofdsiware** [comment]
https://www.youtube.com/watch?v=JBFcC3uoPro

**Comment by kashike** [comment]
ALM said this wasn't a bug, blame him. :smile_cat:

**Comment by AustinLMayes** [comment]
This was fixed a while ago.
