### ISSUE TITLE
Destroy2 doesn't go down when there is only one server

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1133]
We had a situation just now where Destroy1 was the only server playing anything, but for some reason Destroy2 was up. This led to a situation where, when Destroy1 restarted, everybody was taken to Destroy2 (which makes them play the same rotation, which isn't great).

**Comment by AustinLMayes** [comment]
Dynamic server virtualization is based on category, not on the whole network, Destroy1 likely met the standards required for Destroy2 to start.
