### ISSUE TITLE
CTP maps

### ISSUE THREAD

**Issue by imryaan** [Avicus/Issues#1137]
In ctp maps(e.g CityScape) you shouldn't have to stand on the point to gain points as this makes the game more boring. 
It would be better if when you captured the point you don't have to keep standing on it to gain points.

**Comment by AustinLMayes** [comment]
Hills now have a `earn-points` attribute that allows you to configure when teams earn points from hills default: `standing-on`
OPTIONS:
`standing-on` - Only earn points when on the hill
`standing-off` - Only earn points when off the hill and owner
`always` - Always earn when owner
