### ISSUE TITLE
Too many icons in the website toolbar / header

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1142]
I realize this is only an issue for staff members who have access to the Admin panel, but when the alert icon is visible, and so is the livestreaming icon, everything doesn't all quite fit in that toolbar / header, resulting in this. https://i.gyazo.com/0f49483a503d63b8b65639b3da1fba1b.png

**Comment by andrgorr** [comment]
Perhaps we should center logo and have icons forcibly under it, centered as well? Opinions @Avicus/Developers

**Comment by CrazyisCreeps** [comment]
Maybe shorten the `Administration` panel to just `Admin`?

**Comment by AustinLMayes** [comment]
Fixed in upcoming web update
