### ISSUE TITLE
Regions Issue On Senex 1

### ISSUE THREAD

**Issue by alexanderjoe** [Avicus/Issues#1145]
Whenever you build out past a certain point you get this, you are still allowed to build through it though. And it is not like I was bridging out across the map, it was just toward the enemy base over solid ground.

![](https://i.gyazo.com/40bfcfdf56aa599b9a20d01e306dee7f.jpg)

**Comment by AbusiveUser** [comment]
The problem could not be replicated (maybe it's already fixed?). I'll be closing this issue but if you still have problems feel free to open this again :)
