### ISSUE TITLE
Player counts are not remotely accurate to what they should be

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#1155]
![](https://i.gyazo.com/4d3279b2500cc38b704cd512aa9af326.png)

It says 38 players are playing.

![](https://i.gyazo.com/ea7cbd4d1dd6a2f6ec7f7930fda3cb79.png)

It says there are 2 people spectating, but there's only one player on and it's not even enough to start the match.

![](https://gyazo.com/c3f1831fe6af90932db2fdd0e61f03b7.png)

There are only 2 people in the lobby. Possibly that the server thinks people in the lobby are spectators and it dupes?

Also, the play page has had reports of duplicated players frequently. This gives the false presumption that you can play on the server, especially if it says there are players on, but there's like, none.

**Comment by AustinLMayes** [comment]
Fixed on restart.
