### ISSUE TITLE
Junior Moderators can't edit threads of other users

### ISSUE THREAD

**Issue by flohlen** [Avicus/Issues#1156]
Right now the rank is pretty much pointless in terms of moderation on the forums.
Junior mods only have access to the two new staff subforums and the report section.

Since they are in their trial stage, they should learn how to edit, archive and lock threads and posts. 
So they know what to do if they successfully completed their trial.

**Comment by AustinLMayes** [comment]
This is intentional. 

In future, please take any permissions suggestions to a senior staff member.
