### ISSUE TITLE
Stats and ranks disappearing from profiles

### ISSUE THREAD

**Issue by BassamR** [Avicus/Issues#1164]
This happened a couple of times before, a player's stats and ranks and skin would simply disappear for absolutely no reason. Example:

![screenshot 156](https://cloud.githubusercontent.com/assets/18619720/24576416/abc0b15c-16cc-11e7-9a42-ba5af178747f.png)

**Comment by AustinLMayes** [comment]
Fixed. Bad people are doing bad things it seems
