### ISSUE TITLE
Right clicking the floating invisible blocks that hold up signs in maps like quintus removes them

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1169]
<img src="https://cdn.discordapp.com/attachments/274688639378915328/298211673460834304/unknown.png" />

**Comment by Palmidence** [comment]
Can be solved by using //fast and just pasting the sign itself.

**Comment by Prodigy4532** [comment]
![2017-09-25_08 52 26](https://user-images.githubusercontent.com/8517389/30811896-1197530e-a1cf-11e7-9508-e11d594f2436.png)
