### ISSUE TITLE
Staff page does not display rows correctly.

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1170]
No idea if this is already a known/reported issue (I didn't see any issues open about this here). But basically, after the latest update to the staff page, the staff page can only fit 9 icons (staff) per row, instead of the 10 it used to be. This ends up any staff category that has more than 9 members to plop that 10th member on a new row.

Just thinking out-loud here, but if you edited the HTML, and maybe just put 9 staff per row and centered it, it might not look so bad and would fix the formatting issue.

**Comment by CrazyisCreeps** [comment]
I think this has something to do with my own display sizes, since some people don't get this (and if I zoom out a bit it all goes to normal). Because of this, I figured it might help if I take a screenshot of what it looks like on my end.
https://i.gyazo.com/0853d201f24eb41701dcb3fa235a31e8.png

**Comment by benrobson** [comment]
It's your browser, it's too small.

**Comment by tnws** [comment]
This is an issue with sizing. 

[Gfycat](https://gfycat.com/gifs/detail/GregariousAmazingAmurminnow)

**Comment by smitdalt** [comment]
Fixed. We did not break the website while fixing this.
