### ISSUE TITLE
Clear up registration message

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1172]
Clear up how to register. https://avicus.net/users/register
Right now it's says `Connect to 3298.register.avic.us to complete the verification process`. A lot of people seem to get confused by what this means, and try to go to https://3298.register.avic.us, which redirects them to the home screen. Maybe change the wording to say something about connecting using Minecraft. So maybe `Connect to this IP in Minecraft, 3298.register.avic.us to complete the verification process`

**Comment by Wqrld** [comment]
Connect to 3298.register.avic.us using MInecraft to complete the verification process

**Comment by CrazyisCreeps** [comment]
Yea, that's probably better

**Comment by tnws** [comment]
Good morning, or afternoon or night or whatever time it is for you!

Apologies for this taking a while for such an easy task. I've [fixed this now](https://avicus.net/development), and the wording is now "Open Minecraft and connect to", which is kind of similar to the wording that's on our [play](https://avicus.net/play) page. 

Thanks for the issue report!
