### ISSUE TITLE
"You have unread alerts" shows up when you don't have unread alerts. (on gameserver)

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1178]
![2a07b0051f3649e0a0ea9185a785e2ec](https://cloud.githubusercontent.com/assets/7355350/25027338/3aa8b250-20ac-11e7-94bc-4b6f812c083a.png)

It shows up, but I don't have any unread alerts. This always happens when you join the server

**Comment by AustinLMayes** [comment]
Fixed
