### ISSUE TITLE
KoTH doesn't end when points max is reached Unless all points are captured by winning team

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1179]
Look at Draxel and Heat.

When a team gets the max amount of points they ONLY win if they have ALL the points captured.

It should be, when a team reaches the score limit they win, regardless of other factors.

**Comment by Palmidence** [comment]
<scores limit="200">
            <score team="yellow"/>
            <score team="red"/>
        </scores>

Add that to Heat. It'll end when they get 200 points. CityScape provides a working template.
**EDIT:** Looks like its nested in the wrong place. Nest it between `objectives` and `any`

If it doesn't work, let me know

**Comment by master00ofdsiware** [comment]
Cityscape does not provide a working template. If you go capture mid but the other team still has their point (that is to say, you have 2 out of 3 points captured) the game does not end if you get the points limit.

**Comment by master00ofdsiware** [comment]
This isn't a programming issue because it's possible to fix via XML changes, but the XML is a bit confusing for this certain feature. Maybe the docs could be expanded?

**Comment by master00ofdsiware** [comment]
This isn't an actual issue.
