### ISSUE TITLE
Something gone weird in /staff

### ISSUE THREAD

**Issue by benrobson** [Avicus/Issues#1184]
Here you go:
![image](https://cloud.githubusercontent.com/assets/15405528/25286049/b341e70a-26ff-11e7-9631-8d21cbe6c479.png)

**Comment by kashike** [comment]
Known, fix in progress.

**Comment by benrobson** [comment]
![image](https://user-images.githubusercontent.com/15405528/28389939-73fc5a28-6d1b-11e7-9ed2-0e37fca0baff.png)

**Comment by benrobson** [comment]
Reopening because it's not fixed

**Comment by benrobson** [comment]
https://i.gyazo.com/8f9f3f95581cac885806b8082e2e743c.png
Still not fixed
