### ISSUE TITLE
Crossfire TE: score boxes broken

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1187]
There is no region to prevent teams from entering their own score box. When they do, they get points for their team, and spawn at the other team's spawn.

Also, if a player gets killed within the score box, they end up glitching out and getting a ton of points (I assume it has to do with them being dead, but still technically in the score box). In both situations where it occurred, the player received approx 500 points from the score box
This bug could be caused by something else, but both times it happened players in chat talked about how it occurs when a player dies.

**Comment by AustinLMayes** [comment]
Both issues fixed
