### ISSUE TITLE
Trying to punish via Website gives a 500 error.

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#1193]
The error says "you may not issue punishments as this user".
This especially affects the Officials who need to tournament-ban somebody.
Screenshot from Tazz: http://image.prntscr.com/image/a89541ffc97546e6a8555f6197307c66.png

**Comment by thekeenant** [comment]
Could you try again and post the exception ID, thanks!

**Comment by master00ofdsiware** [comment]
@thekeenant 

`WIFERJXX` is the exception ID that was shown when I tried using the feature just now; as shown in this screenshot: https://i.snag.gy/iTRrtB.jpg
