### ISSUE TITLE
Greenwoods (KoTH) did not end once score hit the score limit of 200

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1196]
I had reported a map bug earlier on the Map Request forum topic, but I feel like this might be a better place to put this bug (?). Anyways, while playing the KoTH map Greenwoods, Red team reached the score limit of 200 and the map did not end. I was forced to /end it.

![2017-05-19_13 24 15](https://cloud.githubusercontent.com/assets/7937351/26259593/af891798-3c97-11e7-91eb-cd143939e9f9.png)

**Comment by Prodigy4532** [comment]
Fixed!
