### ISSUE TITLE
You cannot filter by escalated appeals

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1200]
On the appeals page, when you hit the "Only Escalated" button, nothing ever appears - it always says that there are no escalated appeals to do with. However, it'll say that even if there is an open, escalated appeal.

As you can see in this image, there are currently at least 2 open, escalated appeals. https://i.imgur.com/L23Z3r3.png
https://avicus.net/appeals?escalated=1 says "No appeals to display".

It would be nice to be able to filter by escalated appeals.

**Comment by AbusiveUser** [comment]
Bump

**Comment by AustinLMayes** [comment]
Please do not bump issues

**Comment by smitdalt** [comment]
Fixed
