### ISSUE TITLE
Enderpearl bug

### ISSUE THREAD

**Issue by JumbOtsutsuki** [Avicus/Issues#1215]
http://imgur.com/a/Glajg in this photo u can see that I threw an enderpearl, but I missed it and I felt into the void, and that was my death msg.

**Comment by Palmidence** [comment]
I mean, technically speaking with the tracker, I'd say this message is fine. We've been using the same tracker for some time and it's never been an issue, and we had Broken World in rots about 3 years ago.

**Comment by AustinLMayes** [comment]
We actually changed trackers when we switched to Atlas @Palmidence

**Comment by benrobson** [comment]
I think this message is fine, probably close this.
