### ISSUE TITLE
TNT does not destroy a monument, if it has moved from its original location.

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1216]
This clip shows the issue: https://youtu.be/uIZeSp7C6H8

**Comment by ProfessorUtonium** [comment]
I would like to add on that this affects Cannons as well on maps such as Nevran Remastered where TNT being shot by a cannon does not destroy the monument (Even though destroyable is marked as true in the Map's XML)

**Comment by ProfessorUtonium** [comment]
Fixed with the latest update
