### ISSUE TITLE
Walls don't drop

### ISSUE THREAD

**Issue by Ciaan** [Avicus/Issues#1220]
This may be an issue on only one map but it seems that the walls do not drop when the timer runs out on the Walls server. Thought I'd bring it up as we'd probably want that fixed ASAP as players are often moved to the walls server while other servers restart.

**Comment by ProfessorUtonium** [comment]
WildWest is the only map having this issue 

I've already commited many updates to this map. Either the XML isn't updating in the rotation or I keep messing up. I removed the map from the rotation yet it's still there

**Comment by AbusiveUser** [comment]
seems to be fixed.
