### ISSUE TITLE
Conflicting names on new Rendezvous map

### ISSUE THREAD

**Issue by Nebuluar** [Avicus/Issues#1222]
![2017-06-26_16 06 00](https://user-images.githubusercontent.com/29688964/27526607-6200a48a-5a8a-11e7-90d4-8b8cf29c7585.png)
In the rotation it's called 'Rendezvous Redux' but on the map it's called 'Rendezvous Remix'

**Comment by benrobson** [comment]
It's meant to be redux but it seems the maps signs are incorrect, if I'm correct :P

**Comment by AbusiveUser** [comment]
Should be fixed.
