### ISSUE TITLE
Enchantments are not displaying correctly on maps.

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#1224]
I got a request by lil ryan about adding enchantments on Zahiw, but when I was checking the XML I saw there are enchantments but they're not displaying correctly.
I don't know if the XML is incorrect (which I don't think that's the issue).

Here is the XML:
https://maps.avicus.net/atlas/Competitive/Practice/Zihaw/map.xml

**Comment by master00ofdsiware** [comment]
Not a bug; update the spec to 1.0.4 and it should be fixed.

**Comment by AbusiveUser** [comment]
Nothing happened, I changed it to spec 1.04 and nothing happened.

**Comment by AbusiveUser** [comment]
Should be fixed.
