### ISSUE TITLE
Map developers cannot use gamemode or worldedit on the development server

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1230]
This isn't something new, but nobody reported it before.

**Comment by Prodigy4532** [comment]
Any update?

**Comment by thekeenant** [comment]
Give it a shot now?

**Comment by Prodigy4532** [comment]
The server need to be restarted i think because the permissions are the same and i cannot use gm1 and world edit.

**Comment by Prodigy4532** [comment]
Now you can use world edit but change your gamemode no.
![screenshot_1](https://user-images.githubusercontent.com/8517389/31266611-36b70d8c-aa3a-11e7-9714-1cea1ad0893f.png)
