### ISSUE TITLE
Profile leads to 404 error

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1233]
This guy's profile leads to a 404 error. If there's anyway to fix it, I'm sure he'd appreciate it.

**Comment by thekeenant** [comment]
Which guy?

**Comment by CrazyisCreeps** [comment]
Oh lol whoops I forgot to link his profile. Here you go - https://avicus.net/Rhetic

**Comment by CCi2** [comment]
My GitHub Gists profile also gives a 404 error now.
