### ISSUE TITLE
'My Replies' Extra Notification/Invisible threads glitch?

### ISSUE THREAD

**Issue by TridentSPQR** [Avicus/Issues#124]
So, in my replies, it says I have 18 unread, yet it only shows 8, and I have scanned through the other pages of 'My Replies'
Glitch? Bug? Stupid Computer? Invisible thread?
Image: http://i.imgur.com/TZeKI9I.jpg

**Comment by IvyCode** [comment]
This would take a lot of work since it deals with archived revisions of posts. Mark All Read is fine.
