### ISSUE TITLE
Tutorial prefix is gray but the rest of the tutorials are white

### ISSUE THREAD

**Issue by ProfessorUtonium** [Avicus/Issues#1252]
the white blends in with the chat

please change the tutorial color to match the prefix color of gray!

**Comment by AbusiveUser** [comment]
would be nice if you can give us details about this issue or provide an example.

**Comment by Prodigy4532** [comment]
Can you please give me some screenshots? Thanks.

**Comment by Prodigy4532** [comment]
Lack of details.
