### ISSUE TITLE
WIld West is still in rotations

### ISSUE THREAD

**Issue by ProfessorUtonium** [Avicus/Issues#1257]
it's broken (walls don't fall)
fix it or remove it

thanks

title

**Comment by master00ofdsiware** [comment]
https://github.com/Avicus/Rotations/commit/ffae8d9c9425eed776fde33bc6c3b76706b059ad

This is a server issue; the map was removed from the file twenty days ago.

**Comment by ProfessorUtonium** [comment]
then fix the map

problem solved!

**Comment by AustinLMayes** [comment]
Yea, the map should be fixed regardless

**Comment by benrobson** [comment]
The map is fixed as it says here [https://avicus.net/forums/discussions/3a4a7c35c?reply=377342]
Requesting Close

**Comment by master00ofdsiware** [comment]
I'll make a separate issue about servers not pulling new rotation files
