### ISSUE TITLE
GD3: you can't edit wool room lanes (higher lanes)

### ISSUE THREAD

**Issue by ProfessorUtonium** [Avicus/Issues#1259]
http://imgur.com/a/ZiugQ
- the higher lanes (not the flat one)

title

**Comment by AbusiveUser** [comment]
Mmm? the second picture is not from GD3

**Comment by ProfessorUtonium** [comment]
ignore
it
please

**Comment by Prodigy4532** [comment]
Fixed on https://github.com/Avicus/Maps/commit/fbbfee64aae04d6da238ed8e8e09136b91947026
