### ISSUE TITLE
Flowing water dynamically extends void regions.

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#1268]
Hello,

I am unsure of whether or not this behavior is intended. I personally believe that it is quite odd, and thus would like to report it.

When water flows from a region where building is allowed into a region that is considered by the plugin as "void", the plugin starts treating the former void, as an area that is no longer considered to be void. This can be easily abused by players who can simply use water to build infinitely in no-build regions.

However, I would like to take this opportunity to explain what I believe should be changed. Judging from the behavior described above, it appears that the plugin changes the void region based on the current state of the map. I personally believe that it would be better if instead of doing this, the plugin maps the void only _before the beginning_ of the match. 

This would solve the aforementioned issue, and would also allow for easier void region definitions using executors. One could have a certain type of block, such as stained glass, at the void, and then have it removed with executors but the void region would stay.

Thank you.

**Comment by master00ofdsiware** [comment]
I did not mention it originally, but this issue is most likely also applicable to lava.

**Comment by AustinLMayes** [comment]
void regions and checks have an `ignored-blocks` attribute which is acts the same as it does for hills
you need to add `water` and `stationary water`
please update the docs
