### ISSUE TITLE
TNT cannons blow up upon use

### ISSUE THREAD

**Issue by CrazyisCreeps** [Avicus/Issues#1269]
I've been noticed for a few weeks now, that any cannons that use redstone tend to blow up when you fire them. I'm not sure what's causing this, however I don't remember having this issue with cannons before the update that fixed TNT not being able to deal damage to monuments (#1216, #1106). 

Another thing I noticed while messing around with cannons to see record this video - when setting off TNT with redstone, some TNT seems to go off at a slightly different tick than other TNT set off at the same time. You can see it flashing at a slightly different rate. I'm thinking this could have something to do with why the cannons blow up (but I don't really think it's the only reason - having TNT go off at two separate times in a cannon doesn't always make it blow up, that generally matters on the design of the cannon). 

I haven't been able to cause any cannons to blow up that do not use redstone, such as a normal whiskey with just buttons, no redstone.

https://www.youtube.com/watch?v=5bBIOXI_R_I

**Comment by AustinLMayes** [comment]
Pushed a patch for this a bit ago, let me know if it helps (servers need to restart first)

**Comment by benrobson** [comment]
Close?

**Comment by CrazyisCreeps** [comment]
Still happens
