### ISSUE TITLE
team page

### ISSUE THREAD

**Issue by devrevs** [Avicus/Issues#1272]
whenever I try and edit my teams about page I get 505 error
An error was encountered during the request. 
Exception ID: DXHJICZJ

**Comment by benrobson** [comment]
@devrevs what exactly are you trying to do?

**Comment by shadowolfyt** [comment]
@AustinLMayes I know you're active here, close this please.

**Comment by tnws** [comment]
I can't reproduce this locally or on the server, going to close this
