### ISSUE TITLE
Ref and/or Streamer cannot appear on staff page

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#1273]
I checked the box that says "appear on staff page"  and when I went back to the staff page, I couldn't load it and got a 500 error.

**Comment by ghost** [comment]
Uhhhh, works for me... 
![image](https://user-images.githubusercontent.com/13290941/28808930-be3c4dc4-7634-11e7-8509-e3fd15e400fc.png)

**Comment by benrobson** [comment]
If they are meant to show on the staff page during tourney times why aren't they there?

![image](https://user-images.githubusercontent.com/15405528/28809076-3257e71a-76c4-11e7-865f-d7d269d63c8f.png)

**Comment by CrazyisCreeps** [comment]
I assume because when Poker tried to enable it, it wouldn't show up and glitched out

**Comment by ghost** [comment]
I'll enable.
Update: Now showing...
Update: NVM It still gives 500 error
Update: Confirmed, any changes to make any rank appear on staff page will give error

**Comment by AustinLMayes** [comment]
Badge/html color cannot be `none`
