### ISSUE TITLE
Map-Vote-Selector is broke

### ISSUE THREAD

**Issue by BreakingBadger** [Avicus/Issues#1283]
Just spent 15,000 credits on one of those, and it didn't work. All the choices were invalid, and people didn't even know how to vote for a map. Fix the glitch (and maybe give me a refund? ;]) and add a message that notifies the users how to vote. The piece of paper only showed I believe one thing, and when clicked, it just said it was invalid.

**Comment by AustinLMayes** [comment]
Unable to reproduce. Comment if still happening.
