### ISSUE TITLE
Automatic Tutorials

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#1302]
Should not be forced automatically or even be dependent on XP. Plenty of people have played before and know how to play, and would rather play. Don't make them automatic because parts of it are unskippable and inconvenient to have to type commands every single time, and they're a huge deterrent for someone who wants to play.

Also, the command to disable automatic tutorials does not work whatsoever for me. Make it dependent on play time.

**Comment by AustinLMayes** [comment]
This repository is for issues, not suggestions. Please use the forums.

**Comment by Palmidence** [comment]
Also, the command to disable automatic tutorials does not work whatsoever for me. Make it dependent on play time.
