### ISSUE TITLE
Weekly Leaderboard doesn't update after 7 days have been over

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1319]
![image](https://user-images.githubusercontent.com/7355350/30392124-2133ce3a-98bc-11e7-9f3a-3f6211407368.png)

It's exactly the same as it used to be over a week ago, when I checked. Why doesn't it update? It should say that I played about 1 day or more in weekly and the same in monthly

**Comment by Atdit** [comment]
![image](https://user-images.githubusercontent.com/7355350/30786651-96547f0a-a179-11e7-961c-72228efb3858.png)
still the same ._.

**Comment by Atdit** [comment]
![image](https://user-images.githubusercontent.com/7355350/31101649-01df729c-a7cf-11e7-8152-64df48403b88.png)
Still the same

**Comment by thekeenant** [comment]
😕 But why?

Hm

**Comment by Atdit** [comment]
Still doesn't update :(

**Comment by smitdalt** [comment]
This is fixed.
