### ISSUE TITLE
Walls Tutorials

### ISSUE THREAD

**Issue by Acceptancq** [Avicus/Issues#1321]
On Avicus the tutorial book is normally in slot 4, on Walls it's replace by the kits. There is no tutorial book

**Comment by AustinLMayes** [comment]
Walls maps don't have tutorials
@Avicus/map-developers

**Comment by master00ofdsiware** [comment]
This will be fixed within a few days; apologies for the delay.

**Comment by Prodigy4532** [comment]
Fixed on https://github.com/Avicus/Maps/commit/603f9f1693567ea2b55d4d2145f694f4f3663708
