### ISSUE TITLE
Sahandus 1.0.0 Text Bug

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1324]
![2017-09-17_15 37 47](https://user-images.githubusercontent.com/7355350/30521707-6d57806c-9bc4-11e7-8c48-9c96575ab743.png)

I can enter the wool area since it's in the enemy team, but when I place a block there it says "You may not enter your own wool room!" which is weird.

**Comment by AustinLMayes** [comment]
@Avicus/map-developers

**Comment by AbusiveUser** [comment]
Fixed.
