### ISSUE TITLE
Credit Blaster Gadget broken 

### ISSUE THREAD

**Issue by JapaneseSquid** [Avicus/Issues#1330]
I tried using the gadget, but whenever I buy one it appears in my backpack as "0/1 usages left" and it doesn't work at all when you left or right click. Spyted tried doing the same thing as well, note that we tried on both lobbies just in case.

**Comment by Prodigy4532** [comment]
Credit Blaster is on Development right no, devs are orking so hard to get this working, be patient c:

**Comment by AustinLMayes** [comment]
Fixed on restart
