### ISSUE TITLE
Annoying thing with appeals

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1334]
Firstly, in appeals if you put a link and then put a full stop or comma after it, it will add that to the link. The proof isn't great but its pretty much showing what happens when I click on a link that has a comma on the end. It sends me to an error page. Heres the proof:
https://gyazo.com/8b7706846143b5a0ac98ec8a05767bfe

Secondly (just a very very very small issue and it doesn't even matter if it doesn't get fixed),
When you type a word and then put a colon, it will make it a hyperlink. If they click the hyperlink which would be lets say evidence: it would just take them to a new tab with the address evidence:
https://gyazo.com/639bb201ec48cc805797d9089284bee7

**Comment by smitdalt** [comment]
Colons no longer create a hyperlink. For now avoid using punctuation after a link on the appeals pages. I'll come back to this, but closing for now.
