### ISSUE TITLE
Dropdown box on website doesn't work on some devices.

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#1337]
After the "fix", some mobile devices started to work, but mine still doesn't and Dev_Rev's doesn't work on his school laptop.

My phone: LG Optimus L90

**Comment by Aki35** [comment]
School computer is a google chrome book.

**Comment by Prodigy4532** [comment]
Can you please provide some screenshots please? Thanks c:

**Comment by Aki35** [comment]
Screenshots won't help anything.

**Comment by Aki35** [comment]
Plus the developers know what I'm talking about, I just put it here for organizational purposes.

**Comment by tnws** [comment]
[Seems to work for me?](https://youtu.be/28BWNiypXQk)

**Comment by Aki35** [comment]
@tnws Yeah, but I said some devices it doesn't work.

https://youtu.be/0MKSzmOkt38

**Comment by tnws** [comment]
Seems to be an issue with how Bootstrap handles dropdowns on devices with different viewpoints. My only issue is that I don't have any devices where this has been an issue for me, but I'll definitely try to get a fix for you within hopefully a week or so.

**Comment by AustinLMayes** [comment]
Fixed in upcoming web update
