### ISSUE TITLE
Sector Six 1.1.0 A little building mistake

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1340]
![2017-10-04_13 42 40](https://user-images.githubusercontent.com/7355350/31173988-15af3aaa-a90a-11e7-95b2-0e3841d32821.png)
![2017-10-04_13 42 51](https://user-images.githubusercontent.com/7355350/31173989-17afc27a-a90a-11e7-8633-e8f27d274e6e.png)

On the orange side, there is a slab on the first tower, but on the cyan side, there isn't one.

**Comment by Prodigy4532** [comment]
Fixed on https://github.com/Avicus/Maps/commit/95a18749969515be040a4ae86cf517b47840a62e
