### ISSUE TITLE
Atlas doesn't work sometimes.

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#1344]
We're currently having issues with some maps after updating them. One example of this is the map "Fractal Descent", the map is currently broken because you can damage your own objectives, regions aren't working correctly and monuments can not be completed.
After you update the map it works for a few matches but after you restart it, the map is broken again.

The most recent issue about this is "Aquatic Urbex", Distraction tested it out yesterday at night and it worked correctly, but now, it's broken (like I explained before)

![4b29b01fec0ae6343f69dc6d8a826c0d](https://user-images.githubusercontent.com/19915020/31580781-6e2b224e-b11f-11e7-8d6a-32b6b026b087.png)

_Prodigy and Distraction can confirm this information._

**Comment by master00ofdsiware** [comment]
This is reported as happening on spec versions 1.0.4 and 1.0.5, but not 1.0.3

**Comment by pcteddy** [comment]
We reported this ages ago and still hasn't been fixed. Staff have to come on and skip it for us.
