### ISSUE TITLE
2 issues

### ISSUE THREAD

**Issue by sir-crashalot** [Avicus/Issues#1347]
Hello there,

I've just found out that arrow trails aren't working as expected. Whenever I shoot an arrow it just displays a default trail instead of the purchased one. I can't even toggle the settings "ShowArrowTrails" on all servers except Lobby servers. Evidence: https://youtu.be/qDXWeBYUqxM

And the second thing that I found out is that whenever I want to /nh a spectator, I have to write his username on my own instead of using TAB.

**Comment by AustinLMayes** [comment]
1. Servers need to restart for the setting/trails to be deployed. Let me know if they still don't work.

2. You can't TAB to anyone you can't see. If you are in a game OR have spectator view disabled, you cannot TAB to them.

**Comment by sir-crashalot** [comment]
1. Trails now work, but is there a possibility to make it more visible? I feel like you gotta be lucky to see those trails xD

2. Well yeah, I agree with what you said, however it would be kind of useful to let us TAB them whenever we're in-game :)
