### ISSUE TITLE
Chunks around the Halloween lobby aren't pruned

### ISSUE THREAD

**Issue by BassamR** [Avicus/Issues#1349]
Pretty self explanatory really. Players can also (with a bit of parkour) leave the lobby and go on the survival world.

![2017-10-23_10 35 12](https://user-images.githubusercontent.com/18619720/31875207-1ec89fea-b7de-11e7-877b-964c0b2dfb4d.png)

**Comment by AustinLMayes** [comment]
This was actually an Atrio issue
