### ISSUE TITLE
/mute is broken

### ISSUE THREAD

**Issue by BassamR** [Avicus/Issues#1351]
Another self explanatory issue, when using /mute on a player they are still able to use the chat normally.
(the screenshot was a 15 second test mute)

![2017-10-26_12 33 36](https://user-images.githubusercontent.com/18619720/32042814-ecf14b16-ba49-11e7-9705-c728a722c3d2.png)

**Comment by AustinLMayes** [comment]
Let me know if this is still happening.

**Comment by AustinLMayes** [comment]
Fixed
