### ISSUE TITLE
Minecart glitch

### ISSUE THREAD

**Issue by JapaneseSquid** [Avicus/Issues#1356]
https://www.youtube.com/watch?v=tLPe6cKSxak

If you stay in the mine cart deck located at the top of the mountain on MYOB, you can not get out the cart after the game ends. After the next map is cycled, the player is stuck in place in the air about 190 blocks, the same altitude of the mine cart on MYOB. The player can join and even start in the same spot, and is stuck there until they hit the mine cart exit button (Default is Left Shift)

**Comment by master00ofdsiware** [comment]
This isn't map-specific; it's just something that happens with minecarts.

**Comment by pcteddy** [comment]
It happens on all maps with minecarts or if you make a minecart and sit in it
