### ISSUE TITLE
You have unread alerts!

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1357]
Ggives you the unread alerts msg in game when the website doesn't (this is when you join the server). What I mean is that when you read the alerts on the website I don't think the game realizes that you have read them.

**Comment by Riilo** [comment]
This also happens when you connect to destroy or any server

**Comment by AustinLMayes** [comment]
Fixed on restart.

**Comment by Riilo** [comment]
Fixed in the lobby, not on the capture or destroy server.
