### ISSUE TITLE
Using vote keys

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1358]
When you use a vote key and it is like the machine that spins, every item either says rare or extremely rare. Shouldn't some of the items say like Common or something. Not sure if this is intentional or not.

**Comment by AustinLMayes** [comment]
Not every item is rare.

See:
<img width="781" alt="screen shot 2017-11-04 at 12 04 20 am" src="https://user-images.githubusercontent.com/4269021/32402510-c26b4c60-c0f3-11e7-92db-6c46b5f96fb4.png">

**Comment by Riilo** [comment]
I just spun a vote key and every single item as it spun by said 'Rare' and some said 'Extremely Rare'. :/

**Comment by Riilo** [comment]
@AustinLMayes 
^^^

**Comment by Riilo** [comment]
@AustinLMayes ^^^

**Comment by Riilo** [comment]
@AustinLMayes Wake up please ^^^
