### ISSUE TITLE
Map Critic achievement can be cheated

### ISSUE THREAD

**Issue by Atdit** [Avicus/Issues#1359]
![image](https://user-images.githubusercontent.com/7355350/32405471-1f75db4c-c166-11e7-96d8-ad69ec2ef162.png)

This guy probably spammed /rate <1-5> 10 times and upgraded his achievements two times in a row on the same map.

**Comment by pcteddy** [comment]
This is possible and should be reported as well. I have mentioned it to staff but they didn't do anything
