### ISSUE TITLE
Development (for builders and mapdevs)

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1360]
For some reason PvP is turned off and you get a bunch of particles at your feet. 
______
On red alert the blocks don't fall.
______
Builders have no perms to change the cycle time (we can use /cycle but we can't use /cycle 10 or something)
______
When you fall into the void it gives you the msg: "Sorry, you had to be disconnected because of an internal server error"

**Comment by AustinLMayes** [comment]
Please make individual issues for those which still apply.
