### ISSUE TITLE
Mute

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1363]
You can't delete/edit mutes on the punishments.
_____________________
It mutes you permanently unless the infraction is appealed (It mutes you permanently when you temporarily mute yourself)

**Comment by AustinLMayes** [comment]
a) Permissions issue
b) mutes are not permanent, users just need to relog to be unmuted.

**Comment by Riilo** [comment]
Okay, well it still isn't fixed... 
@AustinLMayes

**Comment by Riilo** [comment]
@AustinLMayes ^^
