### ISSUE TITLE
Unintentional/Intentional glitch??? Idk

### ISSUE THREAD

**Issue by Riilo** [Avicus/Issues#1365]
You can't see how long someone is tempbanned for when you type /history. 
https://gyazo.com/eb81e24810ffc0ff9e7c1e505e398504

Instead of showing
____________
 "AIDSquirt >> Temporarily Banned (2 years ago) >> AussieOctopus >> Combat Logging" (2 years ago)
____________
It should say 
__________
"AIDSquirt >> Temporarily Banned (3 days) >> AussieOctopus >> Combat Logging" (2 years ago) like it does in chat.

**Comment by AustinLMayes** [comment]
Intentional

**Comment by Riilo** [comment]
Okay.
