### ISSUE TITLE
Map authors not loading

### ISSUE THREAD

**Issue by sir-crashalot** [Avicus/Issues#1368]
This screenshot was taken on the first map after the server restarted.

http://prntscr.com/h925ul
http://prntscr.com/h926m7

Kind regards,
EncryptedShoesHD!

**Comment by sir-crashalot** [comment]
The map has finished and authors were displayed on the next map. Might be an XML problem.

**Comment by Prodigy4532** [comment]
If the authors were displayed it is not an XML issue.

**Comment by sir-crashalot** [comment]
Check an XML file for Senex 2 map just to make sure it's not an XML issue.

**Comment by AustinLMayes** [comment]
This happens when the authors are not in the database and mojang rate limits our name resolution requests.
