### ISSUE TITLE
Credit Blaster can be used to farm credits

### ISSUE THREAD

**Issue by JapaneseSquid** [Avicus/Issues#1371]
The credit blaster can be used to gain more credits. 
This works because of the fact that people with ranks have a 2.5 multiplier that works upon pick up of the credits.
This means that the 100 credit blaster is generating 250 credits, minus the 115 credits used to purchase the gadget would be 35. Now, 35 isn't a lot, but if credit blasters up to 1000 or 5000 are implemented, you could gain more than 1000 credits. The 5000 blaster would have an estimated gain of 7000 credits. Just a bug I found out when messing around with them today. https://youtu.be/RZzwOnJRZTI

**Comment by AustinLMayes** [comment]
In future, please report game breaking issues directly to @smitdalt
