### ISSUE TITLE
/t broke or someone broke the rules

### ISSUE THREAD

**Issue by Minertedtoad** [Avicus/Issues#1373]
basically egirls4life98 felt like she had reach and i asked  leTea about his opinion and some how in /t she knew what i was talking about!!!

https://imgur.com/nX5mGF4
https://imgur.com/s1saxFk
https://imgur.com/nfYMfeK

**Comment by smitdalt** [comment]
I just tested this in-game and couldn't see the other team's chat. They could have had a friend on your team who told them what you said.
