### ISSUE TITLE
Hyperlink on the Support page takes you to a page I cannot access

### ISSUE THREAD

**Issue by Barsik4** [Avicus/Issues#1374]
Hiya,
I've been doing some looking around on your website and I found that here https://gyazo.com/1e8e7d8bbe57a6ffd2e9630eedcf1673 on this page https://avicus.net/support you can't access the page, initially, the hyperlink sends me to https://avicus.net/forums?topic_id=3 but I can't access it.

Please either fix or remove.

**Comment by smitdalt** [comment]
I changed the link to the updated URL for staff applications. Thank you for your report!
