### ISSUE TITLE
Punishment profile spacing is too small

### ISSUE THREAD

**Issue by Barsik4** [Avicus/Issues#1375]
[![Screenshot from Gyazo](https://gyazo.com/3cb97046fcbdaafba389f802af5e2ade/raw)](https://gyazo.com/3cb97046fcbdaafba389f802af5e2ade)

Screenshot explains it all.

**Comment by smitdalt** [comment]
This is already fixed, it's just not live yet.

**Comment by Barsik4** [comment]
I'd like this reopened because I see another issue, as a logged out user, why is the Actions column there.
That's for the logged in User and staff.

This shouldn't be available to the public/logged out users.

**Comment by smitdalt** [comment]
This is also fixed now.
