### ISSUE TITLE
The 'Archives' Section of the Fourms are showing for logged out users

### ISSUE THREAD

**Issue by Barsik4** [Avicus/Issues#1378]
[![Screenshot from Gyazo](https://gyazo.com/53aa2a841041163324ccfdad16c91329/raw)](https://gyazo.com/53aa2a841041163324ccfdad16c91329)

Basically look at the title ^ 
I've been told that the Archives (Staff Applications) is for Staff use only. It displays as empty to the public.

**Comment by AustinLMayes** [comment]
We show the latest archives forum so people who applied can review their apps.
