### ISSUE TITLE
im banned

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#1384]
big issue

**Comment by smitdalt** [comment]
I can't replicate this issue... Can you provide steps on how to reproduce?

**Comment by steven5703** [comment]
1 log into avicus
2 /ban smitdalt hacked client
3 try and reconnect 
4 you can’t. It says you’re banned

**Comment by Prodigy4532** [comment]
Can you please send screenshots? we need some to fix this.

**Comment by steven5703** [comment]
i think i found a temporary solution:

1. change your ip
2. use mcleaks and get a new account
3. log in and it works!

**Comment by steven5703** [comment]
oh ok the temporary solution isnt necessary anymore i can connect on steven5703 now

**Comment by Prodigy4532** [comment]
Nice, thanks for the report!
