### ISSUE TITLE
CTH, Kit ninja bug

### ISSUE THREAD

**Issue by Shirokamii** [Avicus/Issues#163]
Ninja can take off boots and be inviseble.

**Comment by Aki35** [comment]
Sorry for the bump, but I'm pretty sure that this is still an issue.

**Comment by swivr** [comment]
Aw @pavilion99 thought you added lock slots.

**Comment by tanpara** [comment]
@swivr Unfortunately, the slot locking feature caused a few gameplay issues with duping items. It's still there for use, but people could spawn in more golden apples or potions and such by clicking them.

**Comment by thekeenant** [comment]
Ninja was definitely removed.
