### ISSUE TITLE
[Wish] Make Nexus tools soulbound.

### ISSUE THREAD

**Issue by 1Theodore1** [Avicus/Issues#182]
Including the sword, bow etc.
It's really annoying when you drop a sword in the middle of the fight and you <b>can't</b> pick it up :/

**Comment by ParaSpider** [comment]
Boop! Thanks for the suggestion, meant to do this a while back. https://github.com/Avicus/Maps/commit/d60a29542d7aa33622380741d9e040a678aad61c and https://github.com/Avicus/Maps/commit/c91c648eded3e698dd360f4191287e919d9bc89e solve this.
