### ISSUE TITLE
Minotuar dying

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#215]
If the Minotaur dies, the game keeps going until one more person dies.
![image](https://cloud.githubusercontent.com/assets/6472584/3663679/7890c9ec-11d5-11e4-9150-db04e145dd01.png)
Now I'm not sure if this is supposed to happen, but if it is it's really annoying and people can troll with this.
e.g.: afk mino, someone kills mino with fist, then he/she jumps into lava.

**Comment by IvyCode** [comment]
Arcade is being revised and is no longer relevent.
