### ISSUE TITLE
[Request] Remove / Modify Decay

### ISSUE THREAD

**Issue by NotalAvic** [Avicus/Issues#239]
Whenever I play on decay, there are constant people complaining about  the game-play being slow pased and bad, to be honest I notice that myself.
The map seems to stalemate all the time.
My idea is that because there is only 1 bit to the map, front lines, everyone HAS to go there therefore its all a big bow battle.
Also, it takes a long time  to bridge to the monuments.
My suggestion is that at the frontlines, instead of being 1 straight line, its 3 bits that branch out a small bit in each direction to save people from all being crammed into the 1 line so its impossible to bridge.
Also, make the monuments at the back of the map behind spawn BUT less to bridge.
This is just a suggestion, idk if it would work.
if it doesn't, possible remove.

**Comment by ParaSpider** [comment]
Closing in favor of the fact feature requests are not allowed, I will evaluate Decay with the other mapdevs however but not like this
