### ISSUE TITLE
Weird Damage Glitch

### ISSUE THREAD

**Issue by matic0basle** [Avicus/Issues#258]
Map (if its map related): Diamond Shore
Team: Observer
Description: Flying very high up in the air and falling down will make you take damage. The y is 256+ because beacons disappear.
Video: https://www.youtube.com/watch?v=Sr_oadB75X0

EDIT: I am not able to reproduce the issue on Rendezvous III at y=300 which is above the world limit.

**Comment by IvyCode** [comment]
Never saw this, but it looks like AntiCheat thinking you're speed or fly hacking. Now we have NCP.
