### ISSUE TITLE
Not able to /tp in the walls

### ISSUE THREAD

**Issue by vladthegreat100** [Avicus/Issues#259]
So, ive know this problem for some time but I was always too lazy to report it until now since I never really enjoyed walls until now, so I'm not sure if its been taken out because of EULA now but before EULA and currently, in the shop it says that diamonds are able to do /tp. I try and it says you do not have permission.

Thanks for trying to help :+1:

**Comment by IvyCode** [comment]
It was taken out do to the EULA and now has since been removed from the shop page.
