### ISSUE TITLE
Fluctuating /server Permissions

### ISSUE THREAD

**Issue by TridentSPQR** [Avicus/Issues#266]
The permissions for /server is fluctuating for some reason, sometimes you can do it, sometimes you have no permissions. o-o I thought it was just me... but apparently it's been happening to other people.
http://avicus.net/forums/9f8d44220?page=1#reply97941 Might have something to do the extreme server lag atm...

**Comment by IvyCode** [comment]
Aware this is still occurring and has become more prevalent, but considering the update is just around the corner...


:D
