### ISSUE TITLE
Some Infractions Randomly do not Register

### ISSUE THREAD

**Issue by nathancard** [Avicus/Issues#272]
![](http://i.imgur.com/8Yx83Vj.png)

Taken several minutes later: 

![](http://i.imgur.com/FIm0lsU.png)

It didn't register at all. This has happened several times before. Here's the message I typed in: 
/tempban Skypey_Awesome 3d Excessive infractions for the same offense.
Issued it again without the period, nothing changed.

**Comment by IvyCode** [comment]
Fixed in update. Not pushed
