### ISSUE TITLE
Unpatched Holes in The Divison 2

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#275]
![Image of Yaktocat](http://i.imgur.com/6OEcqY3.png)

**Comment by ParaSpider** [comment]
Fixed.

**Comment by IvyCode** [comment]
Well that's one way to fix an issue!

**Comment by TheRickMaster** [comment]
IvyCode why you ban me im not hacker please desban me!!! is my favourite server :(

**Comment by TheRickMaster** [comment]
please desban me im not hacker!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by TheRickMaster** [comment]
![image](https://cloud.githubusercontent.com/assets/11027190/6209735/44c9a0dc-b5c9-11e4-8e43-bcef74e202cb.png)
im not hacker

**Comment by TheRickMaster** [comment]
![Uploading image.png . . .]()
 you can see now?

**Comment by TheRickMaster** [comment]
![image](https://cloud.githubusercontent.com/assets/11027190/6209801/e0a87fdc-b5c9-11e4-9aeb-1fbec2fb7ce0.png)

**Comment by TheRickMaster** [comment]
![image](https://cloud.githubusercontent.com/assets/11027190/6209817/fd6c6bba-b5c9-11e4-82f3-bfd28500b4d1.png)

**Comment by matic0basle** [comment]
@TheRickMaster You can appeal your ban by emailing support. This is not the place for ban appeals.

**Comment by TheRickMaster** [comment]
Matic  i dont nos héroe is the emailing support

**Comment by matic0basle** [comment]
@TheRickMaster  support@avicus.net

**Comment by TheRickMaster** [comment]
Thx
