### ISSUE TITLE
[Bug][URGENT]Relog Positioning

### ISSUE THREAD

**Issue by TridentSPQR** [Avicus/Issues#288]
If your list name is gray and your TAB name is white... when you relog(to menu), you respawn where you were previously, not at the spectator spawn http://prntscr.com/52hp05
not the survival glitch
Now... that I have experienced it... it's worse. I have that glitch in virtually every single nebula server, and staff can't see staff chat and/or tp, so we can't answer in-game reports lots of the times D:

**Comment by IvyCode** [comment]
Still confused at this. What.

**Comment by ParaSpider** [comment]
Screenshot removed, haven't experienced it, and issue is hard to read. Not only this, but old issue. Closing.
