### ISSUE TITLE
Rubberbanding

### ISSUE THREAD

**Issue by Tarheelkiwi** [Avicus/Issues#302]
I don't know if this problem is in other games, but in Nexus, it is bad.  I would walk and be pulled back.  I can't move.  Sometimes, it would last a couple of seconds, but it is getting worst.  I can't pvp.  Hope you can fix this!  Thanks for reading.

**Comment by IvyCode** [comment]
These effects are the result of a host of issues that should be fixed in the next update. Closing until after the update - they might be relevant afterwards.
