### ISSUE TITLE
 Stomper kills are not counting for XP (pic) & stomps can hurt teammates (on Walls)

### ISSUE THREAD

**Issue by armoredpotato** [Avicus/Issues#304]
Two Kit Stomper issues:

(1) If you kill somebody with kit stomper it says they killed themselves; and (2) you can kill / hurt your teammates.

Issue 1:

http://i.imgur.com/ywUPq5l.jpg

The above is an example, WitherVortexMC was weak when I jumped on him and HuskyJerome123.  My jump killed WitherVortexMC but it says "WitherVortexMC was slain by WitherVortexMC's iron sword".  Of course, the issue is experience points - when I jump on somebody and kill them I want the XP.  (I then killed HuskyJerome123 who was weak from my jump).

This was not a one time occurrence, I can think of four times it has happened today.

Issue 2: Same thing, but I killed a teammate by jumping on him (I killed him and the opponent, but the text said that they both killed themselves (per Issue #1 above).  I thought that teammates were supposed to be immune to your fall damage?

Also, fire still does not spread.  Please fix this, burning used to be a great way to attack skybases.

**Comment by ParaSpider** [comment]
Fixed
