### ISSUE TITLE
Inaccurate /match calculation

### ISSUE THREAD

**Issue by abdulla-almarri** [Avicus/Issues#343]
When you do /match it doesn't calculate correctly. Let's say you get 50 kills and 20 deaths.
Next map, it doesn't change. You still have 50 kills and 20 deaths, it doesn't calculate for that match.

Fix: Restart the k/d count every map.

**Comment by IvyCode** [comment]
I'm going to call this command /stats in the next update. Makes more sense.

This will also fix the issue.
