### ISSUE TITLE
Currently playing time issue

### ISSUE THREAD

**Issue by matic0basle** [Avicus/Issues#345]
If a map plays for 60 minutes the time won't display the actual time.

![](http://i.gyazo.com/dfb2846dd58fbdeb7be5be68040ade9a.png)

At 60 min:

![](http://i.gyazo.com/c4e18a3f8a1be5d3098c523e8ea6add1.png)

After 60 min:

![](http://i.gyazo.com/5de4eee6aae790dbced562240658a932.png)

**Comment by IvyCode** [comment]
Needs to be pushed, but fixed.
