### ISSUE TITLE
Remake or Remove Frostbite.

### ISSUE THREAD

**Issue by RajK23** [Avicus/Issues#354]
Frostbite is a map every time I've played it or seen it played either it:

1.Stalemates at the middle and the map turns into a fun and exciting match where either team pushes forward to try and win.

**or (more often)**
2.One team gets **horribly stomped** and people **diamond armour** camp out the front of the other teams spawn and practically spawn kills them but, **technically not spawn killing** because they give enough breathing room for the team getting stomped to run out of their spawn.

### My Proposal

* Remove some diamond
* Change positioning of monuments
* Have less monuments
* Increase map size slightly
* Change Positioning of Iron/Diamond

**Or**

Remove the map.

**Comment by Flueh** [comment]
Frostbite is one of the iconic maps in the MCzone rotations, so removing it is not in my best interest. Editing it would lose the maps nostalgic feel.

**Comment by RajK23** [comment]
@Flueh Iconic Gameplay shouldn't outweigh the numerous flaws I feel this map has

**Comment by ParaSpider** [comment]
Replacing with Frostbite Beta.
