### ISSUE TITLE
Hub Crashing

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#355]
You can let the hubs crash if you try to use the pet echo plugin.
For example, if you are dia donor, you can type: /pet villager;Notch. It shows you an error message, but the villager got spawned. If you do this more than 3 times, the Hub crashes/the server gets closed.
![2015-01-03_14 52 23](https://cloud.githubusercontent.com/assets/8640683/5602592/6eb68966-9358-11e4-8fcd-19d7e344c888.png)

**Comment by IvyCode** [comment]
Fixed

**Comment by IvyCode** [comment]
I think
