### ISSUE TITLE
Project anti-spawnkill

### ISSUE THREAD

**Issue by Flueh** [Avicus/Issues#356]
Maps that usually includes severe killfarming (EG: Quintus & Frostbite). Plans to prevent this from happening is underway.

**Comment by RajK23** [comment]
Does spawnkilling extend out to kill farming/spawn camping? Where people camp at the front of spawn with diamond armour.

**Comment by Flueh** [comment]
Spawnkilling is defined when a team cannot exit out of spawn due to players killing them. Camping outside spawn is what I plan to prevent.
