### ISSUE TITLE
Gramatical Error - Rule B4 

### ISSUE THREAD

**Issue by Pelpel** [Avicus/Issues#357]
http://gyazo.com/5c8022b4991b5cb1c80716013933d6fa

Should be "of hacking" not "are hacking"

**Comment by FrontierMountie** [comment]
This as well, instead "acceptable" being written as "accepteable"

![accept-tea-ble](https://cloud.githubusercontent.com/assets/6289313/5696934/ce5f069c-9996-11e4-9f7e-7b0154822c8f.png)

**Comment by IvyCode** [comment]
K
