### ISSUE TITLE
Quintus is BROKEN!

### ISSUE THREAD

**Issue by Tynvale** [Avicus/Issues#358]
I was recently playing on Quintus and there was a MASSIVE glitch. People were somehow mining directly underneath the opposition's spawn and then that team would fall into that hole when spawning and were betting killed over and over again! This needs to urgently be fixed because I really like this map and I hate that this is wrecking it! PLEASE FIX THIS!

**Comment by ParaSpider** [comment]
Fixed by @IvyCode
