### ISSUE TITLE
Website Bug - Issue with background

### ISSUE THREAD

**Issue by FrontierMountie** [Avicus/Issues#360]
![watdotavi](https://cloud.githubusercontent.com/assets/6289313/5734496/5b2fc9b4-9b6b-11e4-8784-888c9e8037fa.png)
Experiencing this problem with Firefox and Chrome, not my browser as far as I know.

**Comment by RajK23** [comment]
What resolution is your screen?

**Comment by FrontierMountie** [comment]
1920x1080p, wasn't having this issue prior to today.

**Comment by IvyCode** [comment]
Looks like your browser isn't loading the CSS properly...

**Comment by FrontierMountie** [comment]
I guess it is my browser after all... :L Any ways to resolve this issue on my side?

**Comment by IvyCode** [comment]
Not sure, ask around I guess, if it isn't resolved yet.
