### ISSUE TITLE
Walls - Stompers Hurting Teammates & Players Escaping World

### ISSUE THREAD

**Issue by ShwimpSauce** [Avicus/Issues#362]
I was playing Walls the other day as stomper, and I was doing small jumps which were damaging my teammate. We don't want team griefing, do we?

Another bug I discovered is when a player falls out of the world on a Walls match, that player will join a completely different world apart from the current server. This prevents the game from finishing since they're still in the game... but they're not, in a sense.

I just thought I would address these bugs since they may become an issue in the future if not fixed sooner. 

Good day,
Bronson a.k.a. TheBron_cool

EDIT:
I see armoredpotato has brought up the stomping issue, but it still has not been addressed yet even though it's been over 2 months. :/

**Comment by ParaSpider** [comment]
Fixed
