### ISSUE TITLE
Senex 1 - Four teams?

### ISSUE THREAD

**Issue by Aphelion-** [Avicus/Issues#363]
![Senex 1] (http://i.imgur.com/wFtLZTU.png)

**Comment by Aphelion-** [comment]
![Senex 1] (http://i.imgur.com/suw7S1R.png)

Lol. Look now, I can choose between Red and Blue but it says Cyan and Lime to the right?

**Comment by Aphelion-** [comment]
![Sandstorm] (http://i.imgur.com/drsAJUC.png)

I can choose between Red & Blue on Sandstorm but it says Banana & Apples on the right?

**Comment by ParaSpider** [comment]
Fixed in winter update.
