### ISSUE TITLE
Invisibility not compatible with 1.8.1 (they can see you)

### ISSUE THREAD

**Issue by armoredpotato** [Avicus/Issues#365]
If a person uses an invisibility potion, another person using 1.8.1 can see the nametag of the invisible person.

Person A:  uses invisibility potion
Person B (using Minecraft 1.8.1): sees floating nametag of invisible person

Please fix this.  If somebody is invisible their nametag should also be invisible.  Thanks.

**Comment by ParaSpider** [comment]
Minecraft bug.

**Comment by IvyCode** [comment]
For reference: https://bugs.mojang.com/browse/MC-48730

**Comment by armoredpotato** [comment]
Ah, I see.  Thanks.  Darn Microsoft!
