### ISSUE TITLE
Error & Bug - Website

### ISSUE THREAD

**Issue by Aphelion-** [Avicus/Issues#367]
http://avicus.net/staff
http://i.imgur.com/T9HwzL3.jpg
![Staff] (http://i.imgur.com/T9HwzL3.jpg)

http://avicus.net/canuck_pro
http://i.imgur.com/Zxb1Saq.jpg
![Profile] (http://i.imgur.com/Zxb1Saq.jpg)

**Comment by IvyCode** [comment]
Canuck pro changed their username?

**Comment by matic0basle** [comment]
@IvyCode Going to http://avicus.net/canuck_pro will update the name next to the skin but the URL will remain the same which might cause issues if a person changes their name to canuck_pro.

**Comment by IvyCode** [comment]
It has a cache so that users locating another user who changed their name recently can be found more easily. If someone changes to the old username, they are prioritized.
