### ISSUE TITLE
Hearts added to matches where additional health cannot be gained

### ISSUE THREAD

**Issue by Polarexpress** [Avicus/Issues#369]
After playing Monster Bash or Grotto Arena and getting the added Hearts from the Armor buffs, the added hearts carry over to other maps so players will have up to 10 hearts to much on maps other than Monster Bash or Grotto Arena.

**Comment by Polarexpress** [comment]
One Thought - /gamerule Keepinventory true may need to be turned to false on those maps.  Could be a solution to try if nothing else.

**Comment by IvyCode** [comment]
How do you modify health in a map?

**Comment by Polarexpress** [comment]
Good question . The health buff is via armor buffs. Some armor items come with a +5 health bonus, so as long as you have the item on, you get the added health. When a player puts on all the items, for example the diamond armor arena set in Grotto Arena, they have a total of 20 hearts ( 40 health ) after the match is over when the maps cycle some players keep the heart buff So they end up playing a map not designed for 20 hearts ( 40 health ) with the added buff.  This buff continues even if they re-log. For example Walls01 is where i have my added hearts so if I go to walls03 I am fine, but any map on walls01 I get the buff. Murph_the_cat, me, and several others are having this. My only thought is that the server for some reason is applying the armor buffs. We may not be able to see the armor and are "keeping" it , or some other reason, I am unsure where the problem comes in at. but the health totals match the set health amount gained on both health maps, Grotto Arena a total of 20 hearts or MonsterBash a total of 15 hearts from armor buffs. Those maps were tested with the /gamerule keepinventory true.

**Comment by Polarexpress** [comment]
Hey,

I replied on github.  Thanks. 


Sent via the Samsung Galaxy Note® 4, an AT&T 4G LTE smartphone


-------- Original message --------

**Comment by Polarexpress** [comment]
The problem has been resolved for the most part. The hearts have been removed on those maps, but I still see some players with the added hearts. It seems that once you complete either Grotto Arena or Monster bash the heart level will self correct. If a player in the past was dropped from the match wearing the heart armor and does not complete the map that added the glitch, they will continue to have the hearts. We have a very low amount of players with the glitch. My levels were corrected, so we're most players that I knew had it.
