### ISSUE TITLE
docs.avicus.net severely out of date

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#370]
There's around 200 bugs on that website now... I can help update it if you want I know a fair bit of html & CSS.

**Comment by IvyCode** [comment]
Pointing out the errors could help me and the map devs.

**Comment by matic0basle** [comment]
Examples need to be updated to use new names for authors. Formorgar (components/info) also doesn't exist because theres Formorgar I and II. Thats all that I noticed for now.

**Comment by ParaSpider** [comment]
Updating some stuff now.

**Comment by ParaSpider** [comment]
Fixed?

**Comment by subzero110** [comment]
This should be re opened. I have got many for you:
Quotations around Version, type & creators is incorrect on http://docs.avicus.net/components/info example.
No support for Nexus or CTW.
Lots of Avicade gamemodes listed are obsolete
Holograms are no longer used
In http://docs.avicus.net/components/info the table says CTH but it should be control_the_hill
Thats a few for you, Im sure Ill find some more as time goes by...

**Comment by IvyCode** [comment]
Addressing some of the supposed issues:

- Apostrophes should technically be around version for a string. Same with type and creators, so there aren't any issues there. 
- Lack of support for gamemodes isn't an issue, but rather adding them would be a feature. 
- The gamemodes for Avicade may not be on the server, but some are still on the repository and may come back if desired and supported by MC again.
- Holograms are not supported. That could be removed but I think it would be helpful to bring back. Perhaps just a warning or something.
- CTH should be control_the_hill.

**Comment by Tanpiku** [comment]
Overlooked the CTH thing... fixed as well as added some more nu features.

**Comment by KyloCode** [comment]
I pushed the changes @Tanpiku but it needs some formatting fixes it looks like https://docs.avicus.net/components/nebula

**Comment by Tanpiku** [comment]
@KyloCode I'll try my hand at fixing it :page_with_curl:

**Comment by javipepe** [comment]
I think docs is pretty much up to date now, comment / reopen if there is still anything to add / fix
