### ISSUE TITLE
Users of non-mod groups can briefly see archived posts

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#372]
I assume this is fixed in new site, but just dropping it here

![](http://i.imgur.com/5rzR40m.png)
![](http://i.imgur.com/rHjavu8.png)

http://avicus.net/forums/b365d2997

**Comment by IvyCode** [comment]
Briefly?

**Comment by ParaSpider** [comment]
I saw able to see it for around 4 seconds before I couldn't anymore.

**Comment by IvyCode** [comment]
How did you narrow it to map devs?

**Comment by ParaSpider** [comment]
I'm a mapdev, so it happened. It's a perms thing for mods to do, and it just occurred to me and I haven't seen any other players experience it.

**Comment by resepignev** [comment]
The same happened to me in the same post.
I was able to see the archived post of glitchy. I don't know how long I was able to see it, but it was a reply like in the OP.

**Comment by ParaSpider** [comment]
When this happens, simultaneously the topic title is named just "reply" until you refresh.
