### ISSUE TITLE
Camp Creeper needs rebalancing

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#373]
http://avicus.net/forums/d316c105f?reply=155225

Going off a junior's word, it needs to be changed potion-wise

**Comment by kycrafft** [comment]
I cannot remember the exact amount of potions but I know the map comes with a brewing stand and 2 chests of potions/ingredients. There is blaze powder allowing you to make 3 potions of strenght, which can be made into 3 potions of strength 2 or 3 potions of strength extended (18 minutes total). Along with this there is an invisibility potion (easily made into 8 minutes) some poison potions (easily made into poison 2 which is pretty OP) and countless regen potions. I do not have a problem with the potions spread out across the map but it seems that the potion room underground is quite OP.

**Comment by Polarexpress** [comment]
I agree with this. The map does have a potion room with every combination of material  to make any potion. You can make an endless amount of strength potions as a garden of netherwart is just one wall away from the brewing room. The map has multiple blaze rods and blaze powder with 3 blaze powder in the brewing room. We need to adjust the resource level. The map also has a Notch apple, diamond armor vendor, flame books,  and every other combination you can imagine. Getting a full diamond sharp 3 sword with 12 strength 2 potions can be done by running the correct pattern.

**Comment by Polarexpress** [comment]
I spoke with Murph, She is going to work on a re-balanced version of the map this weekend.

**Comment by Polarexpress** [comment]
The map has been Re-balanced. We may need to tweak it, gut for the most part the major concerns including mass strength production is gone.

**Comment by ParaSpider** [comment]
:+1: @Polarexpress
