### ISSUE TITLE
Nexus kit glitch

### ISSUE THREAD

**Issue by kycrafft** [Avicus/Issues#374]
http://imgur.com/jE8TsgT

new kits leak?

**Comment by kycrafft** [comment]
When you open up the nexus kit selector or do /kit it will show you the upcoming kits too. Also you cannot do /kit barbarian if you are level 30 because it will say you have to be level 48, a feature of the next update

**Comment by IvyCode** [comment]
Dustin has shared kits on the forum; This wasn't exactly a leak, just a mistake in the YAML. Thanks for reporting though.

**Comment by kycrafft** [comment]
Was joking about the leak...

But thanks for fixing it
