### ISSUE TITLE
Broken Leaderboards

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#375]
Heey resepignev here,
The leaderboards aren't updating again. The last time it updated was around 1 week ago.
It isn't a major bug or so and I'm sure it'll be fixed in the next update, but I just want to remind ya that it's currently not updating/broken.

**Comment by resepignev** [comment]
Well it's fixed. Thanks <3

**Comment by resepignev** [comment]
It happened again .-.
Well, I'll reopen this evertime it happens again.
Last update 21.03.15

**Comment by KyloCode** [comment]
Fix again :+1:

**Comment by resepignev** [comment]
Thanks <3
