### ISSUE TITLE
Forum Blank posts/threads

### ISSUE THREAD

**Issue by AtditC** [Avicus/Issues#379]
You can create blank topics with no text etc.
I think this is a bug/not wanted and that's why I post it here, yea.

1) Create a new topic, with no title (use the space key on your keyboard) but just with some text in the body. Let's say I write "hi" in the body.
2) delete "hi" and replace it with your keyboard-space-key
3) update the post and wait until it gets locked 

Screenshots:

![](http://i.gyazo.com/153e16398b0e2aee22ddb1077511f560.png)

![](http://i.gyazo.com/ab37b2ddf98492f464af47a28b695c38.png)

Post to my "test": http://avicus.net/forums/5d9aa5269

**Comment by KyloCode** [comment]
It doesn't let me :c

**Comment by resepignev** [comment]
I successfully did the same. It also can be done in posts and replies.
