### ISSUE TITLE
avicus.net/staff - Map Developer colour is wrong.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#380]
![screen shot 2015-03-09 at 10 35 34](https://cloud.githubusercontent.com/assets/7715330/6552644/4acd0426-c648-11e4-998e-de3f35e8f8da.png)
The Junior Moderator and Map Dev colour are the same, whilst the Map Dev colour should be green.

**Comment by ParaSpider** [comment]
It's because there's a person from the junior mod group overriding the map developer rank, and it overrides for everyone else. I assume fixed in new site, but we'll see.

**Comment by pelpelajax** [comment]
@ParaSpider You're right. Now iMercury isn't a Junior anymore the Map Dev colour is right. How come the moderator colour doesn't overwrite it?

**Comment by ParaSpider** [comment]
Not sure. Going to leave open though in case new site has this issue.

**Comment by KyloCode** [comment]
Nope, it's all good.
