### ISSUE TITLE
There are server duplicates when opening the compass in lobby

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#388]
It shows doubles of the server in the compass

http://gyazo.com/7207d8a6508da90e811f4d175eaa491d
http://gyazo.com/282ee5f38426ea2e5110219d868534f6

**Comment by kycrafft** [comment]
Yeah this annoys me.

**Comment by resepignev** [comment]
It's back. Since the CTW server are merged into Nebula, there are 2 Mix01 server in the server selection.
