### ISSUE TITLE
Position of the "Post" button

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#390]
heeya,
I know the website is just up, but I would like to say that the "post" button is slight slipped.
It is to the right instead of under the text box.
It happens only to replies, from what I saw
Maybe it's just for me, but then you can close this issue.
Pictures: http://prntscr.com/6oemmr
http://prntscr.com/6oen21

**Comment by KyloCode** [comment]
Fixed in dev website, pushing tonight, if I haven't.
