### ISSUE TITLE
Clay Wars - CTW - Players spawn on Spectators platform.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#396]
![screen shot 2015-04-02 at 11 16 10](https://cloud.githubusercontent.com/assets/7715330/6961268/c9e7feac-d929-11e4-9311-8f28d824c8bb.png)

**Comment by matic0basle** [comment]
When you are fixing this just move it further back

**Comment by KyloCode** [comment]
Duplicate.
