### ISSUE TITLE
Staff Ranks - Staff Members get normal credits, not the credits they should get from their Rank.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#399]
So, if you have emerald, your credits is multiplied, instead it stays normal.

**Comment by Sethskype** [comment]
You mean credits?

**Comment by Sethskype** [comment]
How many credits are you getting for a kill?

**Comment by resepignev** [comment]
diamond donors get 7c per kill, so I guess 3c per kill for non donors

**Comment by pelpelajax** [comment]
2 for non-donors.

**Comment by KyloCode** [comment]
Fixed upon deployment!
