### ISSUE TITLE
When the game starts it does not tp you to where you are supposed to spawn

### ISSUE THREAD

**Issue by Micahb222000** [Avicus/Issues#400]
- Can't join a team after it auto joins.
- Compass points to nearest player, including teammates.
- When the game starts it does not teleport you to where you are supposed to spawn, it just puts you in survival, I died because I was flying around when the game started.

Kits-
-Sonic is speed 2, too OP.
-Stomper still needs to be removed or ONLY take no fall damage
-There is nothing to work for anymore. Everyone has every kit. No point in playing.

**Comment by ParaSpider** [comment]
1. /leave, then /join
2. Intended...?
3. That is a bug.

Post suggestions on the forum please, I'm editing your issue to single out that individual error.

**Comment by KyloCode** [comment]
One bug per issue please, not 6!

**Comment by KyloCode** [comment]
Also, mainly a region (boundary) issue.
