### ISSUE TITLE
Staff Applications Subforum not showing

### ISSUE THREAD

**Issue by matic0basle** [Avicus/Issues#403]
With the update some new subforums appeared on the forums. The Staff Applications subforum that was under Discussions is now gone from the sidebar

You can still get to it by going to there from your topics and then clicking on the link under the title where it says which subforum it was in.

![](http://i.gyazo.com/9d2495f8afec0dcf08f6129c48bbb8ef.png)

![](http://i.gyazo.com/d41a078f5d64b9b89366ac3df5450c84.png)

I asked Pelpelajax about this and he said it was a bug.

**Comment by KyloCode** [comment]
That is intended.

**Comment by matic0basle** [comment]
@KyloCode My bad then. I imagine they will show when appilcations are open or is that also out of the question?

**Comment by KyloCode** [comment]
That's correct.
