### ISSUE TITLE
CTW map in a DTM rot

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#405]
http://gyazo.com/ce0e33bc08c55db0b52d9c5fdb94993c

**Comment by AtditC** [comment]
Can confirm, there are many other bugs in the same category (dtm in ctw's etc.)

**Comment by ParaSpider** [comment]
This is because of the DTM versions being purged with the CTW versions. Thanks!

**Comment by KyloCode** [comment]
@Avicus/map-developers Pretty easy fix, is this resolved?
