### ISSUE TITLE
Incorrect "Last seen" counter on website profile

### ISSUE THREAD

**Issue by AtditC** [Avicus/Issues#406]
Example: I wasn't online for the past 4 months, but on my profile, it shows up: Last seen about 2 months

If you need evidence: https://avicus.net/AtditC#infractions
![image](https://cloud.githubusercontent.com/assets/7355350/6969252/6d20d95c-d96d-11e4-9a56-d2c7e8902055.png)

**Comment by KyloCode** [comment]
I guess you accidentally joined or have a compromised account...
