### ISSUE TITLE
SG01 isnt starting

### ISSUE THREAD

**Issue by SamirTheory** [Avicus/Issues#408]
title say all

**Comment by KyloCode** [comment]
Are there > 10 on?

**Comment by SamirTheory** [comment]
There were 11 people on and the match didnt start

**Comment by KyloCode** [comment]
At 11 the bar starts going down indicating its starting, its likely some just left. I'll check tonight.

**Comment by ParaSpider** [comment]
Considering other matches on SG are starting... and it's been fine and smooth sailing so far, it's 99% likely someone left.
