### ISSUE TITLE
Ender Crystal [Map Problem]

### ISSUE THREAD

**Issue by Emmaye** [Avicus/Issues#413]
![qpwnh2i](https://cloud.githubusercontent.com/assets/11779651/6978827/1d29ff92-d9a8-11e4-90e5-122d64073ede.png)

**Comment by Emmaye** [comment]
Just wanted to state, this is not a lighting glitch at all, nor texture error.

**Comment by ParaSpider** [comment]
Please post coords and map name next time, thanks!

**Comment by ParaSpider** [comment]
I can't find it.

**Comment by Emmaye** [comment]
It's happening on multiple maps with the health bar, I don't know why it randomly appears, and coords don't matter for this bug to be seen.
![juoigsc](https://cloud.githubusercontent.com/assets/11779651/6983830/5adba438-d9f0-11e4-8a95-c8c331190bf6.png) Here you can see it in SG

**Comment by ParaSpider** [comment]
That's an enderdragon aha

We need it for the top to function, I was confused for a bit
