### ISSUE TITLE
DTM04 Clay Wars map is broken

### ISSUE THREAD

**Issue by SamirTheory** [Avicus/Issues#416]
You spawn on the spectators spawn and no one can destroy the monument

**Comment by matic0basle** [comment]
Unless the YML file was changed so spawn and monument regions get changed its not the maps fault. Something that could cause this is the new update spawning playing teams in the observer spawn for some reason, don't know about the monument.

**Comment by ParaSpider** [comment]
I don't understand... the YML hasn't changed.

**Comment by matic0basle** [comment]
Possibly the plugin spawns players in obs spawn because it thinks that the actual spawn? I don't know but if this repeats just remove the map from rots until fixed.

**Comment by KyloCode** [comment]
Guessing its boundaries.

**Comment by KyloCode** [comment]
Changed up the boundaries.
