### ISSUE TITLE
SG01 Spawning Glitch

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#417]
You can spawn in those starting holes where u get pushed up in the original HG. Including during DM its unfair

**Comment by JKawesome** [comment]
A screenshot:

![2015-04-04_19 03 24](https://cloud.githubusercontent.com/assets/5256393/6995440/7b8bff44-dafd-11e4-93e2-9751b5c5a743.png)

**Comment by ParaSpider** [comment]
What maps?

**Comment by Sethskype** [comment]
The maps I saw: SG01 and Drybone valley

**Comment by ParaSpider** [comment]
Those are both fixed

**Comment by ParaSpider** [comment]
Closing. If any other SG maps have pods, make another issue for that individual map.
