### ISSUE TITLE
Add a region flag to prevent natural world changes

### ISSUE THREAD

**Issue by Emmaye** [Avicus/Issues#418]
![tree2](https://cloud.githubusercontent.com/assets/11779651/6986459/612479a8-da0b-11e4-82a3-ae8667ad285c.png)
![tree3](https://cloud.githubusercontent.com/assets/11779651/6986461/615046d2-da0b-11e4-8a5d-6eaec90805da.png)
![tree4](https://cloud.githubusercontent.com/assets/11779651/6986460/6124d8e4-da0b-11e4-86e5-cf8fe22196af.png)
![tree](https://cloud.githubusercontent.com/assets/11779651/6986466/6c8019e2-da0b-11e4-926f-ae0aee9469ab.png)

**Comment by KyloCode** [comment]
This should be implemented as a region flag of sorts.

**Comment by ParaSpider** [comment]
Tried changing the leaves into non-decay in-game... even loading the world freezes and crashes me. I think a region flag would be nice haha

**Comment by KyloCode** [comment]
Added decay as a flag.

```
flags:
  decay:
    allow: false
```

Map devs can give it a test.

**Comment by resepignev** [comment]
If the regions doesn't work then use this: http://minecraft.gamepedia.com/Leaves#Data_values
(use a server with worldedit to change the leaves. Command: //replacenear <radius> 18:<data value of decaying leaves> 18:<data value of non decaying leaves>)
I hope this helps!
