### ISSUE TITLE
You can re-place wool

### ISSUE THREAD

**Issue by ImRaging** [Avicus/Issues#421]
Say the blue wool has already been placed on a map, you are still able to collect the same wool, break the current wool placed, and place yours. You will still get credits doing this which could result in being able to continuously break and replace the wool.

**Comment by ParaSpider** [comment]
Map?

**Comment by Sethskype** [comment]
you can also replace where the obsidian was with a different block and break it and it gives you credits and it says in chat

**Comment by ParaSpider** [comment]
shiiiii

**Comment by KyloCode** [comment]
Fixed. I'll be looking into instances of this occurring and might punish accordingly.
