### ISSUE TITLE
Can't Enchant Items

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#424]
http://gyazo.com/cbf488308b3b46c6f3ba2ef66f249684

notice i have 2 levels and i can't enchant

**Comment by matic0basle** [comment]
You need lapis.
https://github.com/Avicus/Issues/issues/392

**Comment by Sethskype** [comment]
I know I do but there is no lapis in the maps so there is no use in having enchant tables

**Comment by matic0basle** [comment]
I linked to a previous issue. This is a dupe anyway.

**Comment by ParaSpider** [comment]
Fixed anyway
