### ISSUE TITLE
Purchased 10,000 Credit Badge. nothing happened :(

### ISSUE THREAD

**Issue by KriticalPvP** [Avicus/Issues#425]
Hello, today 05/04/2015 I purchased The 10,000 Credits Badge, and I received nothing, I have screenshots, provided below:
http://gyazo.com/b5b4d5ef5e784d66743f4f9d3f333d2c

please fix this, I am happy to wait!

Thanks a tonne 

~ _Bazooka

Written by Friends GitHub...

**Comment by ParaSpider** [comment]
Resolved!
