### ISSUE TITLE
Minotar not reliable 

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#426]
![](http://i.imgur.com/XheJJeu.png)

**Comment by KyloCode** [comment]
Which one?

**Comment by ParaSpider** [comment]
crafatar

**Comment by matic0basle** [comment]
By saying crafatar isn't reliable I am not sure what you mean since using inspect element the faces are from minotar (Checked my friends and staff page)

**Comment by ParaSpider** [comment]
I inspected element and got crafatar

**Comment by matic0basle** [comment]
![](http://i.gyazo.com/bbb3d9f55ed13bd4e30bfcf054a8f75e.png)

**Comment by KyloCode** [comment]
We use both, which failed you?

**Comment by matic0basle** [comment]
For me Minotar is messing up

**Comment by ParaSpider** [comment]
Mino i guess

**Comment by KyloCode** [comment]
Remove minotar.
