### ISSUE TITLE
Unable to access website

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#427]
Ever since the new website was released I am unable to access it and I get this error 
Error code: ERR_CONNECTION_TIMED_OUT. This is for google chrome aswell. I can't access it on any computers in my house but can access it on my phone using 3G. Erm help?!?

**Comment by matic0basle** [comment]
Could be an issue with your network since it works on your phone but not devices connected to your home network. A version of Google Chrome could help.

**Comment by ParaSpider** [comment]
Not an avicus issue, this is a chrome thing on your end
