### ISSUE TITLE
TempBans - Incorrect expire date.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#428]
![screen shot 2015-04-06 at 11 19 45](https://cloud.githubusercontent.com/assets/7715330/7002687/fdc1d64e-dc4e-11e4-8167-74850e29da0d.png)
![screen shot 2015-04-06 at 11 21 07](https://cloud.githubusercontent.com/assets/7715330/7002691/0af3d948-dc4f-11e4-9c61-732d6470dce7.png)
Both were 25 days.
You can't tb into the next month
If the duration goes into the next month it bugs out

**Comment by KyloCode** [comment]
It looks like it's just reversed? 25 days back.

**Comment by pelpelajax** [comment]
@KyloCode The reason it reversed it because you can't ban into May, due to the fact that we're in April.

**Comment by pelpelajax** [comment]
@KyloCode Wouldn't this be Website and Plugin?

**Comment by KyloCode** [comment]
Wasn't this fixed?

**Comment by KyloCode** [comment]
Yes this was fixed, tested.
