### ISSUE TITLE
can't remove people from teams

### ISSUE THREAD

**Issue by samthemenace** [Avicus/Issues#429]
I tried to remove someone from a team, I got this site message:

Error
undefined method `destroy' for nil:NilClass 

Backtrace
/home/web/avicus.net/app/controllers/teams_controller.rb:137:in `cancel_invite'

Params
member_id => "670" 
controller => "teams" 
action => "cancel_invite" 
id => "67"

**Comment by KyloCode** [comment]
Were you cancelling an invite or removing a player from your team?

**Comment by samthemenace** [comment]
Removing ivycode from invite

**Comment by KyloCode** [comment]
I can't reproduce this... Is the player removed from your team? You might have clicked it twice.

**Comment by KyloCode** [comment]
Added a check for double clicking.

**Comment by samthemenace** [comment]
Must have been some exceptional circumstance because this didn't happen
when I tried removing an invite earlier
