### ISSUE TITLE
Odd statistic behavior?

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#432]
![](http://i.gyazo.com/7ff0a9d6497646da4b9dac09737b3dc9.png)

Engaged in PvP, but no:
- Time
- K/D
- Joins
- PvP K/D

Is this an error when stats regenerated after update?

**Comment by KyloCode** [comment]
The first week or so sessions weren't tracked at all. KD & PVP K/D is 0 because 0 kills 1 death.
