### ISSUE TITLE
Can't stay logged in for more than two minutes

### ISSUE THREAD

**Issue by RileGuy** [Avicus/Issues#434]
I log into avicus and then two minutes later I get ejected from the game due to a ban that was appealed but however, I still get kicked from the game. I will not be able to stay on avicus unless.this is fixed. Please make an announcement on the forums when this is fixed. I would also like to know by Skype @live:rpreator0520 Thanks!

**Comment by ParaSpider** [comment]
Is this still occurring?

**Comment by RileGuy** [comment]
I don't know. I haven't logged on in a couple of days. I will test it out today.

**Comment by ParaSpider** [comment]
What happened?

**Comment by ParaSpider** [comment]
It's not occurring as frequently as you (It's happened twice so far) but regardless it duped.

![](http://i.gyazo.com/0fc4d006b6b3e188713a4fcf0c59030b.png)

**Comment by RileGuy** [comment]
I was testing it out yesterday. It didn't happen at all which was good. So this problem has been solved thanks!
