### ISSUE TITLE
Weird Glitch

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#435]
So I was afk on minechat in an SG match and this happened

http://imgur.com/ERlDzyz,eLNZcos

**Comment by ParaSpider** [comment]
What am I looking at here?

**Comment by Sethskype** [comment]
I was alone on an SG match on minechat and I left my phone open on this SG match. 4 minutes later it says I won 2 matches and got credits

**Comment by AtditC** [comment]
It's maybe because you used an app on your iPhone to connect to Avicus... Pretty sure you can be banned for it, because they will ban you for each Bug abusing, so my personal tip is don't do it again :) Even if it is for a Github post x)

**Comment by ParaSpider** [comment]
Yeahhhh after a talk with seniors don't join matches using minechat.
