### ISSUE TITLE
Remove map builder signs in lobby

### ISSUE THREAD

**Issue by JKawesome** [Avicus/Issues#437]
Should be xArcturus, not xArchturus, unless it was intended for some reason. This is in the SG section of the main lobby.

![screen shot 2015-04-07 at 6 57 55 pm](https://cloud.githubusercontent.com/assets/5256393/7037495/7bce5a58-dd58-11e4-8909-6b0bdf787426.png)

**Comment by Tanpiku** [comment]
Probably a good idea to remove the name signs and just keep the heads considering name changes.

**Comment by Tanpiku** [comment]
Done!
