### ISSUE TITLE
Canceling friend requests

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#439]
You can't cancel friend requests on the website.
It only refreshes the profile of that player.
It's easy to reproduce this issue, just send them a request and then try to cancel it. 
The button should stay orange.

**Comment by KyloCode** [comment]
Cannot reproduce.

**Comment by matic0basle** [comment]
I can. Heres a gif. I included the adress bar so you can see that when it refreshes the circle for refresh becomes a cancel cross on chrome. Could be a browser thing.


![](http://i.gyazo.com/ee550a7bddc153bc0108f9939783dbd6.gif)

**Comment by KyloCode** [comment]
Fixed a while back!
