### ISSUE TITLE
No credit "Ping" sound for certain types of kills

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#440]
You do not hear the credit "Ping" sound for the following types of kills:
Knocked off a high place
Knocked into the void
Blowing them up

**Comment by KyloCode** [comment]
The sounds does occur where the death occurs.

**Comment by ParaSpider** [comment]
Is this is a feature request?

**Comment by pavilion99** [comment]
Could someone clarify the goal of this issue?

**Comment by IcedCode** [comment]
Ensure that all death types have the sound as some don't

**Comment by KyloCode** [comment]
Fixed on restart!
