### ISSUE TITLE
Icons not showing 

### ISSUE THREAD

**Issue by matic0basle** [Avicus/Issues#441]
The icons on the website are not showing.

Examples:
Navbar 
![](http://i.gyazo.com/9c79b46af8c4b4de936d0217817805ce.png)

Social Links on profiles
![](http://i.gyazo.com/a38838bddec8382c229fc7829b68c53e.png)

Forum posting buttons
![](http://i.gyazo.com/b34e2504ad0d697ac7360e0cbea2230e.png)

Using inspect element I could see that the code is there but for some reason not displaying.
![](http://i.gyazo.com/f9f3d9acaa8ea76d68a1c00242f100ef.png)

Tested on Chrome and Firefox without any extensions.

**Comment by KyloCode** [comment]
Well it's gotta be some type of client issue, I can help diagnose it perhaps.

**Comment by pavilion99** [comment]
It doesn't seem to be a client issue.  I have the same thing.
![screen shot 2015-04-09 at 11 07 21 pm](https://cloud.githubusercontent.com/assets/5050363/7081266/90bb41ae-df0d-11e4-841c-cce7dd1d9482.png)

**Comment by ParaSpider** [comment]
Same thing here, I think everyone has it.

**Comment by KyloCode** [comment]
Oops, in attempting fix for one person, broke it for all.

**Comment by matic0basle** [comment]
Works now, thanks.
