### ISSUE TITLE
In the map page for reviews, add readable colours

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#442]
If anything, the color should be made "Teal" to match the color much like the in-game one. The cyan color on the site now can barely be read in white text over light blue, and this looks much better;

![](http://i.gyazo.com/615e9bc10c3f16bfa91375e9d44d4d60.png)

Compared to;
![](http://i.gyazo.com/042aa9bbe63fb7f048511fec0ff2e69a.png)

**Comment by ParaSpider** [comment]
Also happens with yellow.
![](http://i.gyazo.com/b3317bcb1c3053b770069342b85f5bb5.png)

**Comment by matic0basle** [comment]
Why not change text to black?

**Comment by KyloCode** [comment]
I'll be taking maps down entirely until a rating system is up in game.
