### ISSUE TITLE
When Deathmessages toggled to friends, you don't see your own kills

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#444]
![screen shot 2015-04-10 at 17 46 58](https://cloud.githubusercontent.com/assets/7715330/7091402/aa925882-dfa9-11e4-8922-6d7d9a040994.png)

**Comment by KyloCode** [comment]
Fixed

**Comment by pelpelajax** [comment]
@KyloCode Broke again. 
![screen shot 2015-05-02 at 18 26 01](https://cloud.githubusercontent.com/assets/7715330/7441819/a2333dc2-f0f8-11e4-8fea-e4b370367144.png)
