### ISSUE TITLE
Players can break spectator spawn.

### ISSUE THREAD

**Issue by JKawesome** [Avicus/Issues#446]
They can enter, build in, and break the spectator spawn. This screenshot is on Senex III, but I'm pretty sure it happens on all maps.

![screen shot 2015-04-10 at 12 37 41 pm](https://cloud.githubusercontent.com/assets/5256393/7095370/ad0e9150-df7e-11e4-8ed0-47d14635127e.png)

**Comment by ParaSpider** [comment]
@KyloCode Could you hardcode this back in, or do you want the mapdevs to protect them?

**Comment by KyloCode** [comment]
It's better for it to be per-map in the YAML, each spawn is differently sized.

**Comment by Slicorn** [comment]
Regions were added to the spectator spawn so players can not build/break blocks. 
Thank you for reporting this.

**Comment by resepignev** [comment]
still open
