### ISSUE TITLE
Incorrect amount of players in tab menu

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#449]
http://gyazo.com/9ed2f16763cbfec19ac2c989515d8cad
http://gyazo.com/3c04c046c8a10ee6d7a7adc7be32f150

In the /list it doesn't show Hacktivism nor Nathanetrius online but in the tab button it does

/list showed 23 Players but Counting the amount of players in tab it says 36(18x2)

**Comment by IcedCode** [comment]
I believe that when a player leaves the server he/she doesn't always leave on the tab list. Also when the map cycles to a new map with different team colour, the colour of the team they were previously on stays meaning there can be multiple colours in the tab list for people that have aleft at different points during the server cycle

**Comment by KyloCode** [comment]
It's not within our control, Spigot or MC's issue.
