### ISSUE TITLE
Can't register in the web

### ISSUE THREAD

**Issue by vYuri** [Avicus/Issues#452]
When I receive the ip and I connect it gives me an error, this is the error (game):
- http://gyazo.com/9b6657e68729d1d57fae58efc72c5477

**Comment by pavilion99** [comment]
I'm sorry could you be more clear on your error? From the title I was led to believe that it was a web issue but you gave a screenshot from in game.

**Comment by vYuri** [comment]
The web does not redirect to complete the registration and i can't enter the server to register.

**Comment by vYuri** [comment]
Comment: This also happens to other players, not only in my case.

**Comment by pavilion99** [comment]
The first thing that you should know is that /register is no longer a command in game. I will look into the other issue.

**Comment by vYuri** [comment]
I know, /register does not work anymore. i use the web, so the error I think that must be it.

**Comment by vYuri** [comment]
For me, now is working (but the problem is still doing for some people)

**Comment by pavilion99** [comment]
Could you ask them to post screenshots of their issues here?

**Comment by KyloCode** [comment]
I think I know the cause, the BungeeCord proxy servers loose connection with the registration service (redis) after 24 hours of running. I reset them so it should be working. I'll look into a more permanent solution.

**Comment by vYuri** [comment]
Ok, thanks
