### ISSUE TITLE
Refs loose their donor prefix.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#464]
![screen shot 2015-04-13 at 17 18 35](https://cloud.githubusercontent.com/assets/7715330/7118691/3cbfd24e-e201-11e4-948c-67b3436227b9.png)
![screen shot 2015-04-13 at 17 18 53](https://cloud.githubusercontent.com/assets/7715330/7118692/3cdee09e-e201-11e4-9525-f9823838e0a1.png)

**Comment by KyloCode** [comment]
@pavilion99 pushed a potential fix, how's it working?

**Comment by pelpelajax** [comment]
@KyloCode I'll get him to test.

**Comment by pelpelajax** [comment]
@KyloCode @pavilion99 Fixed.
