### ISSUE TITLE
Credits for winning a match you didn't win

### ISSUE THREAD

**Issue by matic0basle** [Avicus/Issues#465]
I got credits for winning a match but the other team won.

![](http://i.gyazo.com/473af48b599e21311959348281d48bb9.png)

Proof that I was on yellow:

![](http://i.gyazo.com/9211de97495d68f4835a6bf761615ee0.png)

**Comment by pavilion99** [comment]
Could you mention what gamemodes this occurs in?

**Comment by ParaSpider** [comment]
https://github.com/Avicus/Issues/issues/397 Dupe.

**Comment by vYuri** [comment]
still happening / Mix

 http://gyazo.com/804253ad0abc0345dda2becf87db001a
