### ISSUE TITLE
Armor is dropped on some maps

### ISSUE THREAD

**Issue by vYuri** [Avicus/Issues#467]
Candyland 2:
- http://gyazo.com/59c22733f962e357c1d363ae7f309135
- http://gyazo.com/d10a3437a641a428d9fc04f07fbb6e4c

Rendezvous 1:
- http://gyazo.com/ebadf0c3bad59e685711b564cd9a1de2

Consilium:
- http://gyazo.com/0472184abc7690bbfb928ad082e2f542

And many other maps

**Comment by KyloCode** [comment]
Fixed a bit ago I believe.
