### ISSUE TITLE
Invisible Players

### ISSUE THREAD

**Issue by SweetMango** [Avicus/Issues#469]
Whilst games are in progress, there are a number of players who come across as invisible. It's becoming quite a large issue as more and more players experience this, and it occurs on all game-modes as far as I know. 

The 'invisible' players seem to be flying around the map in another location (as if they were spawning at the spectator spawn instead).

![2015-04-17_12 04 24](https://cloud.githubusercontent.com/assets/6296366/7195191/bdada218-e4fa-11e4-81c7-93dbbb2610ce.png)

**Comment by KyloCode** [comment]
Tell me if the changes I push do any good, servers need restarting.

**Comment by ParaSpider** [comment]
Seems to still be occurring.

**Comment by vYuri** [comment]
Are you sure if the server was restarted?

**Comment by KyloCode** [comment]
Yeah servers definitely restarted.

Why can't I encounter the issue... Even on my laptop through the school's network... Bleh.

**Comment by ParaSpider** [comment]
Here is evidence of it still occurring; in the position, he was hitting in front of me.

![](http://i.imgur.com/VSDc6N1.png)

**Comment by KyloCode** [comment]
Someone should notify when it's happening to them in game so I can properly diagnose it.

**Comment by KyloCode** [comment]
Wait is it just 1.8 users that experience this..?

**Comment by vYuri** [comment]
I play on 1.7.2 and also happens.

**Comment by ParaSpider** [comment]
Happens for both versions. I'll contact you if there's any invisible players.

**Comment by ParaSpider** [comment]
Rapturous on MCZone01 experiencing this glitch, got a whole killfeed and nobody saw him.

![](http://i.gyazo.com/55d03354052374578635b6ce880baafd.png)

**Comment by KyloCode** [comment]
I understand it's occurring, I just need someone to tell me when I'm online so I can investigate the issue.

**Comment by ParaSpider** [comment]
Alright, at first thought it was in means to updating github so you could see it and log on.

**Comment by KyloCode** [comment]
2 new changes upon restart. Testing soon again.. :|

**Comment by KyloCode** [comment]
People have reported this has been fixed. Hoorah.

**Comment by vYuri** [comment]
Thanks ! :D
