### ISSUE TITLE
Spectators are visible

### ISSUE THREAD

**Issue by Straightened** [Avicus/Issues#470]
Spectators will flash on the screen and are visible by players in-game. It makes it very difficult for Mods to take reports and whatnot when the hacker is able to see them while they are playing.

**Comment by Awesomerp** [comment]
I think I have recorded this if it's needed

**Comment by KyloCode** [comment]
That would be helpful, as long as it was recorded in the past 16 hours or so

**Comment by KyloCode** [comment]
Nevermind, clear issue for all users.

**Comment by KyloCode** [comment]
Fixed upon deployment. Probably.
