### ISSUE TITLE
Grab & Run gamemode

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#471]
https://avicus.net/forums/148c98fdf

One of the few plausible gamemodes that no servers have and it mixes 2 of our signature/concept gamemodes of Avicus into a really great platform for both players of both gamemodes to enjoy. I think this would be popular for both sides of the community, and with the positions and map styles I could see it happening. It has been acknologed and from your/Kylo's words it was **I'd like to see it in action!**.

Details are in thread. Has good community feedback, YAML layouts, and maps are provided.

**Comment by KyloCode** [comment]
Because this is more than a small feature to add and we haven't discussed it much, it should stay on the forums for now. We'll keep it in mind.
