### ISSUE TITLE
SG Leaderboards?

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#472]
Is no one playing SG or are objectives & kills/deaths just not being tracked.

**Comment by IcedCode** [comment]
No one is playing SG....

**Comment by ParaSpider** [comment]
@IcedCode A lot of people are, it's more popular than CTH and Nexus and HG at least. I'm able to gather some players and play.

**Comment by Sethskype** [comment]
It's not. I've won probably 4 times now and got a couple of kills from it.

**Comment by SweetMango** [comment]
People are playing, the stats just aren't being tracked.

**Comment by Aki35** [comment]
As of now, it is still not being tracked.

**Comment by thekeenant** [comment]
Removed with update.
