### ISSUE TITLE
"Invalid book tag" When opening the game booklet in hub

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#474]
You get this (I use 1.8 aswell not sure about 1.7):
![2015-04-17_20 29 03](https://cloud.githubusercontent.com/assets/7426927/7209466/bd46c89a-e540-11e4-84e4-0c3e64513965.png)

**Comment by vYuri** [comment]
https://github.com/Avicus/Issues/issues/468 

That was already reported.

**Comment by IcedCode** [comment]
Sorry I apologise
