### ISSUE TITLE
Stats are tracked on dev server

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#476]
Credits, kills, everything. :santa:

**Comment by vYuri** [comment]
This does not happen with the objectives, but yes with the kills T.T

**Comment by ParaSpider** [comment]
You don't have dev access...

**Comment by vYuri** [comment]
LOL, I mistook with the scrimmage server, I apologize.

**Comment by KyloCode** [comment]
You get credits from kills on scrim?

**Comment by vYuri** [comment]
Yes, my last death are from the scrimmage server.
