### ISSUE TITLE
Senex 3 Spectator spawn(No protection)

### ISSUE THREAD

**Issue by LordDraksis** [Avicus/Issues#477]
People can bridge to Spec spawn and grief it.

Photos: http://imgur.com/mC74atR,mR8gSop,RRO2Y4R#0

**Comment by ParaSpider** [comment]
Dupe

**Comment by LordDraksis** [comment]
Dupe?

**Comment by LordDraksis** [comment]
Ah i see. The other post should at least have a better title though.

**Comment by ParaSpider** [comment]
https://github.com/Avicus/Issues/issues/446 What's wrong with the title?

**Comment by LordDraksis** [comment]
Well by reading the title it did not tell me what map it was.
Which is why i made a dupe without knowing.
