### ISSUE TITLE
on tablets 'weekly' leaderboard box over leaps 'leaderboard'

### ISSUE THREAD

**Issue by Awesomerp** [Avicus/Issues#479]
This picture  is of the leaderboard on my tablet (hudl.2) 
![screenshot_2015-04-18-11-46-46](https://cloud.githubusercontent.com/assets/11773960/7215146/750fea26-e5c1-11e4-9f74-3284e0b95d5e.png)

**Comment by matic0basle** [comment]
Its not the only thing that could be improved for mobile.

The index site has issues as well like the join button going off the image,  buttons going over the icons etc. I don't think this is that important.

**Comment by KyloCode** [comment]
Not going to address issues like this. It's awesome that it works nicely with mobile and tablet, but if it fails in small places like this, then oh well.
