### ISSUE TITLE
Scrimmage servers: 1 Hour instead of 2.

### ISSUE THREAD

**Issue by Roboticboy** [Avicus/Issues#481]
When reserving a scrimmage server, the description states that it will be available for 2 hours, but it closes after 1 hour.

**Comment by KyloCode** [comment]
Each slot last two hours, as stated on the website.

**Comment by Roboticboy** [comment]
but is doesnt last 2 hours, thats the thing.
It closes after 1 hour, as I tested it yesterday night.

**Comment by KyloCode** [comment]
You may have had your timezones wrong, it's worked for other teams...

**Comment by Roboticboy** [comment]
What timezone does it use?

**Comment by KyloCode** [comment]
Your own timezone, bases it off your browser. There were issues with timezones on the website earlier today that may have lead to the confusion though.
