### ISSUE TITLE
Players with low online time can't have ranks?

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#483]
![screen shot 2015-04-19 at 18 27 08](https://cloud.githubusercontent.com/assets/7715330/7220282/ca6cc8ee-e6c1-11e4-8afa-025439d94079.png)
![screen shot 2015-04-19 at 18 27 25](https://cloud.githubusercontent.com/assets/7715330/7220283/ca960f9c-e6c1-11e4-808f-799daa38860d.png)

**Comment by ParaSpider** [comment]
Something seems off but I don't think it's because of low online time, he might have gotten a glitched rank

**Comment by KyloCode** [comment]
There were two slayersource's in the database... That's never happened before. Weird.
