### ISSUE TITLE
Leaders: Disbanding & Leaving

### ISSUE THREAD

**Issue by Roboticboy** [Avicus/Issues#485]
Why do leaders have an option to LEAVE and DISBAND, it isn't logical.

**Comment by Roboticboy** [comment]
Apologies I was unable to label it, was using a phone at the time, and was unaware of how to do so.

**Comment by Roboticboy** [comment]
Whoops.

**Comment by ParaSpider** [comment]
Only people with this repo access can label issues.

**Comment by Roboticboy** [comment]
Ah, thanks Para. The more you know.

**Comment by KyloCode** [comment]
Not worth fixing :P
