### ISSUE TITLE
Make GMT viewers use BST for scrim reservations

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#488]
Its what the time actually is for people in this area so its less confusing for players

**Comment by matic0basle** [comment]
I don't see how it's less confusing. Time is based of the browser so it's the time that it currently is where they are. Having them have to convert the time into a different timezone wouldn't really be less confusing IMO.

**Comment by KyloCode** [comment]
It's based on the browser, so if your computer is in GMT, the website will be. If it's BST, it will be in BST (GMT +1).
