### ISSUE TITLE
Leaderboard on the profile not complete

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#490]
Heey,
I already made such an [issue](https://github.com/Avicus/Issues/issues/414), but it was closed, cuz I wasn't ranked.
But now I checked my stats on CTH and on my profile, and suddenly CTH was missing on my profile.
I'm definitely ranked (I'm currently on the 99th spot on the leaderboards).

Hope it gets fixed

**Comment by resepignev** [comment]
For some strange reasons it's working now. I'll reopen it if occurs again.

**Comment by resepignev** [comment]
And it's back .-.

**Comment by KyloCode** [comment]
What's missing from yours? 
![5icn5jy 1](https://cloud.githubusercontent.com/assets/1189775/7266820/d3b23082-e875-11e4-8017-53cb5e0bcb73.png)

**Comment by resepignev** [comment]
Wot? 
Sometimes it doesn't appears, sometime it does.
It's really weird!
Well, the I can't help myself :/
can be closed...
