### ISSUE TITLE
Players are not launched by tnt

### ISSUE THREAD

**Issue by Vobaseball** [Avicus/Issues#491]
On the scrimmage servers, while testing out an Icarus, I noticed that players on your own team are not launched by tnt, therefore breaking icaruses. It appears that players get launched, then teleported back for some reason.  https://youtu.be/rTSik94_k3g

Grabbed a video for you... Idk really if you need it but whatever :P

**Comment by Vobaseball** [comment]
Can confirm this on more than one map

**Comment by Vobaseball** [comment]
It appears that players get launched, then teleported back for some reason..

**Comment by Vobaseball** [comment]
Sorry for the spamming of comments, but I've been finding out things. TNT only launches yourself, not other teammates...Which kinda defeats the purpose of icaruses.

**Comment by Vobaseball** [comment]
https://youtu.be/rTSik94_k3g 

Grabbed a video for you... Idk really if you need it but whatever :P

**Comment by ParaSpider** [comment]
I think the hacking plugins should be disabled on scrim and tournament servers tbh, that's what refs and officials and mods are for

**Comment by thekeenant** [comment]
This might be present, but closing due to our inconsistency with anti cheat plugins and what not. Likely fixed.
