### ISSUE TITLE
Servers Display /100 instead of /(number of players allowed in a game)

### ISSUE THREAD

**Issue by Vobaseball** [Avicus/Issues#492]
http://imgur.com/Mv1vBTr

Don't know if this is intended, but showing the number of spots free in a game would probably be better. Just lock this if I'm being dumb :P

**Comment by ParaSpider** [comment]
Probably intended, it lets you know if you can join as in spectate. Doesn't necessarily mean that it should let you play the match, but I'll label this as an enhancement since it makes more sense.

**Comment by Tanpiku** [comment]
Seems fixed
