### ISSUE TITLE
CTW all time leaderboards are not displaying correct values

### ISSUE THREAD

**Issue by SweetMango** [Avicus/Issues#496]
The weekly and monthly leaderboards for Capture the Wool seem to be working fine, however the "All time" tab isn't displaying the correct statistics. Each column is displaying much lower values than the ones displayed on the weekly and monthly tabs. As far as I can tell this is only an issue for Capture the Wool.

**Comment by KyloCode** [comment]
Looks like it's right to me?

**Comment by KyloCode** [comment]
Scratch that, yeah it looks a bit weird.

**Comment by Aki35** [comment]
I think the statistics are finally working.

**Comment by swivr** [comment]
Magic?

**Comment by Aki35** [comment]
Kylo, you probably won't believe me, but when I commented 11 days ago, it was working fine. I just checked again today and it's not working again. I for one know that I'm supposed to be on the leaderboard, but I am not. My monthly score is higher then some of the All time scores and I still couldn't find my name. Hopefully you believe me :p. Also something interesting to note, under my profile, only thr weekly and monthly value is shown for CTW.

**Comment by Aki35** [comment]
Something interesting to note, it seems to be working now, but I think that ot may break again sooner or later because this is the pattern I have noticed before. As of now I'm almost certain it works, but it could easily break again of it follows the same trend. Another note is that the All time leaderboard fot ctw appeared on my profile recently as it hasn't been there before.

**Comment by Aki35** [comment]
![webpage_20150914_102926](https://cloud.githubusercontent.com/assets/12650080/9861039/a08213ee-5acb-11e5-9a8e-d2a6b57fe57d.jpg)

@thekeenant 

So I've been checking up with this issue and I'm not quite sure if the all-time leaderboard is working now. I've been using my profile as reference and I dissapeared from the all-time leaderboards. In my profile the all-time leaderboard showed up, but it dissapeared again. I've narrowed this issue down to 2 things. Either my profile is corrupted or the all-time leaderboard is still broken. I haven't really got the chance to look in detail if the values of the players on the all-time leaderboards have changed.

**Comment by rilomilo9** [comment]
Fix this. My walls stats have never updated. One week I remember I got 50-ish wins and it said 21. I am not over exagerating, also my kills were a bit off :P

**Comment by thekeenant** [comment]
@rilomilo9 Yes sir

**Comment by rilomilo9** [comment]
@thekeenant :P
