### ISSUE TITLE
You can't teleport as spectator when you join a team

### ISSUE THREAD

**Issue by ViceWatercolour** [Avicus/Issues#498]
If the match is, say, 20 seconds in, you can't teleport to people if you ran /join. It thinks you're in the middle of a match and you lose your teleportation/compass perms.

**Comment by thekeenant** [comment]
Testing fix tonight.

**Comment by Aki35** [comment]
I thought I might add on to this issue as the one I discovered is somewhat related.

Once you join a team, the compass teleporter doesn't work as well.

**Comment by thekeenant** [comment]
Yup @Aki35, that included. Fix made, will be in next release!
