### ISSUE TITLE
Some Iron blocks in Rendevous II cannot be broken because they are part of spawn

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#500]

**Comment by Tanpiku** [comment]
Guess https://github.com/Avicus/Issues/issues/393 didn't work.

**Comment by Aki35** [comment]
Accorsing to steven5703, this was fixed in the "Map Modification Request" post. Requesting topic to be closed/confirmed.

**Comment by Tanpiku** [comment]
Alright, thanks @Aki35
