### ISSUE TITLE
You crash when someone with a long name joins the server

### ISSUE THREAD

**Issue by Tanpiku** [Avicus/Issues#503]
![](http://i.gyazo.com/c8f27d68da6b24df2036737289bccc65.png)

I think that's the issue? Since the max shows 16 on the error (which is the maximum amount of letters for a Minecraft name), the recent change for tab menu colors caused a crash in 1.8 where if you join, and someone with a longer name joins, it disconnects people. Due to color codes being counted as characters, someone with 16 characters added on with coloring (17 or 18 maybe) characters will be there, crashing you. Gathered info from Bukkit forums sources.

https://bukkit.org/threads/internal-exception-java-io-ioexception-received-string-length-longer-than-maximum-allowed-18-16.151343/ Bobcat's post.

**If it happens to me it happens to others. I cannot get through without crashing.**

**Comment by Tanpiku** [comment]
Confirmed for it happening to other people.

**Comment by Evocal** [comment]
Watch out guys I'm running free

**Comment by KyloCode** [comment]
Hmm, tested this with evo, weird.

**Comment by KyloCode** [comment]
Guess I'll wait until 1.8 for colors.

**Comment by Tanpiku** [comment]
pls revert your commit

**Comment by KyloCode** [comment]
It was reverted yesterday.
