### ISSUE TITLE
World chunk in embers 1

### ISSUE THREAD

**Issue by Awesomerp** [Avicus/Issues#505]
Yup, there's a world chunk in embers 1. (Please note i broke my bridge after so no-one would come across it and i also did not mine any ores etc (i only broke a tree )
![2015-04-26_15 06 54](https://cloud.githubusercontent.com/assets/11773960/7337587/45908816-ec27-11e4-9b87-5b38f8d5f166.png)
![2015-04-26_15 06 56](https://cloud.githubusercontent.com/assets/11773960/7337588/459488d0-ec27-11e4-9233-8d2a98d1b488.png)
![2015-04-26_15 07 05](https://cloud.githubusercontent.com/assets/11773960/7337590/45a1c39c-ec27-11e4-9ccd-05412aa163fd.png)
![2015-04-26_15 07 16](https://cloud.githubusercontent.com/assets/11773960/7337589/45a0753c-ec27-11e4-8999-f4dbdc450f0d.png)
![2015-04-26_15 07 19](https://cloud.githubusercontent.com/assets/11773960/7337591/45ab5f6a-ec27-11e4-9308-74765135d8ba.png)

I have already notified a member of staff, but i decided to post this on github in order for it to get noticed and therefore removed quicker

**Comment by resepignev** [comment]
Coordinates would help to fix this issue faster. Wasn't there a suggestion of build limits around the map (not only heightlimit)?

**Comment by Tanpiku** [comment]
We need coordinates + boundaries come into play with fixing these anyway
