### ISSUE TITLE
Add regions to prevent standing in front of wool

### ISSUE THREAD

**Issue by Awesomerp** [Avicus/Issues#506]
On some maps, such as justice III, you can stand in front and in the wool spot and consequently a player can bring the game to a standstill. Add regions 1 block around all wool placement areas which teleport players out to stop this?

**Comment by Tanpiku** [comment]
Good feature request, I'll let it stay

**Comment by Tanpiku** [comment]
@Avicus/map-developers Who wants to do this fun task? :smiley:

**Comment by AmazeModerating** [comment]
@Tanpiku Me! Will commence task once I arrive home.

**Comment by tanpara** [comment]
Done.
