### ISSUE TITLE
Bought sound, activated it, then mysteriously disappeared... credits gone

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#508]

**Comment by KyloCode** [comment]
It means it activated, it won't appear in your item chest.

**Comment by DaFrozenBlaze** [comment]
But I have no sound... it doesn't even work... Enderdragon

**Comment by resepignev** [comment]
I would love it if all sounds are staying if you unlock them. Like you can always switch between them without spending credits over and over again. But then they should cost more, like 5000-6000 credits for the first one...

**Comment by KyloCode** [comment]
That's how it works @resepignev . I'll look into your particular case if you email me at info@avicus.net @DaFrozenBlaze

**Comment by resepignev** [comment]
:O Now I'm excited! Thank you for informing me!
