### ISSUE TITLE
Map Info about the Hub/Lobby

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#511]
Heeya,
I saw that if you go on the games site, you can click on the Lobby/Hub map, but you get an error page.
https://avicus.net/maps/FieldsOfGreen
Suggestion for fixing it: You aren't able to click on it or if you are on the site of the map, only the creators and contributors are shown.

**Comment by Tanpiku** [comment]
The maps site is not complete, so disregard any errors for now.
