### ISSUE TITLE
Can't bridge on Castle Adventure [TM]

### ISSUE THREAD

**Issue by NotalAvic** [Avicus/Issues#512]
I was on green. When I tried to bridge
http://gyazo.com/264ce38cc55252a75125346b781884f2
this shows up

**Comment by Tanpiku** [comment]
@jozzmcozz

**Comment by jozzmcozz** [comment]
Should be fixed now.

**Comment by Tanpiku** [comment]
Entry regions wouldn't fix building

**Comment by jozzmcozz** [comment]
I know that, I fixed that issue after Mango comitted. Awaiting another push.

**Comment by Tanpiku** [comment]
Oh, thanks then :P
