### ISSUE TITLE
Tagging a Staff Application resets the post timer.

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#516]
Heeya,
I posted my staff application around 16 minutes ago and it got the reviewing tag around 10 minutes later. Now the timer got resetted.
Pictures: 
![](http://i.imgur.com/oew9Uqd.png)
![](http://i.imgur.com/GxZrxEK.png)
![](http://i.imgur.com/RYQochU.png)

**Comment by KyloCode** [comment]
Yup, that's when it was updated.
