### ISSUE TITLE
Unable to connect to avicus.net. Server side issue!

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#518]
Hi, I made this issue a couple of weeks ago but it got the response of being on the client side: https://github.com/Avicus/Issues/issues/427

I have looked at hundreds of troubleshooting guides, carried the stuff out but nothing has changed I still can't access it.

I have noticed several other pplayers can not connect for the same reasons and get the error ERR_CONNECTION_TIMED_OUT after waiting for a long time for the page to load.

This issue began when the OMEGA update came and I believe that some website/network settings may have been altered/changed meaning several other users could not access avicus.net

I hope this issue can be sorted soon as it is a rather large inconvenience on trying to manage a tourney team over 3G. Thanks,
Icy

**Comment by Reqiz** [comment]
Same here! Thanks for pointing out this issue. I'm having problems trying to connect to the Avicus website but I can connect to any other website.

**Comment by KyloCode** [comment]
The only change was our switch to HTTPS, so I'm guessing a firewall or weird network settings on your end is stopping the connection. It's pretty evident that it is client side, I'm not sure where you got the idea it wasn't... You can contact me via email if you want some help diagnosing the issue. If I'm wrong and it is server side, then I'll open it up, but it's too much to troubleshoot here.
