### ISSUE TITLE
Ability to craft colored wool in CTW

### ISSUE THREAD

**Issue by SweetMango** [Avicus/Issues#519]
A handful of CTW maps contain flowers and cobwebs. In some cases, this allows players to craft colored wool which can then be placed at the monument. 

To prevent abuse I've removed the flowers but I was wondering if it's possible to disable it somehow. This would mean people can include flowers and cobwebs in their maps without it being abused.

**Comment by Tanpiku** [comment]
I suggest a disable-drops module so certain things don't drop at _all_, it's kind of restrictive to not use plants or wool or webs or anything out of that material in design

**Comment by Tanpiku** [comment]
I propose making webs drop webs (not string) and flowers only dropping inc sacs.

**Comment by Aki35** [comment]
Silk touch swords maybe?

**Comment by DaFrozenBlaze** [comment]
I think on Arizona you can make Green dye( Cactus) if I'm not wrong

**Comment by thekeenant** [comment]
Added crafting module to disable this in next update.
