### ISSUE TITLE
Hub glitch

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#520]
It makes the Avicus like a survival server. Watch:
https://youtu.be/ni7u-LMf1Y0

**Comment by KyloCode** [comment]
What is "it"?

**Comment by Tanpiku** [comment]
Provide a brief summary of the issue, the title will help us get an idea of what we'll be looking at. 
Be clear in your description.

**Comment by resepignev** [comment]
Well, I was in the hub.
So, due a glitch or a bug in some plugins, i guess, you could break anything in the hub. All player names were white in the tab list and the books, enderchest, playerheads didn't worked. They were just normal renamed items.
It felt like the hubs had no plugins at all.
Maybe it happened as something was changed or added to the plugins/library.
However the hub restarted and everything was fine then and it didn't happened again.
So close it for now.
