### ISSUE TITLE
modify_drops isn't working properly

### ISSUE THREAD

**Issue by Tanpiku** [Avicus/Issues#521]
The YAML module: It works for only one block. See Enoki; I have multiple things to be changed into mushroom drops but it still doesn't work with dirt, mycel, cobble, obsidian, or other blocks. Only clay.

Priority because needed for tournament ASAP.

**Comment by KyloCode** [comment]
You can't have the duplicate trigger types for a region. I'd create 7 separate regions.

Big drawback to the current YAMl parser.

**Comment by Tanpiku** [comment]
Still not working

**Comment by KyloCode** [comment]
I made a bad hacky fix that may have broken things on other maps... But the good news is that this works.

**Comment by Tanpiku** [comment]
Works great now, thank you :heart:

**Comment by Tanpiku** [comment]
Doesn't work with TNT D;

**Comment by KyloCode** [comment]
TNT isn't in the YAML?

**Comment by Tanpiku** [comment]
No, using TNT against it makes the drops normalized, not to what they're set to.

**Comment by KyloCode** [comment]
Yeah modify drops is for block break events...

**Comment by Tanpiku** [comment]
=(
