### ISSUE TITLE
[CTH] Bugs and some kit updates

### ISSUE THREAD

**Issue by izjust4fun** [Avicus/Issues#522]
Bugs:

~ Players can hit others extremely fast. (Can literally kill a player in a second)
~ Takes an extremely long time to respawn..(Could be just me)

Kit changes:

Demo~
TNT and grenades need to do less damage.

Ninja~
Players on 1.8 from the other team can see your name tag while you're invisible.

Fisherman~
Rod needs a short cool down.
Also if possible, have it so that if a fisherman tries to reel you into the void you will be tp'd back to the last block before you were reeled in.

**Comment by resepignev** [comment]
I can confirm these bugs. I also go video evidence (just has to get uploaded).
I also agree with the kit changes.
Demo: Grenades deal around 9 hearts damage if you throw them directly on a player.
FIsherman: definitely needs a cool down, you can spam reel players and it's really annoying.
And I also agree with the safe void reeling. For example on the map Starburst, you can stand next to the path that connects the middle with the spawn and reel players out of their spawn. If you then jump down into the void you can farm credits all day(match) long.

**Comment by IcedCode** [comment]
Disagree that Demo is to OP, I believe it's balanced and it takes some skill to use it well.
To add to this I suggest that you have a feature like in Avicore V1.0 where you could not remove armour in CTH matches (Stop abuse of ninja)

**Comment by Tanpiku** [comment]
First bug already reported somewhere.
Second bug is your side.
Ninja issue is a thing we aren't planning to fix at this moment.
As well, suggestions aren't for here and issues should be listed separately, not compiled.
