### ISSUE TITLE
Two of the same players in the database?

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#524]
![screen shot 2015-05-05 at 13 43 48](https://cloud.githubusercontent.com/assets/7715330/7471915/e103c4be-f32c-11e4-90f1-c616ff3f6426.png)
![screen shot 2015-05-05 at 13 44 16](https://cloud.githubusercontent.com/assets/7715330/7471916/e3cb7d86-f32c-11e4-9126-d839fef61bdc.png)

**Comment by KyloCode** [comment]
Yeah, resolved.
