### ISSUE TITLE
New shot colours - two numbers show up.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#525]
![screen shot 2015-05-07 at 09 12 51](https://cloud.githubusercontent.com/assets/7715330/7510147/71ea690c-f499-11e4-858b-eaf3c3f430ad.png)

**Comment by pavilion99** [comment]
I pushed a fix, we'll see if that helps anything

**Comment by Vobaseball** [comment]
Still like this

**Comment by KyloCode** [comment]
It wasn't live yet.

**Comment by pelpelajax** [comment]
Fixed
