### ISSUE TITLE
CTW Map YML/Map issues

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#526]
Dreadlock
No Arrows in Wool Room Chest and you get supplied a Punch 1/2 Bow (forgot which enchant) and you can only shoot it once because of the 1 arrow u spawn with
Lotus: 
The Build Limit (Y Zone) Might be low and you can't reach the chest at the top most part of the Wool Room (On the Balloon thing)
BreakOut:
Players can go into their own wool room and camp
You can cover the water pool you jump into

And more to come (Don't Remove This unless i say u can. I'll try to update this every now and then with CTW map problems)

**Comment by Sethskype** [comment]
Rendezvous II

The Sign asks for Light Blue Wool but you need to place Green (Red Team)
http://gyazo.com/382953dd0f6c1bd5d944fd6ec81d2ad2

**Comment by AmazeModerating** [comment]
Fixed BreakOut, looking into the other issues for you.

**Comment by Sethskype** [comment]
Most of it has been fixed

**Comment by Sethskype** [comment]
http://gyazo.com/78f45308ee4611ab6221906ce9909e70

Can't destroy most of iron block pillars On Taurtis

**Comment by Aki35** [comment]
Probably a YML problem.

**Comment by Tanpiku** [comment]
S'ok
