### ISSUE TITLE
Spectators hitting in-game players.

### ISSUE THREAD

**Issue by ImRaging** [Avicus/Issues#537]
In a castle adventure game, I /join(ed) but was still in the spectating mode. I went over to the pink side of the map and realised that i could hit people on the opposite team. I jumped into the void and that then put me right, but others were still abusing it (when i say 'others' i mean about a third of the players in the game).

The abilities you have when in this mode are: 
-being able to fly
-being able to teleport with the compass
-being able to hit players
-and being able to open chests located on the map.

These are the problems I have encountered, and there may still be more. Please fix asap :P

**Comment by resepignev** [comment]
#532
