### ISSUE TITLE
Allow joining of the gray team with "/join grey" (alias feature)

### ISSUE THREAD

**Issue by Tanpiku** [Avicus/Issues#538]
Considering it is a color spelling used globally outside of America alone, I think that having an alias for the gray team to be "grey" would be great. It's the only color with a different spelling, and even though Avicus is based here it's friendly to other players for convenience so they don't have to conform to American spelling.

**Comment by KyloCode** [comment]
Teams shouldn't have grey as their color really, and really this is such a minor nitpicky thing... -.-
