### ISSUE TITLE
When placing blocks, sometimes it disappears (block lag)

### ISSUE THREAD

**Issue by Tanpiku** [Avicus/Issues#539]
https://www.youtube.com/watch?v=fL7JWK2-SiI Finally a video!

**Comment by KyloCode** [comment]
Oh interesting. So it doesn't happen arbitrarily, but rather when clicking fast and perhaps when the player is right around the block placed.

**Comment by Aki35** [comment]
Even when you don't click fast, block lag often occurs. Let's say if I try to place a block below me on a wall while jumping and only holding right click, (not rapidly clicking) The block usually disappears. At one point, I placed 4 blocks below me and all of them had lagged out.

**Comment by zero9178** [comment]
sry for the bump but I also got a very good example, which is even weirder as it took so long for the server to delete the blocks https://www.youtube.com/watch?v=yTh-uwUYprw&feature=youtu.be

**Comment by Aki35** [comment]
Pardon the bump, I just want to say that this still occurs even after the server host changed.

**Comment by KyloCode** [comment]
Should be fixed now!

**Comment by Aki35** [comment]
Block lag still occurs pretty often for me.

**Comment by KyloCode** [comment]
Might need to upgrade something on your end, the servers have since been reporting no tps drops, I don't think it would be mistaken.

**Comment by KyloCode** [comment]
I'll write something up to log any suspicious server performance issues, but it sounds like it's on your end.

**Comment by tanpara** [comment]
It's not on our end unfortunately :|
