### ISSUE TITLE
Sometimes the server thinks you're a player as a spectator

### ISSUE THREAD

**Issue by Raysty** [Avicus/Issues#540]
I was playing on the DTM map vesper earlier today and I accidentally exited out of minecraft in the respwan screen and when I rejoined I had the stuff as if I was on the blue team and was on the spec platform but I wasn't able to fly even thought in chat I was labeled as a spec. I was also in survival and could place blocks but when I jumped off the edge o try and kill myself I didnt die. This is similar to sethskypes post but we experienced diffre to things    -Raysty              (I will add screenshot when I Can access computer again. I am on my way to a little event)

**Comment by resepignev** [comment]
I can confirm this. It can happen on all nebula maps.

**Comment by KyloCode** [comment]
Definitely tied to #537
