### ISSUE TITLE
Avatars are still broken

### ISSUE THREAD

**Issue by Tanpiku** [Avicus/Issues#541]
![](http://i.gyazo.com/0f25645f84b55fd0684bd6acec3263a3.png) I think it'd be worth it to maybe make our own avatar site by now, considering the last 3 haven't worked.

**Comment by KyloCode** [comment]
Seems to work? http://i.imgur.com/qvDbyej.png

Who was it?

**Comment by Tanpiku** [comment]
JustBudah
