### ISSUE TITLE
SG07 has multiple chests you cannot open

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#550]
http://imgur.com/hqMZL63
There are more chests like these
This is just one of them on the Brick Bridge

**Comment by Tanpiku** [comment]
The map makers weren't really smart with this... I doubt we'll be able to fix all of the chests, but if you could give us coordinates for each one we'll fix them. :)

**Comment by Sethskype** [comment]
They are all on the same bridge
It's a brick bridge

**Comment by AmazeModerating** [comment]
They all open? I used 1.7 + 1.8 to test this.

**Comment by Tanpiku** [comment]
Probably slab ID thing, not even sure but if it opens anyway, all good.
