### ISSUE TITLE
Juniors have permission to ban.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#557]
![screen shot 2015-05-25 at 19 52 04](https://cloud.githubusercontent.com/assets/7715330/7800571/923c38ca-0317-11e5-96db-32716cbf1c47.png)

**Comment by Tanpiku** [comment]
Privately mentioned this to mango.

**Comment by javipepe** [comment]
This was already fixed, just so if you wish to close the issues that have been resolved.

<img src="http://i.imgur.com/yeS5UYT.png">

**Comment by pelpelajax** [comment]
Alright, thank you @javipepe
