### ISSUE TITLE
Avicus Website needs a better/more accurate search bar

### ISSUE THREAD

**Issue by Sethskype** [Avicus/Issues#558]
Note: Pictures were taken in my phone
So
I tried to search up the "Map Feedback Thread"
Pic: http://imgur.com/VNuQM8N
I copied the whole title and put it in search bar

But when I searched it up, other threads came up 
http://imgur.com/RKmKxbk

Here is my theory on why this is happening:  The Searched words are being scanned separately 
The threads that came up have either Map, Feedback, or Thread in either the replies or the Title. So instead of this, the words should be searched together.

Other Possible Evidence: http://imgur.com/GSBSrgM

Picture shows me putting random letters then 2 map names and the 2 maps came up and the random letters didn't do anything. Instead of this, the search should find topic titles NAMED habsbnejtkflcoxyG Opulence Maisosen instead of them having that specific word in their replies

**Comment by KyloCode** [comment]
You're correct on how it works. This is intended, and explained here. https://avicus.net/forums/06b9faaa1
