### ISSUE TITLE
When on a match with gives team-specific inventories, you can glitch in more items

### ISSUE THREAD

**Issue by Awesomerp** [Avicus/Issues#559]
http://gyazo.com/716371a49b7cdfc5051efe691786c0df
A gif showing it (because it was easier to uplaod) 
If a player goes out of the region and gains items, goes back into it then back out, he will get more of those items.

**Comment by AmazeModerating** [comment]
Still buggy. Gives default coloured leather, which is very confusing. 

Investigating a potential fix.

**Comment by AmazeModerating** [comment]
Deployed potential fix... looks good so far. Made changes to the actual spawn & YML.
