### ISSUE TITLE
Dyeing Armor Blue.

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#560]
In maps that have enchanting tables and include a blue or shade of blue as a team, it is possible to dye armor with the lapis given in the inventory loadout to match the blue team giving the team that isn't blue an advantage. Examples include Clearmont II.

Basically the solution would be to allow enchanting without lapis (If that's even possible in 1.8) or remove blue teams.

**Comment by Aki35** [comment]
Basically, the solution would be to change the team colors or allow enchanying tables to be used without lapis.

**Comment by thekeenant** [comment]
Added auto lapis module in next update.
