### ISSUE TITLE
Outdated Map Authors

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#562]
Not too much of an issue but, it deserves some small attention. Many maps made have signs that have an old player's name. Example: Darkiur_ made maps such as Alpha Complex but, the credit goes to one of his old usernames (Astronis) It would however be a big hassle to get a new download just for changing a sign though so, I have no solution to this.

**Comment by javipepe** [comment]
Just remove the signs and make authors UUID based?

**Comment by Tanpiku** [comment]
We have this feature, but we'll need to update every single map. Hopefully someone can come up with a script

**Comment by AmazeModerating** [comment]
@Tanpiku I'll look into a script which would automatically change the authors > UUIDs without doing it all manually.

**Comment by Tanpiku** [comment]
@AmazeModerating We also would need it to update everything else like how regions and loadout are used

**Comment by AmazeModerating** [comment]
@Tanpiku Got a general idea how to convert... will play around when I have some free time on my hands

**Comment by KyloCode** [comment]
UUID coming soon.

**Comment by Aki35** [comment]
Found another problem. On the website pages to review a map, a few of the outdated creator names are displayed there as well. I really do not know of a potential fix, but I just wanted to point out that it will need to be fixed when the map pages are publicized.

Ex: https://avicus.net/maps/Arizona
(Darkiur_ is now Skyadia)

**Comment by Tanpiku** [comment]
It goes in hand with YML

**Comment by tanpara** [comment]
Will wait for the UUID feature

**Comment by thekeenant** [comment]
Uuid was added I think
