### ISSUE TITLE
Donors can't join game

### ISSUE THREAD

**Issue by ImRaging** [Avicus/Issues#564]
So, by being a donator, you are able to join any game freely. However, when i tried to join, this happened:

![1](https://cloud.githubusercontent.com/assets/11795385/7878796/42639a96-05e2-11e5-91e7-863a899b4656.png)

Problémo.

**Comment by Aki35** [comment]
There is also a maximum limit that includes all players including donators. This only happens when the game is extremely packed. It's not an issue and it was meant to be like that however, I believe it is to keep a good gameplay.

**Comment by Tanpiku** [comment]
^
