### ISSUE TITLE
Knockback upon spawning

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#565]
First off, I'm not sure if this issue just pertains to me due to ping but, after you die in Nexus and I think CTH while being knocked back, when you respawn, you will be flung in one direction right after. It gets kind of annoying and I would provide video if I could but unfortunately, my computer is not strong to record. Perhaps I could have someone record me sometime.

**Comment by kycrafft** [comment]
Pretty much sums it up.

**Comment by thekeenant** [comment]
Fixed with next update
