### ISSUE TITLE
[Walls] Please nerf poseidon

### ISSUE THREAD

**Issue by kycrafft** [Avicus/Issues#570]
I don't know if I should be posting this here, but it's really OP. Poseidon is almost invicible in water, as long as you have armor on and if you manage to fight them on land, they jump into the water and pull you in with the fishing rod. I mean, it's a good kit idea, but it's abused so often.

Once again, if this is better on the forums, I'll put it there.

**Comment by Tanpiku** [comment]
Sorry, please post in server feedback.
