### ISSUE TITLE
About Page Editing: Error 404

### ISSUE THREAD

**Issue by Roboticboy** [Avicus/Issues#571]
When editing your about page here:
![image](https://cloud.githubusercontent.com/assets/6438467/7997611/fe425840-0afd-11e5-8acc-62e5726f144c.png)

This happens:
![image](https://cloud.githubusercontent.com/assets/6438467/7997617/1602a642-0afe-11e5-83fa-08a7e256c1ee.png)

**Comment by Tanpiku** [comment]
https://github.com/Avicus/Issues/issues/554
