### ISSUE TITLE
[Nebula] Some tools drop and quickly clog up inventory space

### ISSUE THREAD

**Issue by kycrafft** [Avicus/Issues#576]
This issue was brought to my attention by some players. Maps that have tools in their spawnkits (ex: shovels on Zalidor and shears on Taurtis) will drop upon death. These will tend to clutter players' inventories. I was wondering if tool drops could be removed.

**Comment by Tanpiku** [comment]
Both are disabled

**Comment by AmazeModerating** [comment]
Disabled all weapon drops for Destroy the Monument maps. Will do the same for the maps kept in Storage (at a later date).
