### ISSUE TITLE
[The Walls] Bug

### ISSUE THREAD

**Issue by Jhon1409** [Avicus/Issues#577]
Uh , hello, I want to put here a case in The Walls , was a bug happened the day yesterday , what happened was this: Well, first of all I started as a game rule nothing out of the ordinary , in the end, my team the win and there began the bug was like a message loop " Your team won " and it was very strange , I never thought that this would affect bug official stats from the server , I thought it was just a visual bug or I know , but in the end when I had already quit the game I realized this, I could not report yesterday about personal problems but here it is, this is proof of the bug . http://i.imgur.com/0xPptPO.png Thx for you time :)

**Comment by KyloCode** [comment]
That's a lot of wins.
