### ISSUE TITLE
Xp Glitch. [Nebula Dtm]

### ISSUE THREAD

**Issue by pizza334** [Avicus/Issues#580]
This issue was alerted to me by a user stating he kept his xp from last game. Other players also reported this. The Previous map was Alpha Complex and the Current map where the glitch took place being Sector Six
![c706e14efafbee433ed66a9b7d11d0083d40b2fa8e1727e843 pimgpsh_fullsize_distr 2](https://cloud.githubusercontent.com/assets/6341732/8299202/2438e5d2-196d-11e5-9efc-6bd3aaeda3b6.jpg)

**Comment by pavilion99** [comment]
I wrote some code that will (hopefully) fix this issue; please wait for Kylo to apply changes.

**Comment by Aki35** [comment]
#555

**Comment by thekeenant** [comment]
Fixed with next update
