### ISSUE TITLE
[Web] Tabs in profile don't highlight correctly

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#582]
![image](https://cloud.githubusercontent.com/assets/6472584/8360561/856e75c2-1b3b-11e5-9557-74a562d817ae.png)
In this picture, it is highlighted like it's on the about page, but really it is on the stats page.
![image](https://cloud.githubusercontent.com/assets/6472584/8360591/ac8efa32-1b3b-11e5-8bd5-fbff392ac77a.png)
Same with this picture, but instead it's highlighting leaderboards instead of infractions

![image](http://i.gyazo.com/6e652863753c3d464369628491d9c83b.gif)
Here is a gif I made of me clicking all of the tabs

I'm not really sure what to call it when the tabs indicate what you're viewing (like how it stands out from the other non-selected tabs), so I'm just calling it highlighting.

**Comment by KyloCode** [comment]
Yeah, noticed this a while back, fixed in a web update I'll push soon.

**Comment by AustinLMayes** [comment]
@swivr This is still an issue.

**Comment by swivr** [comment]
Yeah, just not pushed. Intended on it earlier, but its being bundled with a few other large updates.
