### ISSUE TITLE
Loadouts applied during end of match

### ISSUE THREAD

**Issue by dentmaged** [Avicus/Issues#587]
If you die, then respawn when the game has ended, the kit will still be applied.
![Screenshot](http://i.imgur.com/f2iTOMl.jpg)

**Comment by thekeenant** [comment]
Testing fix tonight.

**Comment by dentmaged** [comment]
Thanks @thekeenant!

**Comment by thekeenant** [comment]
Fix made, will be in the next release of Avicore!
