### ISSUE TITLE
Spectator Glitches (various)

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#590]
https://youtu.be/TW3SM7KS7LE

I was a spectator and spawned with a regular player loadout. I couldn't fly either and I found out that you could randomly place blocks on the spectator spawn. When I'm looking at the other player, I realized he had also had the same issues as me. It seems this issue happens only sometimes as other players didn't spawn with the loadout.

**Comment by resepignev** [comment]
#532 ?

**Comment by Tanpiku** [comment]
I'm keeping this one open
