### ISSUE TITLE
Unable to type % character in chat

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#592]
When you type the % character in chat it does not say the message but says this instead:
![2015-07-08_12 42 04](https://cloud.githubusercontent.com/assets/7426927/8569500/37918e72-2570-11e5-9398-07e5ec9f451b.png)

The following video at: https://youtu.be/5qc83AL0Ols?list=PLAF3anQEEkzREsHA8yZzVhc3_GHcPnqxR (16:50) has a very similar issue involved and he explains how to fix it.

**Comment by IcedCode** [comment]
As a sidenote I think this issue may have been created when Team Chat was implemented due to the nature of the issue & how I had not seen this issue prior to it being implemented into the servers.

**Comment by resepignev** [comment]
it's fixed ;)

**Comment by javipepe** [comment]
Fixed :smiley:
