### ISSUE TITLE
[Website] Typo on Games Page

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#593]
![webpage_20150708_074802](https://cloud.githubusercontent.com/assets/12650080/8577661/ef6c3f68-2545-11e5-9351-8f8cfa927a2c.jpg)

It says expore instead of explore.

**Comment by Tanpiku** [comment]
What better way to partake in avicus none other than exporing?

**Comment by KyloCode** [comment]
Microsoft Exporer

**Comment by IcedCode** [comment]
This has been fixed. Someone should close this

**Comment by thekeenant** [comment]
yes
