### ISSUE TITLE
[Walls] YML fails to give non-kit loadouts

### ISSUE THREAD

**Issue by Polar-Express** [Avicus/Issues#596]
Yml settings to allow a load-out to be given via entering a region on the walls game mode does not work. Tried with Potion effects and items, and no items of effects were applied to the player on entering or leaving a region.

**Comment by Tanpiku** [comment]
I believe this is more of a feature request since I think it only works with interact and kill reward flags anyway, at least when I tested.

**Comment by Polar-Express** [comment]
Looking at the yml docs, the triggers, we're listed as available on all game modes, so that's why I posted as an issue.

**Comment by Tanpiku** [comment]
Ah, fair enough.

**Comment by thekeenant** [comment]
Fixed in next update Avicus/Avicore@0d32c67580d95c7724844ba8ff7e4f6f345ecf15
