### ISSUE TITLE
If you click on reports multiple times, you could get kicked for spam.

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#599]
![screen shot 2015-07-15 at 21 52 57](https://cloud.githubusercontent.com/assets/7715330/8708383/e03bbdd8-2b3b-11e5-90ac-84d478c5178b.png)

**Comment by KyloCode** [comment]
Well it is repeating a command 5 times in like 5 seconds. The same happens if you type it out. It could be lessened if we want to have more activity moderating spamming - something to discuss in staff chat.

**Comment by pelpelajax** [comment]
@KyloCode Why would a command be condisered spam? Only you see it, so it doesn't do any harm to others?

**Comment by KyloCode** [comment]
It can cause stress to the servers. This here though is a bit too picky.
