### ISSUE TITLE
Vanishing Trail Purchase

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#601]
![2015-07-18_14 13 14](https://cloud.githubusercontent.com/assets/7426927/8767470/d8dd48be-2e55-11e5-8df6-ef1e1f39afb9.png)

Trail doesn't show, it appeared in my backpack but when I used it, it vanished. Proof of purchase above. I've set particles to on when I bought it and nothing showed still :/

**Comment by KyloCode** [comment]
You may have particles disabled in your Minecraft settings.

**Comment by IcedCode** [comment]
I still see blood if I turn avicus particles on

**Comment by Sethskype** [comment]
The portal trail works for me. Try standing still until you see purple dots like the nether portal

**Comment by swivr** [comment]
It's one of the least flashy trails, I might up the particle count. Otherwise, yeah it seems to be working. Ask others if they see it.
