### ISSUE TITLE
/stafflist says there are 1 staff online when no staff are online

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#602]
^^^^^^^^^
![2015-07-19_20 41 52](https://cloud.githubusercontent.com/assets/7426927/8767496/caeb94bc-2e56-11e5-9acb-fc9c6e75dd46.png)

**Comment by IcedCode** [comment]
This issue no longer persists with the new /stafflist command. Might aswell close it

**Comment by javipepe** [comment]
Yep, thanks
