### ISSUE TITLE
Trails Disapearing In-Game

### ISSUE THREAD

**Issue by Upsoar** [Avicus/Issues#605]
This is a minor glitch, but one that bugs me nonetheless. Trails that I have equipped in the lobby will stay with me until my first death in a match. I'm not sure if trails are SUPPOSED to stay with you in matches, or if they're just for the lobby (It'd be neat to see them in-game). 
If trails are lobby only : Trails carry over to matches 
If trails are supposed to be in-game : Trail disapears after first death in game

**Comment by Aki35** [comment]
I think trails would be bad in-game. It would give away the location of a player.

**Comment by tanpara** [comment]
This is client side.

**Comment by Upsoar** [comment]
It's not client side. The only reason I noticed it was because other players pointed it out to me.

**Comment by tanpara** [comment]
It's client side when it happened to me and others.

**Comment by Upsoar** [comment]
![image](https://cloud.githubusercontent.com/assets/13409196/8995031/8a5a0f42-36d4-11e5-9361-c251dffea92e.png)

**Comment by keenanthompson** [comment]
Confirmed

**Comment by thekeenant** [comment]
Looking into it!

**Comment by javipepe** [comment]
State of this?

**Comment by thekeenant** [comment]
Persistent!
