### ISSUE TITLE
You can't archive your own topics.

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#606]
Any user can see the "Archive" checkbox under the post reply text field. When clicked, posting fails with a "Unable to find linked reply." error. Either users should be able to achieve their own discussions, or they should not be able to see the check box.

**Comment by kycrafft** [comment]
I'm pretty sure it still archives the reply, even if it says you can't find the linked reply.

**Comment by thekeenant** [comment]
@AustinLMayes also assgined hehe.
