### ISSUE TITLE
Venomous Map Glitch

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#607]
Hi. I was told to report this certain map glitch here so here goes.

On Venemous DTM/TDM, the map happens to be asymmetrical. On the hills that go up, it is possible to jump onto Cyan's spawn while on the Lime team, but a Cyan player cannot jump onto the Lime team's spawn. It can cause some unfair gameplay. I don't know if the map has to be rebuilt or something, but I just wanted to get this out there. Thanks!

**Comment by tanpara** [comment]
It's lasted 3 years, I don't think it's major enough to really edit the map as that'd cause more problems than it'd solve. Both teams can still win.

Still an issue, but it's not really a problem I see for now.
