### ISSUE TITLE
You can break through your post limitations with font sizes

### ISSUE THREAD

**Issue by ViceWatercolour** [Avicus/Issues#608]
Note: ALM didn't do this. I did an inspect element.

![](http://i.gyazo.com/d4f354b366b17987eb353bcc3aa37b38.png)

**Comment by swivr** [comment]
well gg

**Comment by AustinLMayes** [comment]
@tanpara I actually did do this the first time, I just went back and fixed it. :tada:

**Comment by thekeenant** [comment]
Casually assigning @AustinLMayes to this.
