### ISSUE TITLE
/hub brings you to MapDev if lobby is present

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#609]
If a lobby is on server mapdev, doing /hub brings you to the mapdev server. It was an easy fix but something worth noting.

**Comment by tanpara** [comment]
This is so easily preventable tho, this is more our thing and not kylo's

**Comment by AustinLMayes** [comment]
@tanpara but that is totally how the logic should _NOT_ work. /hub should pull from a set list, not based on map.

**Comment by swivr** [comment]
This is a bug. Fix pushing soon.
