### ISSUE TITLE
You Can Die In The Lobby

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#610]
![Death](http://puu.sh/jiqOY/f961ed237a.png)

Damage is somehow enabled now Even though damage amount isn't sent to the client, you will eventually die.

**Comment by tanpara** [comment]
@steven5703

**Comment by swivr** [comment]
Something to do with the world/regions itself?

**Comment by steven5703** [comment]
@tanpara Did https://github.com/Avicus/Maps/commit/4bdcf32147c9ccf4f4c12f65c46cad163a8c92fd solve this?

**Comment by tanpara** [comment]
Yes, I believe so.
