### ISSUE TITLE
Sometimes server kicks you out of the match saying it's down, but it's not

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#611]
According to players, the server will kick you out of a match by saying it's down, but the server would be in a healthy condition.

Should be typical disconnection message for when the server is "down".

**Comment by keenanthompson** [comment]
When does it kick you? I don't quite understand.

**Comment by ParaSpider** [comment]
No longer occurs.

**Comment by thekeenant** [comment]
Okay :dancer:
