### ISSUE TITLE
Gecko Canopy: No Longer A PVP Arena

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#613]
The PVP arena feature of the sandbox was reverted, but the sign is still there.

![lol](http://puu.sh/jlwdB/a72cf38e85.png)

**Comment by steven5703** [comment]
Fixed in an update I'll push soon

**Comment by ParaSpider** [comment]
Gecko canopy is gone, so this is fine/fixed.

**Comment by thekeenant** [comment]
Okay :D
