### ISSUE TITLE
Credit Bug/Error

### ISSUE THREAD

**Issue by Seuth** [Avicus/Issues#614]
So, I was playing yesterday on SG, and after I won the game and got credits and bought a new badge, I had 6, and then a few minutes later I had -164, no amount of credit gaining will make it go back to normal numbers, and I can't buy anything from the shop. I'm guessing it's a plugin error, but I have no clue how it happened :v

**Comment by tanpara** [comment]
Kudos, you win the award for most strangest bug I've ever seen on here

**Comment by AustinLMayes** [comment]
@tanpara sounds like some database lag/duplicate operations to me.

**Comment by javipepe** [comment]
@AustinLMayes Yeah, we're probably handling them inappropriately, will look into it

**Comment by Seuth** [comment]
After a few days nothing has happened, so it's probably something with the database like @AustinLMayes said
