### ISSUE TITLE
Players Keeping Inventory, Abbilities

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#615]
## Steps to Reproduce ##
1. Join a match, play a bit.
2. Die
3. Leave
4. Rejoin that server anytime before a restart.
5. You are now spectating, you can't fly, have your inventory from when you logged out, and can place blocks. You also have all spectating permissions.

Here's a picture after I placed some wood in the spectator spawn, it is not client side.
![image](http://puu.sh/jm3yP/1b7bc4eeb0.png)

**Comment by AustinLMayes** [comment]
@tanpara This is a plugin issue, not a map issue.

**Comment by tanpara** [comment]
:fearful:

**Comment by thekeenant** [comment]
Can't really replicate. There's an NPE fired, but it doesn't seem to do anything. Pushed that fix.
