### ISSUE TITLE
Dev is awfully broken

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#616]
You can't use /hub or /lobby
You can't use /server (any server)
You can't use /go
You can't use/see staff chat (/s) or dev chat (/d)

It's like its isolated from any other server, the only way to get back to avicus itself is to leave the server and rejoin, or to spam and get kicked to hub.

**Comment by AustinLMayes** [comment]
@steven5703 Sounds like the database plugin is having a fit.

**Comment by swivr** [comment]
Just temporary, someone borked it.

**Comment by pelpelajax** [comment]
Starting happening on Official01 too @swivr
