### ISSUE TITLE
If you put an apostrophe in a permanent ban, it glitches. 

### ISSUE THREAD

**Issue by pelpelajax** [Avicus/Issues#617]
If you do that, the ban won't register. All other punishments do work if you use an apostrophe.

**Comment by AustinLMayes** [comment]
Sounds like the reason isn't checked to be MYSQL safe

**Comment by thekeenant** [comment]
Sounds like it, but not the case, strangely.

**Comment by ParaSpider** [comment]
This is fixed.

**Comment by thekeenant** [comment]
Okay :|
