### ISSUE TITLE
Glitch with /kit on CTH

### ISSUE THREAD

**Issue by keller183** [Avicus/Issues#621]
On CTH if you die while you have the kit menu open you are unable to open the menu for the remainder of the round.
EDIT: This happens on Nexus as well.

**Comment by javipepe** [comment]
I don't think I'm actually able to understand your problem, could you please be more accurate and, ideally, provide me with a video?

**Comment by thekeenant** [comment]
Looking into it.

**Comment by thekeenant** [comment]
It works for me. What I did:

1. Jumped off map
2. Opened kit menu
3. Died from void
4. Respawned, did /kit (it worke)
