### ISSUE TITLE
BossBar Issue

### ISSUE THREAD

**Issue by Prodigy4532** [Avicus/Issues#628]
When you have the view of chunks to "4 " in optifine the " Bossbar " disappears .

Images: Render "8" Chunks.
http://i.imgur.com/R15q2A4.png

Render "4" Chunks.
http://i.imgur.com/oejUToD.png

**Comment by thekeenant** [comment]
The boss bar functions by placing a dragon or wither in the distance, barely visible. Setting your render distance too low *will* make it disappear.
