### ISSUE TITLE
Able to break/destroy boats in Spectator Mode

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#629]
^

**Comment by javipepe** [comment]
I think this is client-side, as the placing of lilypads when block placing event is cancelled. Could you test with an alt / another player if the other player does see you breaking the boat to, or if otherwise it's only a visual glitch that it appears as broken to you?

**Comment by IcedCode** [comment]
Ok my and Javi have conducted a joint investigation into this, I have done investigating and it requires 2 listeners to be cancelled. Those listeners can be shown in the code for a very basic plugin that prevents the destroying/breaking of all vehicles which could easily be applied to Avicus Spectator mode.

The code for this basic plugin can be found here: http://pastie.org/10454473

**Comment by ParaSpider** [comment]
I think this should be priority... it's being very gamebreaking.

**Comment by javipepe** [comment]
Dealing with it.
