### ISSUE TITLE
Nebula doesn't appear on my Avicus Profile

### ISSUE THREAD

**Issue by shadowolfyt** [Avicus/Issues#631]
Basically when I go onto my Avicus Profile my Nebula stats don't come up everything else does the Nexus and CTH and stuff everything but Nebula

![image](https://cloud.githubusercontent.com/assets/15405528/10839442/328e8c1a-7f28-11e5-9408-3aaa9894819b.png)

**Comment by IcedCode** [comment]
Nebula is now split into DTM, CTW & TDM. Don't know whether you just play CTW or something.

Also adding to this issue CTH, SG, TDM don't show on my profile even though I have played several games of all of them? (https://avicus.net/IcyCode#leaderboard)
