### ISSUE TITLE
Unread posts and replies give 500 error

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#633]
If you click the unread number next to the thread title (like this)
![image](https://cloud.githubusercontent.com/assets/6472584/11110034/35f935c0-88c5-11e5-8305-fbd3caa6cffa.png)
It will give you a 500 error (http://pastebin.com/vP47ex8m), unless you are viewing the thread for the first time, then it will show you the thread.

Also if you click the "Replies" button on any post it will just be a white screen
Example: https://avicus.net/forums/replies/248340

**Comment by javipepe** [comment]
@thekeenant is working on it :)

**Comment by steven5703** [comment]
This is fixed
