### ISSUE TITLE
Senex I Issue

### ISSUE THREAD

**Issue by xFracTV** [Avicus/Issues#634]
![2015-11-12_19 44 53](https://cloud.githubusercontent.com/assets/8517389/11136640/04131a7e-8976-11e5-9c9e-f55477e3a359.png)

**Comment by IcedCode** [comment]
This occurs on many maps, it is to do with a 1.8 map being used on a 1.7 server. I do not know how maps are imported into the server but it could be to do with that?

**Comment by AustinLMayes** [comment]
Mapdevs are editing maps on 1.8 servers/clients an them pushing changes to the repository. Since the servers are on 1.7, the maps need to be revised on 1,7 clients only.

**Comment by javipepe** [comment]
Closing due to the fact that 1.7 clients are not anymore allowed, thus maps are no longer made in 1.7 versions :smiley:
