### ISSUE TITLE
[1.8 Testing] Vanishing Scoreboard & Boss Bar

### ISSUE THREAD

**Issue by IcedCode** [Avicus/Issues#635]
When you join the server it's there but after a minute or so they both randomly vanish at the same time.

**Comment by javipepe** [comment]
@thekeenant this is what I was talking about, any idea of what may be happening by know? Does it always happen at the same time within a match @IcedCode ?

**Comment by IcedCode** [comment]
When in the lobby it always seems to go when the game is about to start.

**Comment by IcedCode** [comment]
This has been fixed as far as I can tell
