### ISSUE TITLE
[OITQ] Killing yourself will give you a point

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#638]
If you look up and shoot an arrow a little bit into the sky and shoot yourself, you will get a point on the scoreboard

**Comment by IcedCode** [comment]
Possible fix is to prevent killing yourself at all? (Maybe just in OITQ). Can be done via the EntityDamageByEntityEvent.

**Comment by AustinLMayes** [comment]
@IcedCode Only problem with this is that some events: falling, fire, downing, and suffocation don't fire this event. You could in theory drown yourself and still get a point. Maybe better to just check EntityDamage cause to make sure it's an enemy player and not award points on other deaths.

**Comment by thekeenant** [comment]
Fixed in new update
