### ISSUE TITLE
[Expo] You can start a game by voting

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#639]
If there's not enough people in the game to start it, you can vote for a map in the paper and it will start the countdown regardless of how many people are in the game

**Comment by steven5703** [comment]
Tested it again, for some reason didn't work. I don't know what conditions make this happen but I did this before

**Comment by IcedCode** [comment]
Depends on how many players are required for the highest voted map to start I believe?

**Comment by thekeenant** [comment]
@IcedCode is right, it's determined that way which is why you see different results.
