### ISSUE TITLE
/map gives an error

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#640]
![image](https://cloud.githubusercontent.com/assets/6472584/11349609/0e4df332-91fb-11e5-985c-1fa4ae2070c2.png)

**Comment by IcedCode** [comment]
This ONLY occurs with the current plugin on public servers at the moment. It works on the plugin in Expo & on the old plugin (before voting/keys was implemented)

**Comment by IcedCode** [comment]
Fixed as far as I can tell
