### ISSUE TITLE
Web - Can't change email (500 Error)

### ISSUE THREAD

**Issue by pavilion99** [Avicus/Issues#642]
I tried to update my email on my profile and I couldn't do it because the site ran into a 500 server error.

![screenshot 2](https://cloud.githubusercontent.com/assets/5050363/11464001/d55153d8-96f7-11e5-82e3-2d27bff51fdf.png)

**Comment by thekeenant** [comment]
Possibly fixed.

**Comment by rilomilo9** [comment]
Pav, you were meant to leave avicus for 2 weeks. It turned to be 5 months

**Comment by thekeenant** [comment]
@rilomilo9 Interesting observation, wrong place for that I think.

@pavilion99 Fixed? I'm not seeing any error myself.

**Comment by pavilion99** [comment]
@thekeenant Can confirm, is now working.
@rilomilo9 Sorry m9
