### ISSUE TITLE
Web Temporary Bans may be glitching

### ISSUE THREAD

**Issue by ParaSpider** [Avicus/Issues#643]
Web Tempbans are glitching according to https://avicus.net/SaTiSfAcTiOn__. He got web banned, and it expired, but he says it's still active.

**Comment by ParaSpider** [comment]
I have no idea, but it works for him now. He said he had 500 errors when accessing the site?

I haven't replicated it yet.

**Comment by AustinLMayes** [comment]
@ParaSpider could have been lag, how long did the 500 errors occur?

**Comment by ParaSpider** [comment]
@AustinLMayes Unsure, I believe for maybe 10 minutes max?

**Comment by javipepe** [comment]
@ParaSpider He got a different error than when trying to access the website while webbaned? We have a screen that pops up when user is webbaned, and then the error backtracing ones; did he see the first one while he was banned, and then 10 minutes after the expìring date he was getting the 500 errors?

Also any screenshot of the 500 error?

**Comment by ParaSpider** [comment]
@javipepe Yeah, he got a different screen (the original web ban screen displayed, but after it expired it temporarily showed a 500 screen is my guess), and no, I don't have a screenshot.
