### ISSUE TITLE
Tp gadget appears in 1 hub only

### ISSUE THREAD

**Issue by TridentSPQR** [Avicus/Issues#644]
The teleport wand gadget only appears in the hub I bought it in, not in the other one. Same thing happened to another player.
Not sure if intentional or bug
http://prntscr.com/99qi4y
vs
http://prntscr.com/99qiap

**Comment by IcedCode** [comment]
I believe this issue maybe different to what said here. I bought the lightning wand but I find it just vanishes more randomly from my enderchest than what described above, IE no correlation...

**Comment by thekeenant** [comment]
Fixed with next update.
