### ISSUE TITLE
Lobby Spawnpoints not 'correct'

### ISSUE THREAD

**Issue by AtditC** [Avicus/Issues#646]
You spawn at X83 Y29 Z212, but that's actually only the bottom right corner of the block you are supposed to spawn on. The correct coordinates would be X83.5 Y29 Z212.5, so you spawn in middle of the block. I just wanted to report this because I don't know if it matters, so the Map Devs know.

![2015-12-16_02 48 12](https://cloud.githubusercontent.com/assets/7355350/11829796/8668ca62-a39f-11e5-82b5-7807ad2f0a69.png)
![2015-12-16_02 48 23](https://cloud.githubusercontent.com/assets/7355350/11829797/87668b16-a39f-11e5-89c1-06b2f6b76dd3.png)

**Comment by javipepe** [comment]
Fixed @ https://github.com/Avicus/Maps/commit/bc81b1aa0874d7bc282c8f416953bc09c5a6c708
