### ISSUE TITLE
Spawning on spectator spawn after death

### ISSUE THREAD

**Issue by Fissuraaaa** [Avicus/Issues#647]
https://www.youtube.com/watch?v=fglSWPpmzm4

**Comment by javipepe** [comment]
Hopefully fixed on https://github.com/Avicus/Avicore/commit/fb8b7227b072fd72ad83d9857c4d40f7bce0a0c5 @ branch 1.8.8 (Avicore). 

Awaiting testing.

**Comment by javipepe** [comment]
Fix being pushed soon. If you still experience this after ~1 week, reopen :smile:
