### ISSUE TITLE
Error handling in /go

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#649]
![Error](http://cl.ly/2m1r0T141L0a/Screen%20Shot%202015-12-24%20at%2012.40.53%20AM.png)

As you can see, if /go is executed, instead of the command handling any exceptions internally and supplying a useful message, command exceptions are sent back to the player.
Because of this, server errors and permissions pushback are sent to the player. This can cause confusion for the player on the front end and also looks unprofessional. In theory, the command should perform all of the tasks and catch any command exceptions and handle them accordingly, instead of just throwing them back at the player.

**Comment by rilomilo9** [comment]
xdddddddddddddddd

**Comment by thekeenant** [comment]
I don't see server errors, I'm confused what the issue is..?

**Comment by AustinLMayes** [comment]
@thekeenant When /go is executed by the player, they are sent errors as if they ran the individual /server and /tp commands (line 7-8 in the photo) instead of the errors being handled by /go and no actually being sent by the player.

For example, if they are on the same server, don't warm them and if they don't have TP permission tell them that TP isn't allowed instead of showing no permission which can be confused as not having /go permission.

**Comment by thekeenant** [comment]
Alright. I suppose a minor improvement could be made.
