### ISSUE TITLE
Grammatical Error in /friends

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#651]
![](http://cl.ly/2e3h31372H28/Screen%20Shot%202015-12-25%20at%201.48.06%20PM.png)

As you can see, the message does not take into account the number of friends when pluralization is displayed.

**Comment by javipepe** [comment]
Redoing /friends in some minutes.

**Comment by javipepe** [comment]
/friends command rewritten with per-server results ( https://github.com/Avicus/Avicus/commit/9bede868572cf3611ad1cd3563650c1f736614f5 ), awaiting deployment.

Thanks for reporting anyways :+1:
