### ISSUE TITLE
Ranks in /friends

### ISSUE THREAD

**Issue by AustinLMayes** [Avicus/Issues#652]
![hi](http://i.imgur.com/zzbvNTC.png)

As shown above, ranks appear to sometimes become null when /friends is displayed.

**Comment by javipepe** [comment]
Eh that isn't the current version of /friends, I'm not sure if it's deployed into the servers, but I'm quite sure there's no bug in.

However I want to test the rank part and get back to you, thanks for reporting!

**Comment by thekeenant** [comment]
Thsi was fixed!
