### ISSUE TITLE
I can't put my email

### ISSUE THREAD

**Issue by Shipi1** [Avicus/Issues#655]
535-5.7.8 Username and Password not accepted. Learn more at 

Backtrace
/home/web/avicus2.net/app/controllers/user_controller.rb:225:in `update' 

Params
utf8 => "✓" 
_method => "patch" 
authenticity_token => "5PlPxW/NSD2b+xC8OfogJBiSse0UMgqwwOGctm75Uq8=" 
user_detail => "{"avatar"=>"Minecraft", "about"=>"Hey!", "steam"=>"ChupikioLOL", "skype"=>"chupikio", "facebook"=>"ollar", "twitch"=>"", "twitter"=>"", "github"=>"", "email"=>"arias.martin1@gmail.com", "gender"=>"Male", "interests"=>"Videogames and Student", "cover_art"=>"/assets/profiles/trees.jpg"}"
id => "233035" 
action => "update" 
controller => "user" 
user => "SoloDimeChupi"

**Comment by thekeenant** [comment]
Fixed I think a while back
