### ISSUE TITLE
Block lag/rubber banding

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#657]
We've recently added AAC back onto the live servers. Even more recently we have disabled rubber-banding and many sprinting, flying, block breaking and placing checks. If more instances of rubber-banding are reported, it is likely to be the cause of other _plugin_ issues or potentially _client connection_ issues.

**If you have not played on Avicus past 2:00 CST on 1/25/2016, you have nothing to contribute to the discussion of this issue because the current state is different than the state you experienced. The servers are just now restarting with the new configuration.**

**Comment by thekeenant** [comment]
Significant improvement with removal of AAC! :+1:

**Comment by javipepe** [comment]
@thekeenant Never thought you were going to say that!

**Comment by thekeenant** [comment]
But NCP remains!

**Comment by Palmidence** [comment]
Still happens, it's back to as bad as it was: if not worse https://youtu.be/MsMHf8WjNV4
