### ISSUE TITLE
Media Missing From Staff Page

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#660]
I'm sure you guys are already aware, but just for the sake of organizational purposes, I'll make a post here.

Anyways, yeah.. it's just missing.

**Comment by javipepe** [comment]
With our upcoming rank-manager admin panel we no longer need to do any manual edits for this. When it's finally live we'll make sure it appears as it did before (no idea why it was removed haha).

Anyhow, thanks for reporting :smile: :+1:
