### ISSUE TITLE
(Scrim) Normal members can invite other teams.

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#661]
Normal team members can successfully use the "/scrim invite <teamtag>" command on the scrim server.
I'm not entirely sure if that's a bug or intentional, but I think only teamleaders should be able to use this command.

**Comment by DaFrozenBlaze** [comment]
It was always that anyone could do it, if I remember correctly...

**Comment by javipepe** [comment]
Still happening?

**Comment by thekeenant** [comment]
Pushed a fix :dancer:
