### ISSUE TITLE
People banned

### ISSUE THREAD

**Issue by rilomilo9** [Avicus/Issues#662]
So this isn't really a huge issue but I wanted to point it out. So if a player is banned, try to join avicus, on the forums it will say last seen a minute ago, even if you're banned

zaidms0987
andyjohn231 

^ It happened to those people. See they were banned a while ago and it says they joined recently

**Comment by javipepe** [comment]
This makes registering when abnned possible, though I guess there will be a way to sort it out.

**Comment by javipepe** [comment]
@thekeenant Do we plan on leaving this like-is?

**Comment by AustinLMayes** [comment]
This is fixed with the next update.
