### ISSUE TITLE
Regions enabled before the match starts

### ISSUE THREAD

**Issue by Slyae** [Avicus/Issues#663]
When cycling to a map, the regions are enabled prior to the start time. For example: gapple spawners start to spawn gapples before the match starts and in Senex CTW, you aren't allowed to enter the opposite teams spawn

http://i.imgur.com/8HEVrRL.png

**Comment by javipepe** [comment]
https://github.com/Avicus/Avicore/issues/5

**Comment by thekeenant** [comment]
Ah this is more broad @javipepe

**Comment by thekeenant** [comment]
Pushed a fix to Avicore, will be in next update Avicus/Avicore@b0f9a1cabfce0d77f8eccb5d8da5dee49827b005
