### ISSUE TITLE
maps.avicus.net not available

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#665]
I mainly miss that you can't access the map.yml files, since that were one of the main references for many players to create ymls.
If you try to access the site you'll get redirected to the home page (avicus.net).

**Comment by javipepe** [comment]
https://avicus.net/forums/e53dafd2e

**Comment by thekeenant** [comment]
To address this further, maps will not be up until after the next update.

**Comment by thekeenant** [comment]
JK its up.
