### ISSUE TITLE
docs.avicus.net not available

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#666]
The YAML docs are not available.
If you try to access the site you'll get redirected to the home page (avicus.net).

**Comment by javipepe** [comment]
https://avicus.net/forums/e53dafd2e

**Comment by kashike** [comment]
@javipepe "over the next few days (1/29 - 1/31) as we transfer them"
It is well past 31 of January.

**Comment by thekeenant** [comment]
We're on it :P

Shouldn't be closed

**Comment by thekeenant** [comment]
And docs is up.
