### ISSUE TITLE
Scrim server reservation cancelling not working.

### ISSUE THREAD

**Issue by Auratixx** [Avicus/Issues#667]
http://imgur.com/a/Ji0dg

**Comment by AustinLMayes** [comment]
See #664

**Comment by thekeenant** [comment]
This is scrim servers not cancelling, the other is teams @austinlmayes

**Comment by AustinLMayes** [comment]
It's the same issue

**Comment by thekeenant** [comment]
And it was fixed, caused by the same issue referenced before.
