### ISSUE TITLE
Underscores are disregarded with searching for players

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#669]
i.e. reporting Nobu_ may report Nobug

**Comment by javipepe** [comment]
@thekeenant Any idea of what may be causing this?

**Comment by thekeenant** [comment]
Not exactly, got some ideas.

**Comment by ProfessorUtonium** [comment]
Just saying this, putting something such as "Ed_ans" would work and would go to that appropriate player (Ed_ans) but putting "Edans_" would disregard the underscore. This problem is with the underscores at the end of a username as far as I know.
