### ISSUE TITLE
Iron gets bold death messages if IronSwordGaming kills/dies

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#670]
@javipepe's bolder thingy mabob.

**Comment by javipepe** [comment]
Emm I fixed this recently @thekeenant https://github.com/Avicus/Avicus/commit/46a3dc682da36b5c87538ec432ca4b1af9c84fa0

**Comment by thekeenant** [comment]
But what if the message is "&cfunkystudios was killed by &aIronSwordGaming"

no space at end

**Comment by javipepe** [comment]
Lel hit enter and commit message didn't register entirely. I think this should fix it @thekeenant https://github.com/Avicus/Avicus/commit/85fd4efb1603e4e6a7b6975026427429d26cc09b

**Comment by javipepe** [comment]
Pretty sure that's it. Closing until further notice.

**Comment by thekeenant** [comment]
Avicus/Avicus@ab8aa5e97b68aa308d2ccaf911247aa54e280817
