### ISSUE TITLE
Problems with Registering on the Forums.

### ISSUE THREAD

**Issue by Pie55555** [Avicus/Issues#673]
I am reporting for LittleWhiteEars who is very unfamiliar with this website.

A few players have been coming to me and say they are having issues with registering on the forums. Little says that it is not just him having these issues but a lot of his friends as well. When I asked him to describe where he is having troubles in registering he said this:
https://gyazo.com/945ae32c8c865a22585547503558a572
https://gyazo.com/d980f6119038726b16c165b717949741

**Comment by javipepe** [comment]
@Pie55555 Would like to know if you have received any more complaints / issues from people saying this.

If it was already fixed i guess we can go ahead and close it :stuck_out_tongue:

**Comment by Pie55555** [comment]
I have not had any more complaints from anyone about this

**Comment by ProfessorUtonium** [comment]
I just a complaint about registration and tried it with an alt who hasn't registered before. When given the Unique IP to join the server for registration, the Unique IP reroutes the player to the Main Avicus server and the Registration won't complete after that. @javipepe

**Comment by AustinLMayes** [comment]
Resolved
