### ISSUE TITLE
Can't access the forums when logged in.

### ISSUE THREAD

**Issue by Eteh** [Avicus/Issues#677]
I can't seem to access the forums while logged into my forum account. When I log out, it's perfectly fine. However, others seem to have access but not me.

**Comment by Aki35** [comment]
Yes, this happens to me as well when browsing the mobile website.

**Comment by thekeenant** [comment]
Fixed! Comment if it's actually not :octopus:

**Comment by resepignev** [comment]
Re-open please.
A player has the same issue again:
http://prntscr.com/abjcgq

**Comment by thekeenant** [comment]
A username would be helpful @resepignev!

**Comment by resepignev** [comment]
I have no idea how, but it's fixed the player can access the forums again.

The username was **iScaglia**
