### ISSUE TITLE
Map Dev placement on staff page

### ISSUE THREAD

**Issue by CrazyCreeper521** [Avicus/Issues#682]
I'm not sure if this is a bug or not, but on the staff page (avicus.net/staff), the Map Devs are all the way at the bottom of the list, just above media. If I recall correctly, they're normally in between Devs and Mods. 

The Jr Map Dev group is also displaying in the staff page, however, there is no one in that group.

**Comment by thekeenant** [comment]
Not really a bug, just a configuration.

And all ranks are displayed, even if no one is in it.
