### ISSUE TITLE
Unable to post on forums

### ISSUE THREAD

**Issue by Stimulating** [Avicus/Issues#685]
When I try to reply to posts or post at all, no matter in what category the error message "You do not have permission to reply to topics in this category." pops up (red strip at the top, like when you try to post in a locked topic).

**Comment by thekeenant** [comment]
Assuming this was fixed?

**Comment by thekeenant** [comment]
Assuming this was fixed?

**Comment by Stimulating** [comment]
Nope, still not allowing me to post

**Comment by Stimulating** [comment]
UPDATE: It allows me to post in referals and that seems to be it

**Comment by AustinLMayes** [comment]
This has been resolved.
