### ISSUE TITLE
Hidden/Archived posts on the forums show page numbers & move shown pages

### ISSUE THREAD

**Issue by vladthegreat100** [Avicus/Issues#687]
As you probably know, when you archive or have a section where posts are meant to be hidden it goes out of the view of the regular members. Before the update for example, the "Staff Application" section would be hiding multiple posts. Once the new update came on the forums you still can't see this but now it shows the posts.
**The Problem?: **When Staff Applications do come up the post will be moved down farther into the other posts like it would show for a staff member, problem for regulars is that their post will have disappeared and may believe that it was deleted.
Not sure if this is meant to be or a legit bug but best to put it here in case: 
Example of blank page: 
https://i.gyazo.com/1721ef8abaa9aa5313e71da0d6f6432d.png

Example of post being moved down the pages:
https://i.gyazo.com/f3a77ba563f979b5a599fde167f1e13f.png

**Comment by AustinLMayes** [comment]
This can't be fixed without a drastic increase in page load time, sorry!
