### ISSUE TITLE
Gravatar not working

### ISSUE THREAD

**Issue by CrazyCreeper521** [Avicus/Issues#695]
On my profile, I can no longer select to use the Gravatar picture instead of the Minecraft one. I had confirmed an email in the past, so it should still be working. 

Also, I cannot enter an email to reconfirm. 
https://i.gyazo.com/ea1d1ef5515fbcbecdbda0ee2b54efa0.png

Some people I have talked to don't have this problem, while a few others do.

**Comment by AustinLMayes** [comment]
Should be fixed, comment if still occurring.

**Comment by CrazyCreeper521** [comment]
Yep, still happening.

**Comment by AustinLMayes** [comment]
@CrazyCreeper521 Can you edit your email now?

**Comment by CrazyCreeper521** [comment]
Still no. It doesn't let me select the box.
