### ISSUE TITLE
You can break protected spawn area on Castle Adventure

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#698]
![](https://i.gyazo.com/0a8dbc22aefc0bbab21131c4b78a2543.gif)

**Comment by ProfessorUtonium** [comment]
@thekeenant I'll see what I can do

**Comment by ProfessorUtonium** [comment]
Fixed in the Latest Map Revisions for Castle Adventure.
Took the time to also improve the spawn blocking regions for less spawn blocking on the map.
Thanks for Pointing this out.
