### ISSUE TITLE
I cant disband my team

### ISSUE THREAD

**Issue by iScaglia** [Avicus/Issues#703]
**I created a team for fun and now i want join in a team but when i want disband or leave i cant, it tell me that i dont have permission to disband the team:
**
http://prntscr.com/abc3q8

**Comment by thekeenant** [comment]
@AustinLMayes Did you push a fix?

**Comment by iScaglia** [comment]
With the new update i could disband it

**Comment by thekeenant** [comment]
Awesome, thanks :+1:
