### ISSUE TITLE
/sv

### ISSUE THREAD

**Issue by Midnightstorm** [Avicus/Issues#713]
/sv (server name) or /server (server name) not working.

**Comment by thekeenant** [comment]
What's broken about it?

**Comment by Palmidence** [comment]
This is working perfectly fine for me. Are you using the **-f** flag?

**Comment by javipepe** [comment]
@thekeenant Server names aren't autocompleting. So say `/sv thr` led you to Throwback before, but now it needs the whole thing. Looking into it!
