### ISSUE TITLE
Profile editing fields are not ediable

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#714]
When you access your profile over the drop down menu (https://avicus.net/users//<username>/edit),
you can't edit any of your information (About page, cover art, social media links)

Maybe it's intentionally disabled until all bugs are fixed, but it's worth reporting.

![](http://i.imgur.com/ZEiVc8q.png)

**Comment by javipepe** [comment]
@resepignev Still happening?

**Comment by resepignev** [comment]
@javipepe I think it's fixed :D Thanks!

**Comment by javipepe** [comment]
:sparkles:

**Comment by resepignev** [comment]
I'm sorry that I have to open this issue again, but it looks like my profile is bugged again :(
