### ISSUE TITLE
Permission Issues

### ISSUE THREAD

**Issue by javipepe** [Avicus/Issues#715]
### Describe who should have it, what it is, and if they had it before the update. Current Issues:

- Leaders do not have permissions to /sn, /cycle, /start etc... on their own scrim server.
- Map Developers have No Perms for Creative nor WorldEdit on MapDev. This used to work before the Server Updated. Was this intended or was this just a glitch? http://imgur.com/y4uir28
- Officials Have No Perms for Official/Ref Chats. http://imgur.com/z9LV6YW Typed the Command for Both Chats and none of them worked for me.
- Mods have no Perms to Drain Water nor Extinguish Fires http://imgur.com/piS9gEe Did //ext and //drain but no perms.
- Senior Moderators do not have access to /gamemode.

**Comment by Jahaj1** [comment]
Players on scrim servers cannot choose a team to join.

**Comment by AustinLMayes** [comment]
Please make individual issues.

**Comment by thekeenant** [comment]
U wot
