### ISSUE TITLE
You lose your bow and sword in Senex II when dropping them

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#716]
They should be droppable to you like all the other maps: you are able to pick it up, nobody else. Once you drop it on Senex II, though, it's gone completely and have to defend bowless.

Map issue.

**Comment by javipepe** [comment]
@Avicus/map-developers

**Comment by Aki35** [comment]
I'm sure this problem is on tons of other maps as well. Time to do a dig through YMLs?

**Comment by ProfessorUtonium** [comment]
@javipepe Fixed this issue and @aki35 and @Palmidence If you can PM me on Skype (It's sethskye) with the maps that have issues like this, I can fix them.
