### ISSUE TITLE
Can't view Recent Post

### ISSUE THREAD

**Issue by GrapeSmoothie** [Avicus/Issues#719]
I notice when I go to check someone's most recent post on their profile under the "recent post" tab everything comes up blank

**Comment by javipepe** [comment]
@GrapeSmoothie You mean when you click the orange bubble? It works for me, please send video or steps to reproduce :(

**Comment by thekeenant** [comment]
We hid the recent posts section from profiles temporarily due to permissions errors.

**Comment by Aki35** [comment]
Ayy can close now :D
