### ISSUE TITLE
Unable to edit forum title

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#722]
I can't edit the title of my own discussion post. This error comes up, I have never seen this before.

![webpage_20160307_092051](https://cloud.githubusercontent.com/assets/12650080/13580419/47a84676-e446-11e5-871c-da25eac2a127.jpg)

**Comment by Aki35** [comment]
By the way if it changes anything, the forum categories I tried to post in were Map Releases and Nebula.

**Comment by javipepe** [comment]
@Aki35 Still happening?

**Comment by Aki35** [comment]
@javipepe I just experimented with some other posts such as my AMA, but that one worked fine, it's just this post that seems not to work. https://avicus.net/forums/discussions/d78444e99

I even tried shortening the title in case qhen I edited it got too long, but that didn't solve it.

I really have almost no idea what is causing this.

**Comment by Palmidence** [comment]
I think that's because the title was made before the character limit and it's stuck in limbo

**Comment by Aki35** [comment]
I figured it out! Apparently, for the Map Releases section, you aren't allowed to set a tag (which in this case is the gamemode). To work around this, I just left the tag blank. Someone must've removed permissions from us or something.

**Comment by AustinLMayes** [comment]
Oh, simple fix then 😄 

Tag permissions have returned!
