### ISSUE TITLE
Name history tab-complete error

### ISSUE THREAD

**Issue by alexanderjoe** [Avicus/Issues#723]
When trying to tab a player names servers throws an error. 
Example. [https://gyazo.com/5fe6e1e69ae2ef24c4326e9cebe22a17
![taberror](https://cloud.githubusercontent.com/assets/8846229/13587913/686bed56-e499-11e5-93ea-c75fef70a5a8.png)
](url)

**Comment by Aki35** [comment]
#692 :c

**Comment by javipepe** [comment]
Yeah this is a dupe, thanks for trying to help, though!
