### ISSUE TITLE
Punishments history in descending (false) order

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#725]
**This problem is only happening in the lobby.**

How it is on normal servers (right way):
![](http://i.imgur.com/uiDxOwj.png)

How it is in the lobby (wrong way):
![](http://i.imgur.com/UmP0LQQ.png)

To reproduce the issue, do /history of a player that has more than 2 punishments on a normal server like throwback and the same in the lobby.

**Comment by thekeenant** [comment]
The plugins are identical on the servers though.. 😐

**Comment by javipepe** [comment]
Yeah it's the new version. They should be descending from now on, plus the timestamp is in gold as you can see.

Also @thekeenant most Nebula servers' Avicus version is https://github.com/Avicus/Avicus/commit/ba7b4b9c284c2be3ae7586024a4cd98e04face95` while this was made at https://github.com/Avicus/Avicus/commit/c7de8302aa7a1dc7b78096b7cbed8fba7efd4feb . Weird :astonished:

**Comment by javipepe** [comment]
But I don't think this is any issue, just a new feature / enhancement.
