### ISSUE TITLE
Cannot edit profile background

### ISSUE THREAD

**Issue by Auratixx** [Avicus/Issues#728]
Trust me, the size is 1200 by 250.
[http://imgur.com/a/uGvVR](url)

**Comment by javipepe** [comment]
@Auratixx Still not working?

**Comment by Auratixx** [comment]
@javipepe Nope, still not. http://imgur.com/NS6PfiN

**Comment by javipepe** [comment]
@thekeenant Still working on this?

**Comment by AustinLMayes** [comment]
Fixed
