### ISSUE TITLE
All Website Issues

### ISSUE THREAD

**Issue by Sesspee** [Avicus/Issues#729]
I went through the website and found all the obvious glitches and bugs from the recent update. Enjoy. If i find anymore i will update this. Tomorrow i will make a similar issue for all the bugs on the server. 

The tournament page,
 When you click on view for ANY tournament page you get directed to a 404 page.

![screen shot 2016-03-12 at 5 54 45 pm](https://cloud.githubusercontent.com/assets/10671772/13722281/2dfdd4e6-e87b-11e5-98cd-58314b1c4be2.png)

 On leaderboards, DTM and TDM do not show. 
![screen shot 2016-03-12 at 5 55 43 pm](https://cloud.githubusercontent.com/assets/10671772/13722287/557d6644-e87b-11e5-91df-8a4f0ef3c5b2.png)

On leaderboards the month and all time tabs do not work.
![screen shot 2016-03-12 at 5 56 56 pm](https://cloud.githubusercontent.com/assets/10671772/13722292/75d106b2-e87b-11e5-8e4d-726574eba1fb.png)

Survival Games leaderboards do not work, they don't display anything.
![screen shot 2016-03-12 at 5 56 36 pm](https://cloud.githubusercontent.com/assets/10671772/13722296/8af0791a-e87b-11e5-8df0-5f5f6dee8c9e.png)

Capture the Hill leaderboard, only player and cth points appear, no other stats appear. 
![screen shot 2016-03-12 at 5 56 56 pm](https://cloud.githubusercontent.com/assets/10671772/13722299/ba199dca-e87b-11e5-8ed2-5029a648c7f2.png)

**INTENTIONALLY DISABLED:**
<strike>Recent posts tab in a player profile do not show</strike>:
![screen shot 2016-03-12 at 6 00 10 pm](https://cloud.githubusercontent.com/assets/10671772/13722301/cc67315e-e87b-11e5-8e13-92ea16863249.png)

**INTENTIONAL:**
<strike>There are 2 links to open the voting page, one on the navbar and one on the footer (i am presuming this is an error). </strike>
![screen shot 2016-03-12 at 6 03 14 pm](https://cloud.githubusercontent.com/assets/10671772/13722305/f97c0962-e87b-11e5-8546-f6e57f1e61ea.png)

**FIXED:**
<strike>You cannot edit your profile, a circle with a line through it appears when attempting to do so. And if you click save, it wipes your profile, as i found out :'( </strike>

![screen shot 2016-03-12 at 6 03 46 pm](https://cloud.githubusercontent.com/assets/10671772/13722310/202bccfa-e87c-11e5-9a38-92352efb0c24.png)

**Comment by javipepe** [comment]
The profile not being ediable (sorry for your profile :crying_cat_face: ) is fixed in https://github.com/Avicus/avicus.net/commit/45985f241dc941f7b4a955c84ecf5c42898c4e67

The two links for voting is **intentional**

Recent posts tab in a player profile do not showing is **intentionally disabled** for the time being.

**Comment by IcedCode** [comment]
Also gonna add that all the stickied topics have been removed so for example there is no way to see a format for appeals or reporting players

**Comment by AustinLMayes** [comment]
Let's not create group issues, thanks.
If any of these issues have not been reported already, you may report them individually.
