### ISSUE TITLE
Avicus Ban Appeal? [Important]

### ISSUE THREAD

**Issue by Pyrxis** [Avicus/Issues#732]
First of all i am writing this here because the registration in avicus.net is down. I am Pyrxis also known as QuickDropEz. I came to this server about 2 month ago when i was recommended by my friend Josio_Swaglord. I decided to hack (BIG MISTAKE) and got banned in literally 13 minutes. It is a really great server and a great website one of the best i've ever seen and I wonder why it doesn't have that much people playing. Anyways i am banned and i realize my mistake and i know i shouldn't have hacked. I should serve my punishment and stay banned, but i really enjoyed the server and if i do get unbanned ill will makesure to not use any more hacked client.

Now the main issue: my friend Josio_Swaglord who spent over 18 hours on this server and played this server as his favorite server got banned because of me. He came over to my house after i was banned and (i think is IP ban because of removing alt account of banned players so he also got banned when  he shouldn't have been banned) it is my problem not his. i was the one who was hacking and i should server the punishment not him. Its okay if i don't get unbanned but josio_swaglord really enjoyed this server and i wouldn't like him to be permanently banned. I also have a alt account (bigberryj) that i used to try to register into avic.us because i couldn't go into the minecraft server to register because i was banned and the account also got banned. 

 I no longer use the hacked client because of my awareness of how unfair it makes the game play when other people plays it fairly. It  gives me a tremendous advantage and it makes the game play boring and unfair. I am really sorry and i deserve the punishment, but i hope that josio_swaglord can be unbanned cause he spent a lot of time into this server and he really enjoyed it playing on it (especially nebula).

Thank you for spending your precious time on reading this appeal and i hope that you will take into consideartion in unbanning my friend josio_swaglord

Thank you again 
 ~Pyrxis

**Comment by Pyrxis** [comment]
And also if anybody can get it linked to a manager or a moderator from avic.us that will help so much ty

**Comment by AustinLMayes** [comment]
Please email support@avicus.net

**Comment by Pyrxis** [comment]
*First of all I am sending this to your gmail because apparently the
registration in avicus.net <http://avicus.net/> is down. I am Pyrxis also
known as QuickDropEz. I was banned about 2 to 3 month ago for Hacking. I
know that what I did was bad and it was my mistake. I realize how hacking
makes other people's game play boring and unfair and that it gives me a
tremendous advantage over others who are playing fairly. I know that I
deserver my punishment and I should be banned but I hope I can be given a
second chance. I already deleted all my hacks and I know that hacks should
not be allowed. And also I can help the community by maybe building new
maps for games and inviting more friends. I am also good at plugins and
coding.*

*The main problem is that my friend Josio_Swaglord who invited me to this
server got banned for my mistakes. He came over to my house one day and
logged into my computer and I think he got (IP ban because he wasnt hacking
and he got instantly banned.) then I have anothers friends account called
bigberryj and I went on and got banned instantly with that also. We dont
have any hacks.*


*Josiah has been inviting a lot of friends to this server about (6~8)
Including 7en (_Ubi), Greffen? , xHajiPajix, eliisac, TheEndMaster,
Localheist123, CaptinPengin?, Mike4play?, and a lot lot more. He spent more
than 18 hours on this server and this is his first server and his favorite.
He is pretty new to minecraft so he doesnt really know all about hacking,
ban, forum, etc. He is really sad that he got banned on his server.*


*He shouldn't be banned and I should deserve the punishment. I am the one
who was hacking and I am the one who should be banned. I hope you can unban
Josiah for he has done nothing wrong and he have done a lot to the
community. Thank you for spending your precious time on reading my appeal.
I hope you guys at least take into consideration of unbanning Josiah and my
friends account bigberryj. Thank you again.*


*~Pyrxis formerly known as QuickDropEz*


*PS: I am writing this appeal for Josio_Swaglord because he is really new
to minecraft and he downst know about ban and unban and appeal and forum
and etc. I had to explain it all to him. I really do hope he can be unban
and play avic.us <http://avic.us/> with his friends agin. Thank your so
much. BTW one of the friend Josiah invited is Localheist123 and he has a
youtube channel where he sometimes upload avicus videos and he is getting
some subscribers quickly.*

**Comment by AustinLMayes** [comment]
Since it appears that you and Josio_Swaglord are the same person, and that you have other accounts that are ban evading, I would advise you to stop posting here. IF you still wish to appeal, registration now seems to be working (thanks @thekeenant)

**Comment by Pyrxis** [comment]
Well first of all josio_swaglord and me are different person, i dont know
how i can prove that but you can check josio's IP and you will see that it
has multiple IPs. if there is a way for u to check how much time he spent
on the different ip. I dont know how to prove it but I am completley
different person than josio_swaglord. My realname is Haon Park and his name
is Josiah Bass thank you,
