### ISSUE TITLE
Team Name Under User Profile Glitch

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#735]
I was browsing through people's profile and I looked to see what team they were in and instead of the team name, I came across this. It does not happen all the time, but it happens sometimes. I was using mobile, but the glitch may be present on desktop/laptop as well.
![webpage_20160318_094023](https://cloud.githubusercontent.com/assets/12650080/13890146/0e85abf8-ecee-11e5-8b1f-9f5a288b3cc5.jpg)

**Comment by javipepe** [comment]
Fixed @ https://github.com/Avicus/avicus.net/commit/50404ea8ba2284f3a06ad0e1b7e156960c1c4ca7
