### ISSUE TITLE
Ban Messages are bugged

### ISSUE THREAD

**Issue by Pelpel** [Avicus/Issues#736]
![screen shot 2016-03-19 at 16 50 39](https://cloud.githubusercontent.com/assets/10104759/13899607/c8341b16-edf2-11e5-92fb-6d34c2d0b8de.png)

No punisher name, and no name for the player punished. Also, what's the TM02?

If it makes a difference, I had my toggle option for receiving punishments set to "Global"

**Comment by javipepe** [comment]
This thing is not on a solid enough development stage, I accidentally pushed it to all server when I should have not.

Reverted back.
