### ISSUE TITLE
Action Bar Credit Message

### ISSUE THREAD

**Issue by alexanderjoe** [Avicus/Issues#737]
When the action bar sends a message for credits the color do not work correctly
![2016-03-20_00 58 23](https://cloud.githubusercontent.com/assets/8846229/13902907/19a21b1c-ee37-11e5-8f20-a2357103a1e1.png)

EDIT: Thought instead of a new issue just to add that /tracker is broke.

**Comment by javipepe** [comment]
Fixed :sparkles:
