### ISSUE TITLE
Gamemode doesn't work on Scrim Servers.

### ISSUE THREAD

**Issue by Eteh** [Avicus/Issues#742]
I am a leader of Cronus but I can't change my gamemode on our own scrim servers. Every other leader permissions are fine but this is the only problem.

**Comment by javipepe** [comment]
Try again and report back @Eteh

**Comment by Eteh** [comment]
@javipepe It still doesn't work.

**Comment by AustinLMayes** [comment]
This should be fixed, reopen if still occurring.

**Comment by Eteh** [comment]
It still doesn't work.

**Comment by javipepe** [comment]
@eteh Report back please, still not working?

**Comment by Palmidence** [comment]
@javipepe According to @Sesspee and @nathbrown it doesn't work still.
