### ISSUE TITLE
Walls wins/kills/deaths Aren't recorded

### ISSUE THREAD

**Issue by Patrikano0** [Avicus/Issues#743]
So my wins, kills and deaths on Walls aren't recorded...Or atleast for me. I think other people's stats are recorded, or so it seems when I check walls weekly leaderboard. But my ones are not...

**Comment by Patrikano0** [comment]
It seems like for others it is...Not for me and probably a some others, would be nice if it was fixed xd

**Comment by thekeenant** [comment]
Fear not, it's all recorded the same. It's not displaying correctly is all, not sure why.

**Comment by Patrikano0** [comment]
Hmm, it's displaying some people's but not mine and i'm sure not others :/

**Comment by Patrikano0** [comment]
Hmm, it's not recording again :3 

You did something before and it recorded again but now it stopped :/

**Comment by thekeenant** [comment]
It's still open, so we haven't attempted to fix it.
