### ISSUE TITLE
Deaths and Kills are recorded on scrims..

### ISSUE THREAD

**Issue by Patrikano0** [Avicus/Issues#744]
When I die or kill someone on scrim servers they are recorded. But monuments and wools are not recorded..

**Comment by Patrikano0** [comment]
And you gain credits for kills and monuments and wools on scrims...

**Comment by resepignev** [comment]
The same happens on dev and expo.

**Comment by Palmidence** [comment]
Is this still occuring?

**Comment by Patrikano0** [comment]
Yeah it is

**Comment by Palmidence** [comment]
I'll close in favor of #718
