### ISSUE TITLE
Error 500 while trying to see my forum discussions

### ISSUE THREAD

**Issue by DeliciousShoesHD** [Avicus/Issues#747]
Hey!

I am 100% sure that you know what's going on from just reading a title of this issue. Basically, when I want to see my forum discussions, it throws out an error 505.

Evidence can be found here: http://imgur.com/SUlIM8x

Thanks for reading!

Sincerely,
_DeliciousShoesHD (Avicus Moderator)_!

**Comment by OldManTigerMask** [comment]
@thekeenant Issue Fixed?

**Comment by OldManTigerMask** [comment]
No error for me, could it be closed?
@AustinLMayes

**Comment by AustinLMayes** [comment]
Reopen if still occurring.
