### ISSUE TITLE
Can't reply using /r on latest message from different person

### ISSUE THREAD

**Issue by hydraiku** [Avicus/Issues#752]
Title may be misleading, but issue as follows;

Player A and I have a conversation. It ends in 2 minutes.
Player B then messages me, and I type /r, but it sends the message to player A

How to reproduce:
Get someone to message you, and reply to them. Then, get someone ELSE to send you a message and try to respond using /r. 

Thanks, it's quite annoying :l

**Comment by thekeenant** [comment]
Possibly fixed once we push.
