### ISSUE TITLE
Cannot view stickied posts in different subforums

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#754]
Normal users cannot view https://avicus.net/forums/discussions/4f955d6ab in the "Appeal an Infraction" subforum even though it is stickied. This was also a problem with the staff application posts before they were moved.

**Comment by resepignev** [comment]
I think it's fixed. At least users now can see stickied threads in the staff application sub forum. Sadly I can't test the appeal sub forum since mods can no longer move stickied threads.

**Comment by AustinLMayes** [comment]
Is possible now, is enabled for threads that need it
