### ISSUE TITLE
Can't view My Discussions or search threads by my IGN

### ISSUE THREAD

**Issue by Stimulating** [Avicus/Issues#759]
Whenever I perform either of these actions, Error 500 message pops up. I can't view it at all, not just 2nd page. 

Error
undefined method `name' for nil:NilClass

Backtrace
/var/www/html/avicus.net/releases/20160412172718/app/views/forums/index/my_discussions.haml:78:in `block in _app_views_forums_index_my_discussions_haml___2037575488882553727_59436876682280'
/var/www/html/avicus.net/releases/20160412172718/app/views/forums/index/my_discussions.haml:45:in `_app_views_forums_index_my_discussions_haml___2037575488882553727_59436876682280'

Params
action => "my_discussions" 
controller => "forums/index"

**Comment by AustinLMayes** [comment]
See #747
