### ISSUE TITLE
The countdown breaks periodically so it unwarrantedly resets to another number

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#762]
@Slyae mentioned this and ended up having to fix it, I guess. Happened on Throwback at 6:00 PM EST, and assuming he didn't edit the time himself as he said he didn't, it is a glitch. No elements I'm aware of changed, and it did not hit the "starting in 1 second".

**Comment by javipepe** [comment]
I think this just was another person stopping the countdown, I have never witnessed this. Please reopen or comment if it happens again but really this doesn't sound like an issue on our side :stuck_out_tongue:
