### ISSUE TITLE
Ranks are constantly glitching on the forums.

### ISSUE THREAD

**Issue by Auratixx** [Avicus/Issues#763]
I cannot currently offer evidence, but I'm sure you're aware that ranks for players have been glitching.
Use **Xuph** for example: He was demoted, but a few hours later his forum name was coloured as MapDev, which was the rank he was removed from earlier. It seems to happen for around an hours or more after a change of ranks, then it's fine.

**Comment by Palmidence** [comment]
Clear your cache!

**Comment by Eteh** [comment]
@Palmidence It doesn't work

**Comment by javipepe** [comment]
@Eteh @Auratixx Noticed any difference lately?

**Comment by Auratixx** [comment]
@javipepe Seems fine now
