### ISSUE TITLE
Walls is Broken

### ISSUE THREAD

**Issue by shadowolfyt** [Avicus/Issues#765]
I tried to play walls the other day and noone was in the game. I tried to /join it and it said "you can't join a game that is already in progress"

**Comment by javipepe** [comment]
Looks like a circumstantial issue. Can you still reproduce the error?

**Comment by shadowolfyt** [comment]
When I logged in the error occurred. Other people started joining and they asked why isn't it letting us join. It said that a game was already in progress when it wasn't.

**Comment by ProfessorUtonium** [comment]
Which rotation was this? Walls03 is broken because the maps are weird and the game starts when there are no players in the matches because of the low player cap (1 each team to start). I will fix this when I get home but I just want to confirm what rotation this was.

**Comment by shadowolfyt** [comment]
So is this issue fixed?

**Comment by Palmidence** [comment]
I'm going to assume so, plus Atlas.
