### ISSUE TITLE
Delay Time in TDM= Sudden Death

### ISSUE THREAD

**Issue by Aki35** [Avicus/Issues#766]
Often times in scrims, we delay the match by a lot to ensure that we have everything sorted out. But, when you input a large number, the chat gets spammed with "SUDDEN DEATH" and 3 minutes is added to the map timer every time it says sudden death. I believe it is for values over 999 seconds, but I'm not too sure.

**Comment by ProfessorUtonium** [comment]
yes it is values over 999 for future developer reference.

**Comment by javipepe** [comment]
Looking at it.

**Comment by javipepe** [comment]
Fixed.
