### ISSUE TITLE
Spectators cannot open furnace and/or chest minecarts

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#773]
All other utilities can be opened, however for maps that have chest or furnace utilities, you cannot view them as a spectator. All utilities should be available for spectators to view.

![](https://i.gyazo.com/3eb6b75e0c0d12a99e5446bab369bbcc.png)

**Comment by thekeenant** [comment]
Closing this, as it is a random enhancement, doesn't even exist in Avicore currently :P
