### ISSUE TITLE
TNT can break protected build regions

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#775]
![](https://i.gyazo.com/d71e0cda4ec08936fa571b04d64aaa9a.png)

**Comment by thekeenant** [comment]
No, I think that map just has bad regions?

**Comment by Palmidence** [comment]
You can't break anything except with TNT. The opposite spawn cannot be entered, and it cannot be broken. TNT does, however.

**Comment by Palmidence** [comment]
Seems to work now. Magic!

**Comment by thekeenant** [comment]
That's how we solve most our bugs.
