### ISSUE TITLE
Last seen is 0 seconds when player is banned

### ISSUE THREAD

**Issue by sergivb01** [Avicus/Issues#782]
Well if a player is banned, on it's profile page it shows that the player's last time was 0 seconds ago. As example I just insert a [banned-player-profile link](https://avicus.net/mesternopvp) I consider it should be changed to some text as "Player banned" or to show the right time.

https://gyazo.com/95c77d34b8a577eb941dcbd4099678f3

**Comment by thekeenant** [comment]
Or whenever, like avicus.net/funkystudios

**Comment by AustinLMayes** [comment]
Previously banned users will show as simply `offline` while users banned after the fix will show time of ban.
