### ISSUE TITLE
ALM is dumb and broke the website

### ISSUE THREAD

**Issue by steven5703** [Avicus/Issues#784]
http://prntscr.com/blyuci
HE TRIED TO HIDE THE TBH THREADS XDDDDDDDDDDDDDDDDDDDDDDDDDD

Get meme'd kylo

**Comment by AustinLMayes** [comment]
This issue has been resolved.
Thanks for reporting!

**Comment by steven5703** [comment]
@AustinLMayes Who cares?

**Comment by thekeenant** [comment]
You dooo, you reported it silly @steven5703
