### ISSUE TITLE
You can place the same wool 2 times

### ISSUE THREAD

**Issue by AbusiveUser** [Avicus/Issues#787]
Here's a screenshot:

![2016-07-09_11 33 22](https://cloud.githubusercontent.com/assets/19915020/16709010/e123f5a4-45c9-11e6-8519-1c8d9d0148de.png)

**Comment by jasoryeh** [comment]
This problem has been here for a long time?

**Comment by Auratixx** [comment]
This is because (if you've noticed) after the game ends there is a 1-2 second moment where you still have the kits and can place blocks, hence why you can place wools even after a game should have ended.
