### ISSUE TITLE
Server help book guide glitched

### ISSUE THREAD

**Issue by pizza334** [Avicus/Issues#788]
![2016-07-11_19 49 30](https://cloud.githubusercontent.com/assets/6341732/16743029/63efba0c-47a2-11e6-9452-6aab0f8979d1.png)
![2016-07-11_19 49 28](https://cloud.githubusercontent.com/assets/6341732/16743032/6701cb54-47a2-11e6-80b7-9b66aca31001.png)
Has happened once or twice to me in the past , no idea what causes it.

**Comment by steven5703** [comment]
yeah what he said
