### ISSUE TITLE
Boss Bar Message

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#789]
Currently Says:
See our development - avicus.net/rivisions

Should Say:

See our development! avicus.net/development

**Comment by Auratixx** [comment]
Yes, https://avicus.net/revisions takes you to https://avicus.net/development automatically.

**Comment by steven5703** [comment]
This issue needs to be escalated to top priority. Honestly this is more important than Atlas.

**Comment by javipepe** [comment]
No fix needed because, as Aura said, https://avicus.net/revisions takes you to https://avicus.net/development automatically.

**Comment by OldManTigerMask** [comment]
Didn't notice that, earlier it did not.

**Comment by steven5703** [comment]
@javipepe @Auratixx @javipepe please fix this its really ruining my avicus experience

**Comment by smitdalt** [comment]
PLEASE FIX THIS I CAN'T USE THE WEBSITE IN THIS BROKEN STATE
