### ISSUE TITLE
Add authored maps to user profiles in 'Maps' tab

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#794]
![](https://i.gyazo.com/48c709524cb4ff26af7d7b7c7ff587ec.png)

Will pull from maps.avicus.net with a map image of the map the user authored, as well as the other authors that made the map. They may also get the ability to get a download token from the maps.avicus.net to have access to their own map?

Approved by @javipepe.

**Comment by thekeenant** [comment]
Not on the agenda/confirmed.

**Comment by Palmidence** [comment]
> Approved by javipepe

?
He wanted to add it

**Comment by thekeenant** [comment]
Me too, but it's not something we have the need or time to do.
