### ISSUE TITLE
Repeated nick on /msg and pressing tab

### ISSUE THREAD

**Issue by sergivb01** [Avicus/Issues#795]
So when a player just does /msg and writes a letter (J in my example) and then clicks tab, if he has a friend who is connected to the same server which it's name starts with J (in my example) the name will appear twice.

I attach an image of my logs. (I can't in minecraft cause actually there is no friend connected, but I made it with Javipepe before, when I found the bug).

![Image](https://cloud.githubusercontent.com/assets/16362381/17362810/204a848a-5977-11e6-933e-044e4898f21f.png)

:smile:

**Comment by javipepe** [comment]
Tested. All working now :+1:

**Comment by steven5703** [comment]
@javipepe good one!

**Comment by smitdalt** [comment]
@javipepe Nice one!!!
