### ISSUE TITLE
1.9 tablist has no team colors

### ISSUE THREAD

**Issue by JCostas380** [Avicus/Issues#796]
``

**Comment by AustinLMayes** [comment]
Please provide more explanation

**Comment by thekeenant** [comment]
In the tablist in 1.9 and up, players' names aren't colored.

**Comment by AustinLMayes** [comment]
Fixed in Atlas then

**Comment by JCostas380** [comment]
Thank you both @thekeenant and @AustinLMayes

**Comment by JCostas380** [comment]
Problem continues

**Comment by thekeenant** [comment]
We haven't released Atlas yet @JCostas380?
