### ISSUE TITLE
Staff with worldedit can't use wooden axes in-game

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#798]
It's a disadvantage for me, it'd be nice if we could use wooden axes (I need them for defense and not all maps have different materials)

**Comment by AustinLMayes** [comment]
Fixed in Atlas

**Comment by thekeenant** [comment]
I don't see how this is fixed in atlas? @austinlmayes

**Comment by thekeenant** [comment]
@palmidence I don't think you should have world edit perms, different issue though.

**Comment by ProfessorUtonium** [comment]
It's the mapdev rank

they have WE perms

**Comment by ProfessorUtonium** [comment]
@palmidence /toggleeditwand can disable it. You need to do this on every server though (such as once on throwback and once on CTW)

And @thekeenant refer to my response above for the issue

**Comment by thekeenant** [comment]
That's a good fix, we can't do much about it.

**Comment by AustinLMayes** [comment]
@thekeenant Right now we remove all WE perms on join, we remove less perms in Atlas

**Comment by thekeenant** [comment]
The problem isn't that they cannot use WorldEdit in game, it's that they can @AustinLMayes :stuck_out_tongue:

**Comment by AustinLMayes** [comment]
@thekeenant I think the original issue is that they can't use it in game.
