### ISSUE TITLE
Atlas - Armour Drops in Arizona

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#801]
The stickied armour doesn't work in ARIZONA.

I have fixed the issue and here is the XML
https://github.com/OldManTigerMask/Map-XML-Service/blob/master/Arizona.xml

**Comment by javipepe** [comment]
@Avicus/map-developers

**Comment by Palmidence** [comment]
I have fixed it, but for future reference:
- We will typically use repair-tools
- Proper indentation is needed for XML
- You cannot have spaces after an item's name
- It's spelt "leather", not "leader"
