### ISSUE TITLE
Players have permission to use /minecraft:tell in-game

### ISSUE THREAD

**Issue by HBatman** [Avicus/Issues#802]
Hey,

So on Avicus if you do `minecraft:tell <username> <message>` it whispers a player, which you shouldn't really be able to do.

As you can see [here](http://imgur.com/a/4MIla)

**Comment by OldManTigerMask** [comment]
You have been able to do this in Avicus for years! 

It isn't an issue, so please don't be concerned :)

**Comment by HBatman** [comment]
Still, you shouldn't really be able to do it. I spoke to Posighdun about it and he told me to make a GitHub Issue about it

**Comment by Palmidence** [comment]
Yay, Avicus is saved!

**Comment by javipepe** [comment]
Honestly this has the same function than `/msg` so if people are weirdo enough as for to type `/minecraft:tell` every time they want to send a message (pro tip: they won't 😂💥) I'm fine with it.

I don't think this is worthy of an issue, thanks for reporting anyway!

**Comment by steven5703** [comment]
@javipepe :100: :100: :joy: :joy:  :joy:  :joy:  :joy:  :joy:  :joy: :100: :boom: :+1: :eyes: :eyes: :tongue: :tongue: :heart_eyes: :heart_eyes: :boom: :eyes: :eggplant: :droplet: :tongue:

**Comment by HBatman** [comment]
Why's this re-opened? =/

**Comment by javipepe** [comment]
@thekeenant Huh?

**Comment by thekeenant** [comment]
It's a valid issue, we don't want users to have access to that command. There's some other ones too.
