### ISSUE TITLE
Walls Height-limit 

### ISSUE THREAD

**Issue by resepignev** [Avicus/Issues#803]
In the walls gamemode, before the walls drop the build height limit is greater (higher) than after the walls dropped. This can lead to skybases that are unable to reach for the other teams.

Maybe it's map specific, so the map was called Springwood.

To recreate it just join a game of walls build really high up in the sky (preferably until you reach the height limit) and wait until the walls drop. The other teams shouldn't be able to reach you.

**Comment by AustinLMayes** [comment]
This game mode will be gone in under a week, I think its fine 😄
