### ISSUE TITLE
Creative in Spectator Mode

### ISSUE THREAD

**Issue by FrostedCupcakez** [Avicus/Issues#811]
Able to access creative mode inventory in spectator mode in games. You can put on armour, get swords, etc.

**Comment by Palmidence** [comment]
You mean you can change the gamemode you're using as a spectator? Or can you change your gamemode to spectator /creative mode in-game?

**Comment by FrostedCupcakez** [comment]
You're in creative as a spectator and able get items etc.

**Comment by thekeenant** [comment]
Intended, at least for now?
