### ISSUE TITLE
Users lack permissions for friend commands

### ISSUE THREAD

**Issue by Kyoal** [Avicus/Issues#823]
Players are unable to use the command /friends. If you use '/remove [player], it comes up with 'You are not permitted to do that. Are you in the right mode?'.

**Comment by thekeenant** [comment]
Please stop creating issues with the wrong title. The command is working fine, it's simple you do not have permission!

**Comment by thekeenant** [comment]
They all seem to be working fine!

**Comment by thekeenant** [comment]
Added a new issue pertaining to this.

**Comment by thekeenant** [comment]
`/addfriend` and `/removefriend` work
