### ISSUE TITLE
Sounds are lacking when completing objectives/gaining kills

### ISSUE THREAD

**Issue by MapDevAvicus** [Avicus/Issues#824]
You don't have any sounds when completing a kill, 
the bow had different sounds when you ding ding and when you kill it used to have a different sound of completing an objective i think, and the same sound when breaking a monument/getting a kill with the sword. i think every player should have the sound to determine whenever you kill somebody. please add them back.

**Comment by MapDevAvicus** [comment]
also add objective touch/completion sounds

**Comment by MapDevAvicus** [comment]
AND sounds when getting credits.

**Comment by thekeenant** [comment]
Added!
