### ISSUE TITLE
Can't see names in tab

### ISSUE THREAD

**Issue by pizza334** [Avicus/Issues#829]
Shows the number of players but not the players usernames.
![2016-08-31_10 05 52](https://cloud.githubusercontent.com/assets/6341732/18122724/a545b992-6f62-11e6-8d94-59ac868d3909.png)

**Comment by Palmidence** [comment]
What version are you using? 1.8.9?

**Comment by thekeenant** [comment]
Remove all the mods, and get at least 1.8.1!

**Comment by thekeenant** [comment]
Reproduced!

**Comment by andrgorr** [comment]
Closing as we dropped back to the default tab for the time being.
