### ISSUE TITLE
A list of ingame issues

### ISSUE THREAD

**Issue by JoeVC123** [Avicus/Issues#834]
Non Donors can join full teams

Non Donors can chose their team

No sound on kill

No credits at the end of game

Player just disappears rather then blood nd credits, makes it hard for you to tell when youve got a kill.

When a player destroys a monument, it will come up in chat as he is on the opposite team - E,G, If someone on blue destroys a monument in chat it will come up as green have destroyed a monument

/staff doesnt work

When you /report someone it doesnt say in chat that the report has gone through, could lead to spam?

Maps where you spawn in from height (and fall to an area) doesnt have safety - so if you dont land in water you take damage ( Castle In The Rocks is an example of this)

**Comment by Palmidence** [comment]
Make an issue for each seperate concern, please. Most of these also have been reported, unfortunately.
