### ISSUE TITLE
Deathmatch games go on infinitely until a mapdev ends it

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#848]
The module to end maps based off of time located in the docs is not working? This makes the map not parse, and unfortunately makes it to where rotations like Mix, Competitive, & Deathmatch are not able to be played.

https://atlas.avicus.net/en/modules/results/

**Comment by thekeenant** [comment]
Modify the rots accordingly for now.

**Comment by Palmidence** [comment]
I was told that the documentation has been changed. Can we have new examples of usage?

**Comment by AustinLMayes** [comment]
This is fixed, check maps for reference

**Comment by Palmidence** [comment]
My bad, didn't realize you committed the fixes.
