### ISSUE TITLE
Lilypads can be placed as spectator to walk across water in-game

### ISSUE THREAD

**Issue by Palmidence** [Avicus/Issues#854]
It's client side, and probably a fix for this is to disable ability to put a lilypad in your inventory, or make it to where it can't be placed as spectator.

Forms of this are already being abused.

![](https://i.gyazo.com/91a07213e8dbbd3012c2f783e56306db.png)

**Comment by AustinLMayes** [comment]
This is client side, can't fix

**Comment by Palmidence** [comment]
You can't prevent it being dragged into an inventory?

**Comment by thekeenant** [comment]
I'm going to keep this open, not crucial to fix at the moment though. We could remove lilypads from invs.

**Comment by smitdalt** [comment]
Wow guys this is game breaking please fix it IMMEDIATELY
