### ISSUE TITLE
The play page is bugged

### ISSUE THREAD

**Issue by Eteh** [Avicus/Issues#857]
https://avicus.net/play doesn't show everyone whom is currently connected to Avicus, even when I am in Destroy1, it doesn't show my name.

**Comment by Palmidence** [comment]
Have you tested how long it takes to update? Might not be live.

Probably shouldn't be showing Beta and backend either.

**Comment by Eteh** [comment]
[http://prnt.sc/ccj0sr](url)

**Comment by Eteh** [comment]
`<img src="http://prnt.sc/ccj0sr">`

**Comment by Eteh** [comment]
![play](https://cloud.githubusercontent.com/assets/17596846/18132526/c62f96ac-6fc9-11e6-87c3-d9f3614e94da.png)

**Comment by thekeenant** [comment]
Playing does not mean everyone. It's accurate for how many players are in game. The list of players is limited as well.
