### ISSUE TITLE
Staff 'information' sub-forum on website

### ISSUE THREAD

**Issue by Kyoal** [Avicus/Issues#860]
The information sub-forum under 'staff' on the avicus forums, isn't working as I cannot view any discussions there unless it was done on purpose.

**Comment by legoche** [comment]
Same with me, I do not see a tab for the Map Developers

**Comment by Palmidence** [comment]
Piggybacking off of this, mapdevs need access to Staff Discussion so we can use the LoA and read other important information

**Comment by AustinLMayes** [comment]
Still an issue?
