### ISSUE TITLE
Staff...

### ISSUE THREAD

**Issue by ElementProHD** [Avicus/Issues#864]
/Staff - Doesn't work
Crossfire will not stop on its own.
Sr's can't use /end
Heads no longer show up on (http://avicus.net/stats)
When doing /list staff are not priority and no longer come at the top of the list which was helpful.

**Comment by Kyoal** [comment]
To add on, I think the devs are the only ones who currently show up on the stafflist. The other ranks don't.

**Comment by Palmidence** [comment]
Please make more descriptive titles than just "Staff"

**Comment by Palmidence** [comment]
And make an issue for each separate concern
