### ISSUE TITLE
Yellow won when two purple players completed both monuments

### ISSUE THREAD

**Issue by ElementProHD** [Avicus/Issues#869]
See here to understand: http://i.imgur.com/NnAW828.png

**Comment by Kyoal** [comment]
Yeah, this is still happening. It was apparently fixed but it doesn't seem to be.

**Comment by connorjayr** [comment]
This should be fixed, it probably just hasn't been deployed. The players that broke the monuments are actually on the Yellow team, but it colors their name with the team that owns the monument, not the team that broke it.
