### ISSUE TITLE
TDM always results in a tie

### ISSUE THREAD

**Issue by Pie55555** [Avicus/Issues#876]
Games like Supply and Crossfire on Competitive had games that resulted in 56-43 and would announce that it was a tie. 
https://gyazo.com/12ec880a5a09c9b6c4bc5e1711b5fb4b

**Comment by Jahaj1** [comment]
Can confirm, really annoying

**Comment by Palmidence** [comment]
Is this fixed at all?

**Comment by AustinLMayes** [comment]
Fixed

**Comment by Jahaj1** [comment]
Happened again

**Comment by Pie55555** [comment]
Open the issue again because it is not fixed
