### ISSUE TITLE
End-Game Rewards

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#877]

**Comment by thekeenant** [comment]
Added yesterday!

**Comment by Jahaj1** [comment]
![image](https://cloud.githubusercontent.com/assets/12214299/18221088/b006c276-713e-11e6-903c-23c1fb5529b5.png)
Uhh still didn't get any

**Comment by thekeenant** [comment]
Well you deserve some!!11

**Comment by andrgorr** [comment]
@thekeenant Is this still supposed to be open? 🐧😊

**Comment by thekeenant** [comment]
Yeah unfortunately

**Comment by AustinLMayes** [comment]
@iEli2tyree011
