### ISSUE TITLE
People appearing to specs when they die

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#882]
![image](https://cloud.githubusercontent.com/assets/12214299/18154869/f8e6c8b4-6fcd-11e6-9f17-c9fe650bb968.png)

**Comment by thekeenant** [comment]
Explain? How to reproduce? More details

**Comment by OldManTigerMask** [comment]
@thekeenant 
Well, I can help with that.

When you die everyone else sees you like as if you are frozen sitting in an invisible minecart. 

When you die you're supposed to be invisible to everyone.

**Comment by thekeenant** [comment]
I can't reproduce this..

**Comment by OldManTigerMask** [comment]
... Well it's happening I've seen it

**Comment by thekeenant** [comment]
Send a video please!

**Comment by thekeenant** [comment]
The essential thing that was not reported was that this was just for spectators.

Fixed

**Comment by Jahaj1** [comment]
"People appearing to specs when they die"

Its in the title but maybe I should have elaborated whoops.

**Comment by thekeenant** [comment]
Guess it sounded like you meant they appeared like spectators appear or something.
