### ISSUE TITLE
Credit Bugs

### ISSUE THREAD

**Issue by Clijmart** [Avicus/Issues#891]
Most of the player's credits got reset and such, but updated to the amount on Website afterwards.
Well, mine got reset to 38k, which may seem a good thing, but not when you know I had 68k...
Did I buy something on accident, or did something go wrong? I don't know.
But what I do know, is that this is a bug :3

Please try to fix these Credit Bugs <3
- Clijmart

**Comment by thekeenant** [comment]
You have 68k :stuck_out_tongue_closed_eyes:
