### ISSUE TITLE
Minimum Players Requirement (MIX & Other Game Servers)

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#892]
The Mix takes a minimum player count of 30.... which is weird because I don't think it should and sometimes it's 16, then it is 30 then it's 20, its kinda all over the place... Could it be fixed to something more reasonable (considering Amicus's player count) like a minimum of 6?

**Comment by thekeenant** [comment]
It's defined in the XML.

**Comment by Prodigy4532** [comment]
XML or YML? Xd

**Comment by thekeenant** [comment]
@Prodigy4532 XML. Each map defines the min player count.

**Comment by OldManTigerMask** [comment]
@thekeenant Still valid, right? Because I remember it should just be 6 to start not 10 or 20
