### ISSUE TITLE
More /settings

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#896]
None of the settings are there... other than PunishmentAlerts

This a bug?

**Comment by thekeenant** [comment]
We have yet to add more settings.

**Comment by KyloCode-Banned-Me** [comment]
did you do it yet

**Comment by thekeenant** [comment]
- Spectator visibility setting
- Death message self/friends/all settings

**Comment by OldManTigerMask** [comment]
@thekeenant Could we have the title Setting?
For example when an objective is destroyed, you either get a title message, hot bar message and/or chat message

**Comment by thekeenant** [comment]
We've added quite a few.

We'll be adding objective titles in the future.

**Comment by OldManTigerMask** [comment]
@thekeenant Thanks for clearing it up! 
Really looking forward to the titles :)
