### ISSUE TITLE
/reports is broken

### ISSUE THREAD

**Issue by Pelpel** [Avicus/Issues#905]
![screen shot 2016-09-01 at 20 00 48](https://cloud.githubusercontent.com/assets/10104759/18178529/042dc9e6-707f-11e6-9d22-cc78c73bb7c2.png)

**Comment by AustinLMayes** [comment]
1. ❤️ the Plast pack
2. Explain the commands you ran and the issue

**Comment by thekeenant** [comment]
@austinlmayes didn't you fix it

**Comment by AustinLMayes** [comment]
Yes
