### ISSUE TITLE
Kills on your profile page are ALWAYS 2 days old

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#908]
Hey!

So on your profile page, it shows your kills and it always says '2 days ago'.. I killed someone a few hours ago but it still says '2 days ago...'

**Comment by OldManTigerMask** [comment]
No, the stats just aren't updated... I think

**Comment by thekeenant** [comment]
Tracking now!

**Comment by OldManTigerMask** [comment]
@thekeenant Good Job :)
