### ISSUE TITLE
Three issues

### ISSUE THREAD

**Issue by ItsJunr** [Avicus/Issues#910]
1. My backpack duplicates the first page when when I go to the next page.
2. My credits went from 68k to 58k? I didn't spend them for a long time.
3. For the wool protection where the team can't go in its own wool room damages you til you die and when you do, it picks a random player and gives them free credits and kills.

**Comment by Palmidence** [comment]
_Do not:_

> Make 'lists' of issues regarding the server, instead make a separate issue for each problem.
