### ISSUE TITLE
Hit detection and client lag.

### ISSUE THREAD

**Issue by SevHoe** [Avicus/Issues#911]
Hit detection is worse overall, but half my hits don't work on servers other than Destroy1, which for some reason has better hit detection, but still fairly bad. I know for a fact a lot of my hits don't register because I see the critical particles, and after noting the difference in hit detection between Destroy 1 and 2 a couple of people agreed with me. Is this going to be temporary or permanent? If it's permanent reconsider because sooner is better.

Also, I'm getting more client (fps) lag on some maps, for example clay wars. I'm not sure if this is just my computer being weird which it does once in a while but I wasn't getting the full 144 fps I needed for my 144hz monitor on Clay wars which I usually do. I also stumbled upon some lag on some other maps but turned down settings a bit and was better, until I started fighting people. Then I realized it might just be the load the server is receiving giving me more lag if that makes any sense whatsoever. 

Anyways, I'd just like to say thanks and good luck with Atlas c;.

**Comment by thekeenant** [comment]
We have mixed reports about hit detection, but we do not modify it. Many claim it is better? We can also not impact client FPS unless the map has really bizarre issues.
