### ISSUE TITLE
/nh

### ISSUE THREAD

**Issue by SamDoesGamez** [Avicus/Issues#914]
where is /nh? (name history)

**Comment by Palmidence** [comment]
Not added yet. Will be.

**Comment by Jahaj1** [comment]
Regulars don't have perms to do /nh

**Comment by AustinLMayes** [comment]
This is intended. They can't do it on web so they shouldn't do it in game.

**Comment by Palmidence** [comment]
@AustinLMayes I mean, any user can do it with a website. It'd be more convinent for someone to be able to use the command /nh to see who is who, considering we're a close community it only is more helpful than it is obstructive. Shouldn't really be a staff exclusive command.

**Comment by Jahaj1** [comment]
^
We can't do it on the web either right.
