### ISSUE TITLE
Online when I'm not

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#916]
Profile says I'm online when I'm not

**Comment by AustinLMayes** [comment]
How did you leave? Were you kicked? Did the server crash?

**Comment by DaFrozenBlaze** [comment]
Should have taken a screenshot of it
No I just normally left the server. It's fine now though. If it happens again I'll be sure to remember to screenshot it

**Comment by AustinLMayes** [comment]
Reopen if happens again
