### ISSUE TITLE
Knocking players off doesn't get you the kill?

### ISSUE THREAD

**Issue by DomSpicer** [Avicus/Issues#917]
When you hit a player off into the void by sword, bow, sometimes it doesn't give you the kill? Instead it just has them falling into the void as shown through chat.

**Comment by Palmidence** [comment]
Can confirm, happened to me.

**Comment by thekeenant** [comment]
Yeah we have some issues with our kill tracker, on ground detection.

**Comment by thekeenant** [comment]
We've fixed spleefing. Now only hitting the ground has an issue. Void works fine.

**Comment by thekeenant** [comment]
Should be fixed!
