### ISSUE TITLE
Add colored stained clay to their respective teams on Clay Wars

### ISSUE THREAD

**Issue by DomSpicer** [Avicus/Issues#918]
On the map Clay Wars, a team doesn't have their coloured clay for a primary block but instead has white clay?

**Comment by Palmidence** [comment]
Not an issue, but I like this idea

**Comment by DomSpicer** [comment]
It is an issue? Previously before Atlas, I swear each team has their individual colours to their given team.

**Comment by Palmidence** [comment]
It wasn't like that at first, it was done the last month or two I believe but people had to walk through a region to get it. Multiple loadouts weren't really that widespread of a thing, and it seemed more hacky (e.g Mute City- sometimes people didn't get their items).

Atlas officially supports this now, I have added it. Thank you.
