### ISSUE TITLE
Castle on the rocks resistance removed?

### ISSUE THREAD

**Issue by DomSpicer** [Avicus/Issues#919]
Before atlas, Castle on the rocks had resistance if you jumped down from where you were just spawned. Now, after the update has been put in place, the resistance has been removed.

**Comment by AustinLMayes** [comment]
@Avicus/map-developers

**Comment by Palmidence** [comment]
Not sure why it wasn't there. I've readded it.

**Comment by DomSpicer** [comment]
Cheers
