### ISSUE TITLE
Mute city III scoreboard monuments

### ISSUE THREAD

**Issue by Kyoal** [Avicus/Issues#923]
On the scoreboard, which appears on the map Mute city III, team yellow has two left monuments. 
http://prntscr.com/cdesef shows what it looks like.

**Comment by Palmidence** [comment]
Fixed?

**Comment by Kyoal** [comment]
@Palmidence Still not fixed

**Comment by thekeenant** [comment]
Looks fixed to me...
![image](https://cloud.githubusercontent.com/assets/1189775/18226723/c9f42fe2-71d5-11e6-9b30-1437b9bdad0f.png)

**Comment by Kyoal** [comment]
It could've fixed now. However, earlier on today it definitely wasn't or it could've just been like that for me.

**Comment by Palmidence** [comment]
Changes don't push instantly, they change on restart now I believe.

**Comment by Tomqss** [comment]
Earlier today, yellow team still had two left monuments.

**Comment by Palmidence** [comment]
You sure it wasn't another Mute City? @Tomqss

**Comment by Palmidence** [comment]
The XML says it's fixed. Report back if it's Mute City III you experienced it on... there's a lot of Mute Cities.
