### ISSUE TITLE
when you do /tp, and the player is no longer online, you don't get an error message

### ISSUE THREAD

**Issue by Pelpel** [Avicus/Issues#925]

**Comment by thekeenant** [comment]
We didn't make the tp command :/

**Comment by Pelpel** [comment]
@thekeenant It works when players are online

**Comment by thekeenant** [comment]
I'm just saying we didn't make the command, so we can't change it, unless we add our own. Minecraft made it.

**Comment by Pelpel** [comment]
@thekeenant Ah, I understand now. Could it be added back please?
