### ISSUE TITLE
Ancientlake colors are messed up

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#929]
![image](https://cloud.githubusercontent.com/assets/12214299/18220669/eebf1d92-7139-11e6-9a5a-30fc3d433580.png)
You can see the sidebar

**Comment by Palmidence** [comment]
Fixed https://github.com/Avicus/atlas-maps/commit/2a2bb2500817ccaeb9ac8de61ff5eeb7ba1683b5
