### ISSUE TITLE
Make channels clickable

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#932]

**Comment by OldManTigerMask** [comment]
@thekeenant Why is it called channels? It makes sense for "make reports clickable"

**Comment by thekeenant** [comment]
A report is just a special type of channel. All channels (staff included) should be clickable. It's more generic.

**Comment by thekeenant** [comment]
Done!

**Comment by OldManTigerMask** [comment]
@thekeenant Thanks
