### ISSUE TITLE
/server issue?

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#938]
![image](https://cloud.githubusercontent.com/assets/9856226/18223275/c196bad4-71f5-11e6-9cb7-466faa3164f2.png)

This appears when you type /server

**Comment by AustinLMayes** [comment]
And the issue is?

**Comment by thekeenant** [comment]
😐🤔

**Comment by KyloCode-Banned-Me** [comment]
@AustinLMayes fix this

**Comment by OldManTigerMask** [comment]
@AustinLMayes It's not supposed to say the server list (fixed now)

@thekeenant 🤔 Thanks
