### ISSUE TITLE
/tp

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#940]
Allow /tp before game starts?.. Glitch or no?

**Comment by AustinLMayes** [comment]
No

**Comment by thekeenant** [comment]
So there is an issue where you can't tp if you /join and the match is starting.

**Comment by thekeenant** [comment]
Custom tp command added. Perms are still removed when you `/join`.

**Comment by andrgorr** [comment]
Is this fixed then @thekeenant ?

**Comment by Palmidence** [comment]
yes

**Comment by thekeenant** [comment]
No not yet. You can't `/tp` if you have `/join`'ed but are still spectating before the match. There isn't an elegant solution in Atlas yet.

**Comment by AustinLMayes** [comment]
Fixed by @thekeenant 🎉
