### ISSUE TITLE
No ranks in /s?

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#947]
![image](https://cloud.githubusercontent.com/assets/12214299/18255789/bf0958ac-7372-11e6-8a02-7df2bcb948fa.png)

**Comment by AustinLMayes** [comment]
Ranks will only show on same server, and never in chat channels

**Comment by Jahaj1** [comment]
Mods ranks show in /s and seniors + admins used to show but they don't anymore

**Comment by thekeenant** [comment]
I think certain commands like this is good to show ranks, but not everywhere.
