### ISSUE TITLE
Adding a friend via website 

### ISSUE THREAD

**Issue by ghost** [Avicus/Issues#954]
Hey!

So, when I try adding a friend, I always get this error: http://imgur.com/Rbt2nvY
http://imgur.com/2MiscmW

I have no idea why this happens..

**Comment by ghost** [comment]
Error
`can't write unknown attribute`friend_id' `

Backtrace
`/var/www/html/avicus.net/releases/20160904202908/app/controllers/users_controller.rb:51:in`add_friend' `

Params
`u => "507563"`
`controller => "users"`
`action => "add_friend"`
`user => "Tazz"`

That's the code [first 2 are missing a bracket, message me via slack to send it correctly, couldn't get it to work properly here] it just didn't happen on Tazz, I tried it on multiple people to see if it was an actual issue and the same thing always happened

**Comment by andrgorr** [comment]
Dealing with it.
