### ISSUE TITLE
You get stuck in Rendezvous' spawn sometimes

### ISSUE THREAD

**Issue by Jahaj1** [Avicus/Issues#959]
Move the spawnpoint up 1 block

**Comment by joelmce** [comment]
It's not just Rendezvous. Most maps have this issue!

**Comment by thekeenant** [comment]
Can I see a video? I've never encountered this.

Mapdevs, do not move spawnpoints up, that should not be necessary.

**Comment by joelmce** [comment]
@thekeenant tried to reproduce for video footage but had no luck. I guess this has been debunked? :stuck_out_tongue:

**Comment by thekeenant** [comment]
I'm happy to dose issues!

**Comment by thekeenant** [comment]
Close*
