### ISSUE TITLE
You can respawn with the flag in CTF

### ISSUE THREAD

**Issue by Pie55555** [Avicus/Issues#963]
If a player is killed while they are holding the flag, they will re spawn with the particles over their head but not the flag. If they go on the flag area to cap the flag, they will get a point.

**Comment by AustinLMayes** [comment]
Fixed by @thekeenant

**Comment by Pie55555** [comment]
Reopen this. It happened in both CTF maps and this isn`t a rare occurrence.

**Comment by thekeenant** [comment]
Likely haven't deployed.
