### ISSUE TITLE
Picking up wool spams the chat if the wool piece is in a different slot

### ISSUE THREAD

**Issue by Pie55555** [Avicus/Issues#967]
http://imgur.com/a/KCYvI

This happens when a player picks up the wool and then picks up the wool for another slot. This was common on a map that gives 64 wool for each slot in a chest like Rendezvous 2: Medows

**Comment by Pie55555** [comment]
Just an update it didn't happen when we played a map without 64 blocks of wool in a stack in the chest such as Senex CTW.

**Comment by thekeenant** [comment]
What do you mean in a different slot? And this?

> "picks up the wool and then picks up the wool for another slot"

**Comment by thekeenant** [comment]
Nevermind, I was able to reproduce it. Fixed upon restart.

No longer can you touch an already completed wool.
