### ISSUE TITLE
Warns

### ISSUE THREAD

**Issue by ItsJunr** [Avicus/Issues#968]
I warned myself to test it, pizza deleted it btw, and the warn didn't pop up so when players are warned, they are not aware of their warn. It didn't even say in chat I got a warn and all it said was: Sucessfully punished user.

**Comment by thekeenant** [comment]
What is your punishment message setting set to?

**Comment by ItsJunr** [comment]
It's just set to default rn, haven't changed it yet.

**Comment by thekeenant** [comment]
Fixed on deploy.
