### ISSUE TITLE
Punishments do not work on users who have shared same name

### ISSUE THREAD

**Issue by ItsJunr** [Avicus/Issues#973]
The punishments (tempban, ban, & kick) don't show on a user's profile nor remove the user from the server, so the player can still play.

**Comment by thekeenant** [comment]
It appears to be working fine? For example, you punished: https://avicus.net/dopefish13 recently. And it's there.

**Comment by ItsJunr** [comment]
Not on www.avicus.net/Knight187 and look at the recent punishments too

**Comment by ItsJunr** [comment]
He left, because I was froze him, so he can eventually leave.

**Comment by thekeenant** [comment]
Different issue actually. Renamed accordingly.

See: 
- https://namemc.com/profile/16017192-21bf-469b-a49d-f0236e9d4628
- https://namemc.com/profile/20c2168a-d1f6-4f46-b022-c0f9e49108a8

**Comment by ItsJunr** [comment]
Wait, so it punished on the other account and not the new one?

**Comment by ItsJunr** [comment]
Like the original Knight187 was banned, but not the one who had his name?

**Comment by thekeenant** [comment]
Correct! It's a bug.

**Comment by ItsJunr** [comment]
oh ok, ty

**Comment by thekeenant** [comment]
Pushed a fix, also punished them. I'm not sure if it is the proper punishment.
