### ISSUE TITLE
Join queue

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#979]
When you `/join` and the match is full, it would queue players to join so that immediately upon a player leaving the match, a user would join.

The con to this is that a player who is queued may go AFK.

**Comment by AustinLMayes** [comment]
a solution to the con is that the player in front go line could get a message in chat and a 30 sec grace period before the next person has the opportunity to join.

**Comment by flohlen** [comment]
players that don't move for 1 minute or don't interact with the game get removed from the queue.

**Comment by thekeenant** [comment]
The main idea at least in my opinion is to remove the need to type the command twice.

Maybe have a afk detection system, movement removes player from queue?

**Comment by thekeenant** [comment]
I think creating an afk event would be handy for different purposes actually.

**Comment by OldManTigerMask** [comment]
@thekeenant Why would movement remove players from the Queue? 
Doesn't it mean that you aren't AFK if you move? or am I just confused?

**Comment by thekeenant** [comment]
Lack of movement

**Comment by OldManTigerMask** [comment]
@thekeenant Ah ok, thanks.
Would the queue work like the normal joining system where it makes a player join the most balanced side or is it pre-decided when the match is full?
