### ISSUE TITLE
Player count on the server menu is displaying incorrect information

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#981]
So on the server menu it only displays the amount of people who are in the match. Is this a bug? because sometimes there are 48 people on the server but only 20 playing and... well it makes Avicus look bad because of the lower player count when searching for a server.

I think it should be the amount on the server, as for Avicus doesn't have many people (10 - 50), so if it displayed the player count it might be more encouraging to join a server with 47 people online instead of it saying 13/50 playing. Don't you think?

I'm actually not sure if this is a bug or not, which is why I'm posting it here.

**Comment by thekeenant** [comment]
It's not a bug, but I'm open for discussion on changing it.

We display the players in the match out of the number of players possible in the match so that players know if they can join the game or not.

**Comment by thekeenant** [comment]
Both counts are now displayed.

**Comment by OldManTigerMask** [comment]
@thekeenant Thanks!
