### ISSUE TITLE
Spawning?

### ISSUE THREAD

**Issue by Acceptancq** [Avicus/Issues#985]
Are you supposed to spawn in the tower and fall on Senex CTW?  As of right now you just spawn on the ground below it. It seems kind of odd to have a random tower like that and not use it. xd

**Comment by Palmidence** [comment]
It needs to be edited out

**Comment by OldManTigerMask** [comment]
@legoche Fix this please

**Comment by thekeenant** [comment]
Status @Palmidence ?

**Comment by legoche** [comment]
There's an updated version of the map that needs an XML update, it removes the tower.

**Comment by joelmce** [comment]
Fixed
