### ISSUE TITLE
CampiErbosi map boundary issue

### ISSUE THREAD

**Issue by thekeenant** [Avicus/Issues#987]
Slice in the middle of the void area where you can't build.

**Comment by OldManTigerMask** [comment]
@Fouled Please fix this, XML

**Comment by Palmidence** [comment]
@OldManTigerMask You don't need to assign people to do issues... that's the head map developer's job.

**Comment by OldManTigerMask** [comment]
@Palmidence :o I wasn't intending to do that, I was merely asking but alright, if you say so :)

**Comment by joelmce** [comment]
@Palmidence Do you know if this was intentional?

**Comment by Palmidence** [comment]
@joelmcelroy It's a bug

**Comment by legoche** [comment]
I don't know where you mean.

**Comment by joelmce** [comment]
I have no solution to this, other than the tedious task of adding regions block by block. Will look into seeing other efficient methods.

**Comment by AbusiveUser** [comment]
Fixed.
