### ISSUE TITLE
When the server in a server selector is colored red, it doesn't show the playercount

### ISSUE THREAD

**Issue by master00ofdsiware** [Avicus/Issues#988]
Normally, when a server is green in the server selector, a number is shown which is the player count. However, when the server is red, the player count is not shown. The playercount should be shown, because if it isn't then players may think that the server is empty or going down.

**Comment by OldManTigerMask** [comment]
Server Offline? That is why it's red
Player counts should not be displayed as for the server is offline.
@thekeenant 
@master00ofdsiware 
Right?...

**Comment by master00ofdsiware** [comment]
@OldManTigerMask it turns red when switching between maps, even if there is no restart.

**Comment by OldManTigerMask** [comment]
@master00ofdsiware Maybe put in the post, usually it turns blue and displays the player count... This is odd?

**Comment by DaFrozenBlaze** [comment]
I think it turns red when maps are cycled. And you can't join when it's red so if red means it's cycling then it makes no sense for you to not be able to join when cycling

**Comment by master00ofdsiware** [comment]
The red marker should still have the playercount on it, so that players do not think the server is empty just from looking at the server menu...

**Comment by OldManTigerMask** [comment]
I think the main reason why you can't join during cycling is probably to prevent adding extra permissions & confusion during switching maps 
@DaFrozenBlaze 

@master00ofdsiware Good point

**Comment by AustinLMayes** [comment]
Joining during cycling from the selector is not practical because the server could theoretically be restarting after the match. When the next match is cycled, we know for sure that this server can accept players.
