### ISSUE TITLE
Touching wool

### ISSUE THREAD

**Issue by DaFrozenBlaze** [Avicus/Issues#990]
https://gyazo.com/dc35e9401034d17e970f68af8dddaa92
It doesn't show that I touched it?

**Comment by thekeenant** [comment]
Did this happen to occur when you opened the chest with a block over it?

**Comment by DaFrozenBlaze** [comment]
No it was just the chest as it is, because I can't place blocks anyway
Anyway you should make it so that you can place and break blocks in the room

**Comment by thekeenant** [comment]
That is likely intentional by the map developer. The developers have no control over it.
