### ISSUE TITLE
Can play tracks in a public rotations.

### ISSUE THREAD

**Issue by pizza334** [Avicus/Issues#992]
If you do ./backpack and play a track not only does everyone get the message "{name} started playing a track" but it plays it to the whole server with no way of toggling off.
![2016-09-25_11 35 28](https://cloud.githubusercontent.com/assets/6341732/18814743/7f393b5a-8314-11e6-8567-eee98232bc30.png)

**Comment by ProfessorUtonium** [comment]
Pretty sure this is not an issue and is intended.

You can always turn down the volume for jukeboxes in your sound options
