### ISSUE TITLE
Keep getting tagged whenever post is updated

### ISSUE THREAD

**Issue by joelmce** [Avicus/Issues#996]
Not sure if you can fix this, but whenever I get tagged on a forum OP it sends an alert to me. That's good, right? However if someone just added something else to that thread without removing the tag it keeps spamming my alerts tab whenever the author updates it... Confusing? :stuck_out_tongue:

**Comment by thekeenant** [comment]
There isn't really a fix for this, other than just not deleting thr alert.

**Comment by joelmce** [comment]
If I delete it it'll come up again, if the author updates the OP

**Comment by thekeenant** [comment]
@AustinLMayes @javipepe

**Comment by andrgorr** [comment]
Got an idea that could help this, will try to look into it :sparkles:
