### ISSUE TITLE
Leaderboard displays banned players

### ISSUE THREAD

**Issue by OldManTigerMask** [Avicus/Issues#997]
The leaderboard should not display Permanently or Currently banned players. It is supposed to show the best players in Avicus not the hackers.

I suggest moving any banned users to the end or removing them entirely!

Thanks,
Tiger

**Comment by joelmce** [comment]
If you have a suggestion please post them on the forums. Github is for bug tracking...

**Comment by AustinLMayes** [comment]
It actually is an issue.

**Comment by OldManTigerMask** [comment]
@joelmcelroy Huh? This is a uhh issue post because banned users

**Comment by OldManTigerMask** [comment]
Finally.... I can open it again

**Comment by joelmce** [comment]
@AustinLMayes never knew this thing existed.

**Comment by OldManTigerMask** [comment]
@AustinLMayes I meant with Fixed I accidently closed it
